/* License information:
 *   -    Serialnumber:       CBD1100132
 *   - Date of license:       2011-05-06
 * **************************************************************
 * Software is licensed for:
 * BEIQI Foton Motor Co., Ltd.
 * Foton
 * Microcontroller: Infineon TriCore TC1767
 * Compiler: Tasking V3.3r1 */

#ifndef __V_VER_H
#  define __V_VER_H

#  define _VECTOR_SIP_VERSION  0x0201u
#  define _VECTOR_SIP_RELEASE_VERSION  0x13u
#  define _VECTOR_SIP_BUILD_VERSION  0x00u

#  define _COMMON_SIPVERSIONCHECK_VERSION  0x0301u
#  define _COMMON_SIPVERSIONCHECK_RELEASE_VERSION  0x38u
#  define COMMON_SIPVERSIONCHECK_LIB_SYMBOL VER__COMMON_SIPVERSIONCHECK_LIB_SYMBOL__030138__VER
#  define COMMON_SIPVERSIONCHECK_LIB_VERSION  0x00030138u

#  define _COMMON_VDEF_VERSION  0x0301u
#  define _COMMON_VDEF_RELEASE_VERSION  0x00u
#  define COMMON_VDEF_LIB_SYMBOL VER__COMMON_VDEF_LIB_SYMBOL__030100__VER
#  define COMMON_VDEF_LIB_VERSION  0x00030100u

#  define _CP_XCP_VERSION  0x0126u
#  define _CP_XCP_RELEASE_VERSION  0x03u
#  define CP_XCP_LIB_SYMBOL VER__CP_XCP_LIB_SYMBOL__012603__VER
#  define CP_XCP_LIB_VERSION  0x00012603u

#  define _CP_XCPONCAN_VERSION  0x0106u
#  define _CP_XCPONCAN_RELEASE_VERSION  0x00u
#  define CP_XCPONCAN_LIB_SYMBOL VER__CP_XCPONCAN_LIB_SYMBOL__010600__VER
#  define CP_XCPONCAN_LIB_VERSION  0x00010600u

#  define _DRVCAN_HW_VERSION  0x0214u
#  define _DRVCAN_HW_RELEASE_VERSION  0x00u
#  define DRVCAN_HW_LIB_SYMBOL VER__DRVCAN_HW_LIB_SYMBOL__021400__VER
#  define DRVCAN_HW_LIB_VERSION  0x00021400u

#  define _IL_VECTOR_VERSION  0x0502u
#  define _IL_VECTOR_RELEASE_VERSION  0x02u
#  define IL_VECTOR_LIB_SYMBOL VER__IL_VECTOR_LIB_SYMBOL__050202__VER
#  define IL_VECTOR_LIB_VERSION  0x00050202u

#  define _VSTDLIB_HW_VERSION  0x0108u
#  define _VSTDLIB_HW_RELEASE_VERSION  0x00u
#  define VSTDLIB_HW_LIB_SYMBOL VER__VSTDLIB_HW_LIB_SYMBOL__010800__VER
#  define VSTDLIB_HW_LIB_VERSION  0x00010800u
#endif
