/* -----------------------------------------------------------------------------
  Filename:    can_par.h
  Description: Toolversion: 02.01.13.01.10.01.32.00.00.00
                
                Serial Number: CBD1100132
                Customer Info: BEIQI Foton Motor Co., Ltd.
                               Foton
                               Microcontroller: Infineon TriCore TC1767
                               Compiler: Tasking V3.3r1
                
                
                Generator Fwk   : GENy 
                Generator Module: DrvCan__base
                
                Configuration   : D:\TaskingTc&GENywork\R1556\BMS_R1556\Bsw\Can\configCAN\configGENy\R1556.gny
                
                ECU: 
                        TargetSystem: Hw_TricoreCpu
                        Compiler:     Tasking
                        Derivates:    INFINEON_TC1767
                
                Channel "Channel0":
                        Databasefile: D:\DBC WORK\R1556\R1556_Veh_02.dbc
                        Bussystem:    CAN
                        Manufacturer: Vector
                        Node:         Bcu
                Channel "Channel1":
                        Databasefile: D:\DBC WORK\R1556\R1556_Inter_02.dbc
                        Bussystem:    CAN
                        Manufacturer: Vector
                        Node:         Bcu

  Generated by , 2015-12-25  17:24:00
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2008 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__CAN_PAR_H__)
#define __CAN_PAR_H__

#include "can_cfg.h"
#include "v_inc.h"
#include "drv_par.h"

/* -----------------------------------------------------------------------------
    &&&~ Extern declarations of callback functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 4 START */

extern void ApplCanBusOff(CanChannelHandle channel);

/* CODE CATEGORY 4 END */


/* CODE CATEGORY 4 START */

extern void ApplCanWakeUp(CanChannelHandle channel);

/* CODE CATEGORY 4 END */


#if defined(C_MULTIPLE_RECEIVE_CHANNEL) || defined(C_SINGLE_RECEIVE_CHANNEL)
#endif

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgBcu_CarCharBPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgVcuToBmsPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgHcuData3PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgHcuData0PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgRtcTimePreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgRtcIoPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BStatePreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BBalState_0PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AStatePreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60ABalState_1PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60ABalState_0PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData15PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData08PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData07PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData06PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData05PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData04PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData03PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData02PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData00PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc33BData15PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData14PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData13PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData12PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData11PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData10PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData09PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData08PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData07PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData06PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData05PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData04PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData03PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData02PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData01PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 IlMsgMc60AData00PreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern vuint8 XcpPreCopy(CanRxInfoStructPtr rxStruct);
/* CODE CATEGORY 1 END */


/* -----------------------------------------------------------------------------
    &&&~ Extern declarations of confirmation functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 1 START */
extern void XcpConfirmation(CanTransmitHandle txObject);
/* CODE CATEGORY 1 END */



/* -----------------------------------------------------------------------------
    &&&~ Extern declarations of indication functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 1 START */
extern void BCOM_RxBcu_CarCharB(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCOM_RxUdsRx(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCOM_HcuData3(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCOM_HcuData1(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCOM_HcuData0(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCOM_RtcMulReq(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCOM_RtcRxMsg(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCOM_Mc33BState(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCOM_Mc60AState(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */

/* CODE CATEGORY 1 START */
extern void BCOM_BcuRxMdulCtrl(CanReceiveHandle rcvObject);
/* CODE CATEGORY 1 END */



/* -----------------------------------------------------------------------------
    &&&~ Multiple Callback Functions
 ----------------------------------------------------------------------------- */

/* CODE CATEGORY 3 START */
extern C_CALLBACK_1 void C_CALLBACK_2 IlCanCancelNotification(CanTransmitHandle txHandle);
/* CODE CATEGORY 3 END */




/* -----------------------------------------------------------------------------
    &&&~ Handles of send objects
 ----------------------------------------------------------------------------- */

#define CanTxBcuTime                         0
#define CanTxBmsToVcu_E                      1
#define CanTxBmsToVcu_D                      2
#define CanTxBcu_CarCharA                    3
#define CanTxBmsToVcu_C                      4
#define CanTxBmsTxVcu_B                      5
#define CanTxBcuToVcu_A                      6
#define CanTxUdsTx                           7
#define CanTxBcuSD6                          8
#define CanTxBcuSD5                          9
#define CanTxBcuSD4                          10
#define CanTxBcuSD3                          11
#define CanTxBcuSD2                          12
#define CanTxBcuSD1                          13
#define CanTxTxXCP                           14
#define CanTxBcuCHAInfo2                     15
#define CanTxBcuCHAInfo1                     16
#define CanTxUdsInterRx                      17
#define CanTxBcuBalCmdMc60A_1                18
#define CanTxRtcRxMulData                    19
#define CanTxRtcRxMulReq                     20
#define CanTxRtcRxMsg                        21
#define CanTxBcuBalCmdMc33B_0                22
#define CanTxBcuBalCmdMc60A_0                23
#define CanTxBcuInit                         24
#define CanTxBcuSyc100msMsg                  25


/* -----------------------------------------------------------------------------
    &&&~ Access to confirmation flags
 ----------------------------------------------------------------------------- */

#define BcuTime_conf_b                       (CanConfirmationFlags.w[0].b0)
#define CanWriteSyncBcuTime_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuTime_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BmsToVcu_E_conf_b                    (CanConfirmationFlags.w[0].b1)
#define CanWriteSyncBmsToVcu_E_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BmsToVcu_E_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BmsToVcu_D_conf_b                    (CanConfirmationFlags.w[0].b2)
#define CanWriteSyncBmsToVcu_D_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BmsToVcu_D_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define Bcu_CarCharA_conf_b                  (CanConfirmationFlags.w[0].b3)
#define CanWriteSyncBcu_CarCharA_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  Bcu_CarCharA_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BmsToVcu_C_conf_b                    (CanConfirmationFlags.w[0].b4)
#define CanWriteSyncBmsToVcu_C_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BmsToVcu_C_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BmsTxVcu_B_conf_b                    (CanConfirmationFlags.w[0].b5)
#define CanWriteSyncBmsTxVcu_B_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BmsTxVcu_B_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuToVcu_A_conf_b                    (CanConfirmationFlags.w[0].b6)
#define CanWriteSyncBcuToVcu_A_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuToVcu_A_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define UdsTx_conf_b                         (CanConfirmationFlags.w[0].b7)
#define CanWriteSyncUdsTx_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  UdsTx_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuSD6_conf_b                        (CanConfirmationFlags.w[0].b10)
#define CanWriteSyncBcuSD6_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuSD6_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuSD5_conf_b                        (CanConfirmationFlags.w[0].b11)
#define CanWriteSyncBcuSD5_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuSD5_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuSD4_conf_b                        (CanConfirmationFlags.w[0].b12)
#define CanWriteSyncBcuSD4_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuSD4_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuSD3_conf_b                        (CanConfirmationFlags.w[0].b13)
#define CanWriteSyncBcuSD3_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuSD3_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuSD2_conf_b                        (CanConfirmationFlags.w[0].b14)
#define CanWriteSyncBcuSD2_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuSD2_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuSD1_conf_b                        (CanConfirmationFlags.w[0].b15)
#define CanWriteSyncBcuSD1_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuSD1_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define TxXCP_conf_b                         (CanConfirmationFlags.w[0].b16)
#define CanWriteSyncTxXCP_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  TxXCP_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuCHAInfo2_conf_b                   (CanConfirmationFlags.w[0].b17)
#define CanWriteSyncBcuCHAInfo2_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuCHAInfo2_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuCHAInfo1_conf_b                   (CanConfirmationFlags.w[0].b20)
#define CanWriteSyncBcuCHAInfo1_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuCHAInfo1_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define UdsInterRx_conf_b                    (CanConfirmationFlags.w[0].b21)
#define CanWriteSyncUdsInterRx_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  UdsInterRx_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuBalCmdMc60A_1_conf_b              (CanConfirmationFlags.w[0].b22)
#define CanWriteSyncBcuBalCmdMc60A_1_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuBalCmdMc60A_1_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define RtcRxMulData_conf_b                  (CanConfirmationFlags.w[0].b23)
#define CanWriteSyncRtcRxMulData_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  RtcRxMulData_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define RtcRxMulReq_conf_b                   (CanConfirmationFlags.w[0].b24)
#define CanWriteSyncRtcRxMulReq_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  RtcRxMulReq_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define RtcRxMsg_conf_b                      (CanConfirmationFlags.w[0].b25)
#define CanWriteSyncRtcRxMsg_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  RtcRxMsg_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuBalCmdMc33B_0_conf_b              (CanConfirmationFlags.w[0].b26)
#define CanWriteSyncBcuBalCmdMc33B_0_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuBalCmdMc33B_0_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuBalCmdMc60A_0_conf_b              (CanConfirmationFlags.w[0].b27)
#define CanWriteSyncBcuBalCmdMc60A_0_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuBalCmdMc60A_0_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuInit_conf_b                       (CanConfirmationFlags.w[0].b30)
#define CanWriteSyncBcuInit_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuInit_conf_b = (x); \
  CanEndFlagWriteSync(); \
}
#define BcuSyc100msMsg_conf_b                (CanConfirmationFlags.w[0].b31)
#define CanWriteSyncBcuSyc100msMsg_conf_b(x) \
{ \
  CanStartFlagWriteSync(); \
  BcuSyc100msMsg_conf_b = (x); \
  CanEndFlagWriteSync(); \
}


/* -----------------------------------------------------------------------------
    &&&~ Handles of receive objects
 ----------------------------------------------------------------------------- */

#define CanRxBcu_CarCharB                    0
#define CanRxVcuToBms                        1
#define CanRxUdsRx                           2
#define CanRxUdsInterTx                      3
#define CanRxHcuData3                        4
#define CanRxHcuData1                        5
#define CanRxHcuData0                        6
#define CanRxRtcTime                         7
#define CanRxRtcIo                           8
#define CanRxRtcTxMulReq                     9
#define CanRxRtcTxMsg                        10
#define CanRxMc33BState                      11
#define CanRxMc33BBalState_0                 12
#define CanRxMc60AState                      13
#define CanRxMc60ABalState_1                 14
#define CanRxMc60ABalState_0                 15
#define CanRxMc60AData15                     16
#define CanRxMc33BData08                     17
#define CanRxMc33BData07                     18
#define CanRxMc33BData06                     19
#define CanRxMc33BData05                     20
#define CanRxMc33BData04                     21
#define CanRxMc33BData03                     22
#define CanRxMc33BData02                     23
#define CanRxMc33BData01                     24
#define CanRxMc33BData00                     25
#define CanRxMc33BData15                     26
#define CanRxMc60AData14                     27
#define CanRxMc60AData13                     28
#define CanRxMc60AData12                     29
#define CanRxMc60AData11                     30
#define CanRxMc60AData10                     31
#define CanRxMc60AData09                     32
#define CanRxMc60AData08                     33
#define CanRxMc60AData07                     34
#define CanRxMc60AData06                     35
#define CanRxMc60AData05                     36
#define CanRxMc60AData04                     37
#define CanRxMc60AData03                     38
#define CanRxMc60AData02                     39
#define CanRxMc60AData01                     40
#define CanRxMc60AData00                     41
#define CanRxMcInit                          42
#define CanRxRxXCP                           43


/* -----------------------------------------------------------------------------
    &&&~ Access to indication flags
 ----------------------------------------------------------------------------- */

#define RxXCP_ind_b                          (CanIndicationFlags.w[0].b0)
#define CanWriteSyncRxXCP_ind_b(x) \
{ \
  CanStartFlagWriteSync(); \
  RxXCP_ind_b = (x); \
  CanEndFlagWriteSync(); \
}


/* -----------------------------------------------------------------------------
    &&&~ Access to signals
 ----------------------------------------------------------------------------- */

#define b_XCP_TxData_0_b                     (TxXCP.TxXCP.XCP_TxData_0)
#define b_XCP_TxData_1_b                     (TxXCP.TxXCP.XCP_TxData_1)
#define b_XCP_TxData_2_b                     (TxXCP.TxXCP.XCP_TxData_2)
#define b_XCP_TxData_3_b                     (TxXCP.TxXCP.XCP_TxData_3)
#define b_XCP_TxData_4_b                     (TxXCP.TxXCP.XCP_TxData_4)
#define b_XCP_TxData_5_b                     (TxXCP.TxXCP.XCP_TxData_5)
#define b_XCP_TxData_6_b                     (TxXCP.TxXCP.XCP_TxData_6)
#define b_XCP_TxData_7_b                     (TxXCP.TxXCP.XCP_TxData_7)
#define b_XCP_RxData_0_b                     (RxXCP.RxXCP.XCP_RxData_0)
#define b_XCP_RxData_1_b                     (RxXCP.RxXCP.XCP_RxData_1)
#define b_XCP_RxData_2_b                     (RxXCP.RxXCP.XCP_RxData_2)
#define b_XCP_RxData_3_b                     (RxXCP.RxXCP.XCP_RxData_3)
#define b_XCP_RxData_4_b                     (RxXCP.RxXCP.XCP_RxData_4)
#define b_XCP_RxData_5_b                     (RxXCP.RxXCP.XCP_RxData_5)
#define b_XCP_RxData_6_b                     (RxXCP.RxXCP.XCP_RxData_6)
#define b_XCP_RxData_7_b                     (RxXCP.RxXCP.XCP_RxData_7)


/* -----------------------------------------------------------------------------
    &&&~ Access to data bytes of Rx messages
 ----------------------------------------------------------------------------- */

/* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */
#define c1_Bcu_CarCharB_c                    (Bcu_CarCharB._c[0])
#define c2_Bcu_CarCharB_c                    (Bcu_CarCharB._c[1])
#define c3_Bcu_CarCharB_c                    (Bcu_CarCharB._c[2])
#define c4_Bcu_CarCharB_c                    (Bcu_CarCharB._c[3])
#define c5_Bcu_CarCharB_c                    (Bcu_CarCharB._c[4])

/* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */
#define c1_VcuToBms_c                        (VcuToBms._c[0])

/* ID: 0x000007e0, Handle: 2, UdsRx [FC] */
#define c1_UdsRx_c                           (UdsRx._c[0])
#define c2_UdsRx_c                           (UdsRx._c[1])
#define c3_UdsRx_c                           (UdsRx._c[2])
#define c4_UdsRx_c                           (UdsRx._c[3])
#define c5_UdsRx_c                           (UdsRx._c[4])
#define c6_UdsRx_c                           (UdsRx._c[5])
#define c7_UdsRx_c                           (UdsRx._c[6])
#define c8_UdsRx_c                           (UdsRx._c[7])

/* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */
#define c1_UdsInterTx_c                      (UdsInterTx._c[0])
#define c2_UdsInterTx_c                      (UdsInterTx._c[1])
#define c3_UdsInterTx_c                      (UdsInterTx._c[2])
#define c4_UdsInterTx_c                      (UdsInterTx._c[3])
#define c5_UdsInterTx_c                      (UdsInterTx._c[4])
#define c6_UdsInterTx_c                      (UdsInterTx._c[5])
#define c7_UdsInterTx_c                      (UdsInterTx._c[6])
#define c8_UdsInterTx_c                      (UdsInterTx._c[7])

/* ID: 0x00000522, Handle: 4, HcuData3 [FC] */
#define c1_HcuData3_c                        (HcuData3._c[0])
#define c2_HcuData3_c                        (HcuData3._c[1])
#define c3_HcuData3_c                        (HcuData3._c[2])
#define c4_HcuData3_c                        (HcuData3._c[3])
#define c5_HcuData3_c                        (HcuData3._c[4])
#define c6_HcuData3_c                        (HcuData3._c[5])
#define c7_HcuData3_c                        (HcuData3._c[6])
#define c8_HcuData3_c                        (HcuData3._c[7])

/* ID: 0x00000521, Handle: 5, HcuData1 [FC] */
#define c1_HcuData1_c                        (HcuData1._c[0])
#define c2_HcuData1_c                        (HcuData1._c[1])
#define c3_HcuData1_c                        (HcuData1._c[2])

/* ID: 0x00000520, Handle: 6, HcuData0 [FC] */
#define c1_HcuData0_c                        (HcuData0._c[0])
#define c2_HcuData0_c                        (HcuData0._c[1])
#define c3_HcuData0_c                        (HcuData0._c[2])
#define c4_HcuData0_c                        (HcuData0._c[3])
#define c5_HcuData0_c                        (HcuData0._c[4])
#define c6_HcuData0_c                        (HcuData0._c[5])
#define c7_HcuData0_c                        (HcuData0._c[6])

/* ID: 0x00000306, Handle: 7, RtcTime [BC] */
#define c1_RtcTime_c                         (RtcTime._c[0])
#define c2_RtcTime_c                         (RtcTime._c[1])
#define c3_RtcTime_c                         (RtcTime._c[2])
#define c4_RtcTime_c                         (RtcTime._c[3])
#define c5_RtcTime_c                         (RtcTime._c[4])
#define c6_RtcTime_c                         (RtcTime._c[5])
#define c7_RtcTime_c                         (RtcTime._c[6])

/* ID: 0x00000305, Handle: 8, RtcIo [BC] */
#define c1_RtcIo_c                           (RtcIo._c[0])
#define c2_RtcIo_c                           (RtcIo._c[1])
#define c3_RtcIo_c                           (RtcIo._c[2])
#define c4_RtcIo_c                           (RtcIo._c[3])
#define c5_RtcIo_c                           (RtcIo._c[4])
#define c6_RtcIo_c                           (RtcIo._c[5])

/* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */
#define c1_RtcTxMulReq_c                     (RtcTxMulReq._c[0])
#define c2_RtcTxMulReq_c                     (RtcTxMulReq._c[1])
#define c3_RtcTxMulReq_c                     (RtcTxMulReq._c[2])
#define c4_RtcTxMulReq_c                     (RtcTxMulReq._c[3])
#define c5_RtcTxMulReq_c                     (RtcTxMulReq._c[4])
#define c6_RtcTxMulReq_c                     (RtcTxMulReq._c[5])
#define c7_RtcTxMulReq_c                     (RtcTxMulReq._c[6])
#define c8_RtcTxMulReq_c                     (RtcTxMulReq._c[7])

/* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */
#define c1_RtcTxMsg_c                        (RtcTxMsg._c[0])
#define c2_RtcTxMsg_c                        (RtcTxMsg._c[1])
#define c3_RtcTxMsg_c                        (RtcTxMsg._c[2])
#define c4_RtcTxMsg_c                        (RtcTxMsg._c[3])
#define c5_RtcTxMsg_c                        (RtcTxMsg._c[4])
#define c6_RtcTxMsg_c                        (RtcTxMsg._c[5])
#define c7_RtcTxMsg_c                        (RtcTxMsg._c[6])
#define c8_RtcTxMsg_c                        (RtcTxMsg._c[7])

/* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */
#define c1_Mc33BState_c                      (Mc33BState._c[0])
#define c2_Mc33BState_c                      (Mc33BState._c[1])
#define c3_Mc33BState_c                      (Mc33BState._c[2])
#define c4_Mc33BState_c                      (Mc33BState._c[3])
#define c5_Mc33BState_c                      (Mc33BState._c[4])
#define c6_Mc33BState_c                      (Mc33BState._c[5])
#define c7_Mc33BState_c                      (Mc33BState._c[6])
#define c8_Mc33BState_c                      (Mc33BState._c[7])

/* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */
#define c1_Mc33BBalState_0_c                 (Mc33BBalState_0._c[0])
#define c2_Mc33BBalState_0_c                 (Mc33BBalState_0._c[1])
#define c3_Mc33BBalState_0_c                 (Mc33BBalState_0._c[2])
#define c4_Mc33BBalState_0_c                 (Mc33BBalState_0._c[3])
#define c5_Mc33BBalState_0_c                 (Mc33BBalState_0._c[4])
#define c6_Mc33BBalState_0_c                 (Mc33BBalState_0._c[5])

/* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */
#define c1_Mc60AState_c                      (Mc60AState._c[0])
#define c2_Mc60AState_c                      (Mc60AState._c[1])
#define c3_Mc60AState_c                      (Mc60AState._c[2])
#define c4_Mc60AState_c                      (Mc60AState._c[3])
#define c5_Mc60AState_c                      (Mc60AState._c[4])
#define c6_Mc60AState_c                      (Mc60AState._c[5])
#define c7_Mc60AState_c                      (Mc60AState._c[6])
#define c8_Mc60AState_c                      (Mc60AState._c[7])

/* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */
#define c1_Mc60ABalState_1_c                 (Mc60ABalState_1._c[0])
#define c2_Mc60ABalState_1_c                 (Mc60ABalState_1._c[1])

/* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */
#define c1_Mc60ABalState_0_c                 (Mc60ABalState_0._c[0])
#define c2_Mc60ABalState_0_c                 (Mc60ABalState_0._c[1])
#define c3_Mc60ABalState_0_c                 (Mc60ABalState_0._c[2])
#define c4_Mc60ABalState_0_c                 (Mc60ABalState_0._c[3])
#define c5_Mc60ABalState_0_c                 (Mc60ABalState_0._c[4])
#define c6_Mc60ABalState_0_c                 (Mc60ABalState_0._c[5])
#define c7_Mc60ABalState_0_c                 (Mc60ABalState_0._c[6])
#define c8_Mc60ABalState_0_c                 (Mc60ABalState_0._c[7])

/* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */
#define c1_Mc60AData15_c                     (Mc60AData15._c[0])
#define c2_Mc60AData15_c                     (Mc60AData15._c[1])
#define c3_Mc60AData15_c                     (Mc60AData15._c[2])
#define c4_Mc60AData15_c                     (Mc60AData15._c[3])

/* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */
#define c1_Mc33BData08_c                     (Mc33BData08._c[0])
#define c2_Mc33BData08_c                     (Mc33BData08._c[1])

/* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */
#define c1_Mc33BData07_c                     (Mc33BData07._c[0])
#define c2_Mc33BData07_c                     (Mc33BData07._c[1])
#define c3_Mc33BData07_c                     (Mc33BData07._c[2])
#define c4_Mc33BData07_c                     (Mc33BData07._c[3])
#define c5_Mc33BData07_c                     (Mc33BData07._c[4])
#define c6_Mc33BData07_c                     (Mc33BData07._c[5])
#define c7_Mc33BData07_c                     (Mc33BData07._c[6])
#define c8_Mc33BData07_c                     (Mc33BData07._c[7])

/* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */
#define c1_Mc33BData06_c                     (Mc33BData06._c[0])
#define c2_Mc33BData06_c                     (Mc33BData06._c[1])
#define c3_Mc33BData06_c                     (Mc33BData06._c[2])
#define c4_Mc33BData06_c                     (Mc33BData06._c[3])
#define c5_Mc33BData06_c                     (Mc33BData06._c[4])
#define c6_Mc33BData06_c                     (Mc33BData06._c[5])
#define c7_Mc33BData06_c                     (Mc33BData06._c[6])
#define c8_Mc33BData06_c                     (Mc33BData06._c[7])

/* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */
#define c1_Mc33BData05_c                     (Mc33BData05._c[0])
#define c2_Mc33BData05_c                     (Mc33BData05._c[1])
#define c3_Mc33BData05_c                     (Mc33BData05._c[2])
#define c4_Mc33BData05_c                     (Mc33BData05._c[3])
#define c5_Mc33BData05_c                     (Mc33BData05._c[4])
#define c6_Mc33BData05_c                     (Mc33BData05._c[5])
#define c7_Mc33BData05_c                     (Mc33BData05._c[6])
#define c8_Mc33BData05_c                     (Mc33BData05._c[7])

/* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */
#define c1_Mc33BData04_c                     (Mc33BData04._c[0])
#define c2_Mc33BData04_c                     (Mc33BData04._c[1])
#define c3_Mc33BData04_c                     (Mc33BData04._c[2])
#define c4_Mc33BData04_c                     (Mc33BData04._c[3])
#define c5_Mc33BData04_c                     (Mc33BData04._c[4])
#define c6_Mc33BData04_c                     (Mc33BData04._c[5])
#define c7_Mc33BData04_c                     (Mc33BData04._c[6])
#define c8_Mc33BData04_c                     (Mc33BData04._c[7])

/* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */
#define c1_Mc33BData03_c                     (Mc33BData03._c[0])
#define c2_Mc33BData03_c                     (Mc33BData03._c[1])
#define c3_Mc33BData03_c                     (Mc33BData03._c[2])
#define c4_Mc33BData03_c                     (Mc33BData03._c[3])
#define c5_Mc33BData03_c                     (Mc33BData03._c[4])
#define c6_Mc33BData03_c                     (Mc33BData03._c[5])
#define c7_Mc33BData03_c                     (Mc33BData03._c[6])
#define c8_Mc33BData03_c                     (Mc33BData03._c[7])

/* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */
#define c1_Mc33BData02_c                     (Mc33BData02._c[0])
#define c2_Mc33BData02_c                     (Mc33BData02._c[1])
#define c3_Mc33BData02_c                     (Mc33BData02._c[2])
#define c4_Mc33BData02_c                     (Mc33BData02._c[3])
#define c5_Mc33BData02_c                     (Mc33BData02._c[4])
#define c6_Mc33BData02_c                     (Mc33BData02._c[5])
#define c7_Mc33BData02_c                     (Mc33BData02._c[6])
#define c8_Mc33BData02_c                     (Mc33BData02._c[7])

/* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */
#define c1_Mc33BData01_c                     (Mc33BData01._c[0])
#define c2_Mc33BData01_c                     (Mc33BData01._c[1])
#define c3_Mc33BData01_c                     (Mc33BData01._c[2])
#define c4_Mc33BData01_c                     (Mc33BData01._c[3])
#define c5_Mc33BData01_c                     (Mc33BData01._c[4])
#define c6_Mc33BData01_c                     (Mc33BData01._c[5])
#define c7_Mc33BData01_c                     (Mc33BData01._c[6])
#define c8_Mc33BData01_c                     (Mc33BData01._c[7])

/* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */
#define c1_Mc33BData00_c                     (Mc33BData00._c[0])
#define c2_Mc33BData00_c                     (Mc33BData00._c[1])
#define c3_Mc33BData00_c                     (Mc33BData00._c[2])
#define c4_Mc33BData00_c                     (Mc33BData00._c[3])
#define c5_Mc33BData00_c                     (Mc33BData00._c[4])
#define c6_Mc33BData00_c                     (Mc33BData00._c[5])
#define c7_Mc33BData00_c                     (Mc33BData00._c[6])
#define c8_Mc33BData00_c                     (Mc33BData00._c[7])

/* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */
#define c1_Mc33BData15_c                     (Mc33BData15._c[0])
#define c2_Mc33BData15_c                     (Mc33BData15._c[1])
#define c3_Mc33BData15_c                     (Mc33BData15._c[2])
#define c4_Mc33BData15_c                     (Mc33BData15._c[3])

/* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */
#define c1_Mc60AData14_c                     (Mc60AData14._c[0])
#define c2_Mc60AData14_c                     (Mc60AData14._c[1])
#define c3_Mc60AData14_c                     (Mc60AData14._c[2])
#define c4_Mc60AData14_c                     (Mc60AData14._c[3])
#define c5_Mc60AData14_c                     (Mc60AData14._c[4])
#define c6_Mc60AData14_c                     (Mc60AData14._c[5])
#define c7_Mc60AData14_c                     (Mc60AData14._c[6])
#define c8_Mc60AData14_c                     (Mc60AData14._c[7])

/* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */
#define c1_Mc60AData13_c                     (Mc60AData13._c[0])
#define c2_Mc60AData13_c                     (Mc60AData13._c[1])
#define c3_Mc60AData13_c                     (Mc60AData13._c[2])
#define c4_Mc60AData13_c                     (Mc60AData13._c[3])
#define c5_Mc60AData13_c                     (Mc60AData13._c[4])
#define c6_Mc60AData13_c                     (Mc60AData13._c[5])
#define c7_Mc60AData13_c                     (Mc60AData13._c[6])
#define c8_Mc60AData13_c                     (Mc60AData13._c[7])

/* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */
#define c1_Mc60AData12_c                     (Mc60AData12._c[0])
#define c2_Mc60AData12_c                     (Mc60AData12._c[1])
#define c3_Mc60AData12_c                     (Mc60AData12._c[2])
#define c4_Mc60AData12_c                     (Mc60AData12._c[3])
#define c5_Mc60AData12_c                     (Mc60AData12._c[4])
#define c6_Mc60AData12_c                     (Mc60AData12._c[5])
#define c7_Mc60AData12_c                     (Mc60AData12._c[6])
#define c8_Mc60AData12_c                     (Mc60AData12._c[7])

/* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */
#define c1_Mc60AData11_c                     (Mc60AData11._c[0])
#define c2_Mc60AData11_c                     (Mc60AData11._c[1])
#define c3_Mc60AData11_c                     (Mc60AData11._c[2])
#define c4_Mc60AData11_c                     (Mc60AData11._c[3])
#define c5_Mc60AData11_c                     (Mc60AData11._c[4])
#define c6_Mc60AData11_c                     (Mc60AData11._c[5])
#define c7_Mc60AData11_c                     (Mc60AData11._c[6])
#define c8_Mc60AData11_c                     (Mc60AData11._c[7])

/* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */
#define c1_Mc60AData10_c                     (Mc60AData10._c[0])
#define c2_Mc60AData10_c                     (Mc60AData10._c[1])
#define c3_Mc60AData10_c                     (Mc60AData10._c[2])
#define c4_Mc60AData10_c                     (Mc60AData10._c[3])
#define c5_Mc60AData10_c                     (Mc60AData10._c[4])
#define c6_Mc60AData10_c                     (Mc60AData10._c[5])
#define c7_Mc60AData10_c                     (Mc60AData10._c[6])
#define c8_Mc60AData10_c                     (Mc60AData10._c[7])

/* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */
#define c1_Mc60AData09_c                     (Mc60AData09._c[0])
#define c2_Mc60AData09_c                     (Mc60AData09._c[1])
#define c3_Mc60AData09_c                     (Mc60AData09._c[2])
#define c4_Mc60AData09_c                     (Mc60AData09._c[3])
#define c5_Mc60AData09_c                     (Mc60AData09._c[4])
#define c6_Mc60AData09_c                     (Mc60AData09._c[5])
#define c7_Mc60AData09_c                     (Mc60AData09._c[6])
#define c8_Mc60AData09_c                     (Mc60AData09._c[7])

/* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */
#define c1_Mc60AData08_c                     (Mc60AData08._c[0])
#define c2_Mc60AData08_c                     (Mc60AData08._c[1])
#define c3_Mc60AData08_c                     (Mc60AData08._c[2])
#define c4_Mc60AData08_c                     (Mc60AData08._c[3])
#define c5_Mc60AData08_c                     (Mc60AData08._c[4])
#define c6_Mc60AData08_c                     (Mc60AData08._c[5])
#define c7_Mc60AData08_c                     (Mc60AData08._c[6])
#define c8_Mc60AData08_c                     (Mc60AData08._c[7])

/* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */
#define c1_Mc60AData07_c                     (Mc60AData07._c[0])
#define c2_Mc60AData07_c                     (Mc60AData07._c[1])
#define c3_Mc60AData07_c                     (Mc60AData07._c[2])
#define c4_Mc60AData07_c                     (Mc60AData07._c[3])
#define c5_Mc60AData07_c                     (Mc60AData07._c[4])
#define c6_Mc60AData07_c                     (Mc60AData07._c[5])
#define c7_Mc60AData07_c                     (Mc60AData07._c[6])
#define c8_Mc60AData07_c                     (Mc60AData07._c[7])

/* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */
#define c1_Mc60AData06_c                     (Mc60AData06._c[0])
#define c2_Mc60AData06_c                     (Mc60AData06._c[1])
#define c3_Mc60AData06_c                     (Mc60AData06._c[2])
#define c4_Mc60AData06_c                     (Mc60AData06._c[3])
#define c5_Mc60AData06_c                     (Mc60AData06._c[4])
#define c6_Mc60AData06_c                     (Mc60AData06._c[5])
#define c7_Mc60AData06_c                     (Mc60AData06._c[6])
#define c8_Mc60AData06_c                     (Mc60AData06._c[7])

/* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */
#define c1_Mc60AData05_c                     (Mc60AData05._c[0])
#define c2_Mc60AData05_c                     (Mc60AData05._c[1])
#define c3_Mc60AData05_c                     (Mc60AData05._c[2])
#define c4_Mc60AData05_c                     (Mc60AData05._c[3])
#define c5_Mc60AData05_c                     (Mc60AData05._c[4])
#define c6_Mc60AData05_c                     (Mc60AData05._c[5])
#define c7_Mc60AData05_c                     (Mc60AData05._c[6])
#define c8_Mc60AData05_c                     (Mc60AData05._c[7])

/* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */
#define c1_Mc60AData04_c                     (Mc60AData04._c[0])
#define c2_Mc60AData04_c                     (Mc60AData04._c[1])
#define c3_Mc60AData04_c                     (Mc60AData04._c[2])
#define c4_Mc60AData04_c                     (Mc60AData04._c[3])
#define c5_Mc60AData04_c                     (Mc60AData04._c[4])
#define c6_Mc60AData04_c                     (Mc60AData04._c[5])
#define c7_Mc60AData04_c                     (Mc60AData04._c[6])
#define c8_Mc60AData04_c                     (Mc60AData04._c[7])

/* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */
#define c1_Mc60AData03_c                     (Mc60AData03._c[0])
#define c2_Mc60AData03_c                     (Mc60AData03._c[1])
#define c3_Mc60AData03_c                     (Mc60AData03._c[2])
#define c4_Mc60AData03_c                     (Mc60AData03._c[3])
#define c5_Mc60AData03_c                     (Mc60AData03._c[4])
#define c6_Mc60AData03_c                     (Mc60AData03._c[5])
#define c7_Mc60AData03_c                     (Mc60AData03._c[6])
#define c8_Mc60AData03_c                     (Mc60AData03._c[7])

/* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */
#define c1_Mc60AData02_c                     (Mc60AData02._c[0])
#define c2_Mc60AData02_c                     (Mc60AData02._c[1])
#define c3_Mc60AData02_c                     (Mc60AData02._c[2])
#define c4_Mc60AData02_c                     (Mc60AData02._c[3])
#define c5_Mc60AData02_c                     (Mc60AData02._c[4])
#define c6_Mc60AData02_c                     (Mc60AData02._c[5])
#define c7_Mc60AData02_c                     (Mc60AData02._c[6])
#define c8_Mc60AData02_c                     (Mc60AData02._c[7])

/* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */
#define c1_Mc60AData01_c                     (Mc60AData01._c[0])
#define c2_Mc60AData01_c                     (Mc60AData01._c[1])
#define c3_Mc60AData01_c                     (Mc60AData01._c[2])
#define c4_Mc60AData01_c                     (Mc60AData01._c[3])
#define c5_Mc60AData01_c                     (Mc60AData01._c[4])
#define c6_Mc60AData01_c                     (Mc60AData01._c[5])
#define c7_Mc60AData01_c                     (Mc60AData01._c[6])
#define c8_Mc60AData01_c                     (Mc60AData01._c[7])

/* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */
#define c1_Mc60AData00_c                     (Mc60AData00._c[0])
#define c2_Mc60AData00_c                     (Mc60AData00._c[1])
#define c3_Mc60AData00_c                     (Mc60AData00._c[2])
#define c4_Mc60AData00_c                     (Mc60AData00._c[3])
#define c5_Mc60AData00_c                     (Mc60AData00._c[4])
#define c6_Mc60AData00_c                     (Mc60AData00._c[5])
#define c7_Mc60AData00_c                     (Mc60AData00._c[6])
#define c8_Mc60AData00_c                     (Mc60AData00._c[7])

/* ID: 0x00000092, Handle: 42, McInit [FC] */
#define c1_McInit_c                          (McInit._c[0])
#define c2_McInit_c                          (McInit._c[1])
#define c3_McInit_c                          (McInit._c[2])
#define c4_McInit_c                          (McInit._c[3])
#define c5_McInit_c                          (McInit._c[4])
#define c6_McInit_c                          (McInit._c[5])
#define c7_McInit_c                          (McInit._c[6])
#define c8_McInit_c                          (McInit._c[7])

/* ID: 0x00000201, Handle: 43, RxXCP [BC] */
#define c1_RxXCP_c                           (RxXCP._c[0])
#define c2_RxXCP_c                           (RxXCP._c[1])
#define c3_RxXCP_c                           (RxXCP._c[2])
#define c4_RxXCP_c                           (RxXCP._c[3])
#define c5_RxXCP_c                           (RxXCP._c[4])
#define c6_RxXCP_c                           (RxXCP._c[5])
#define c7_RxXCP_c                           (RxXCP._c[6])
#define c8_RxXCP_c                           (RxXCP._c[7])



/* -----------------------------------------------------------------------------
    &&&~ Access to data bytes of Tx messages
 ----------------------------------------------------------------------------- */

/* ID: 0x000007e4, Handle: 0, BcuTime [BC] */
#define c1_BcuTime_c                         (BcuTime._c[0])
#define c2_BcuTime_c                         (BcuTime._c[1])
#define c3_BcuTime_c                         (BcuTime._c[2])
#define c4_BcuTime_c                         (BcuTime._c[3])
#define c5_BcuTime_c                         (BcuTime._c[4])
#define c6_BcuTime_c                         (BcuTime._c[5])
#define c7_BcuTime_c                         (BcuTime._c[6])
#define c8_BcuTime_c                         (BcuTime._c[7])

/* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */
#define c1_BmsToVcu_E_c                      (BmsToVcu_E._c[0])
#define c2_BmsToVcu_E_c                      (BmsToVcu_E._c[1])
#define c3_BmsToVcu_E_c                      (BmsToVcu_E._c[2])
#define c4_BmsToVcu_E_c                      (BmsToVcu_E._c[3])
#define c5_BmsToVcu_E_c                      (BmsToVcu_E._c[4])
#define c6_BmsToVcu_E_c                      (BmsToVcu_E._c[5])
#define c7_BmsToVcu_E_c                      (BmsToVcu_E._c[6])
#define c8_BmsToVcu_E_c                      (BmsToVcu_E._c[7])

/* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */
#define c1_BmsToVcu_D_c                      (BmsToVcu_D._c[0])
#define c2_BmsToVcu_D_c                      (BmsToVcu_D._c[1])
#define c3_BmsToVcu_D_c                      (BmsToVcu_D._c[2])
#define c4_BmsToVcu_D_c                      (BmsToVcu_D._c[3])
#define c5_BmsToVcu_D_c                      (BmsToVcu_D._c[4])
#define c6_BmsToVcu_D_c                      (BmsToVcu_D._c[5])
#define c7_BmsToVcu_D_c                      (BmsToVcu_D._c[6])
#define c8_BmsToVcu_D_c                      (BmsToVcu_D._c[7])

/* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */
#define c1_Bcu_CarCharA_c                    (Bcu_CarCharA._c[0])
#define c2_Bcu_CarCharA_c                    (Bcu_CarCharA._c[1])
#define c3_Bcu_CarCharA_c                    (Bcu_CarCharA._c[2])
#define c4_Bcu_CarCharA_c                    (Bcu_CarCharA._c[3])
#define c5_Bcu_CarCharA_c                    (Bcu_CarCharA._c[4])
#define c6_Bcu_CarCharA_c                    (Bcu_CarCharA._c[5])
#define c7_Bcu_CarCharA_c                    (Bcu_CarCharA._c[6])
#define c8_Bcu_CarCharA_c                    (Bcu_CarCharA._c[7])

/* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */
#define c1_BmsToVcu_C_c                      (BmsToVcu_C._c[0])
#define c2_BmsToVcu_C_c                      (BmsToVcu_C._c[1])
#define c3_BmsToVcu_C_c                      (BmsToVcu_C._c[2])
#define c4_BmsToVcu_C_c                      (BmsToVcu_C._c[3])
#define c5_BmsToVcu_C_c                      (BmsToVcu_C._c[4])
#define c6_BmsToVcu_C_c                      (BmsToVcu_C._c[5])
#define c7_BmsToVcu_C_c                      (BmsToVcu_C._c[6])
#define c8_BmsToVcu_C_c                      (BmsToVcu_C._c[7])

/* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */
#define c1_BmsTxVcu_B_c                      (BmsTxVcu_B._c[0])
#define c2_BmsTxVcu_B_c                      (BmsTxVcu_B._c[1])
#define c3_BmsTxVcu_B_c                      (BmsTxVcu_B._c[2])
#define c4_BmsTxVcu_B_c                      (BmsTxVcu_B._c[3])
#define c5_BmsTxVcu_B_c                      (BmsTxVcu_B._c[4])
#define c6_BmsTxVcu_B_c                      (BmsTxVcu_B._c[5])
#define c7_BmsTxVcu_B_c                      (BmsTxVcu_B._c[6])
#define c8_BmsTxVcu_B_c                      (BmsTxVcu_B._c[7])

/* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */
#define c1_BcuToVcu_A_c                      (BcuToVcu_A._c[0])
#define c2_BcuToVcu_A_c                      (BcuToVcu_A._c[1])
#define c3_BcuToVcu_A_c                      (BcuToVcu_A._c[2])
#define c4_BcuToVcu_A_c                      (BcuToVcu_A._c[3])
#define c5_BcuToVcu_A_c                      (BcuToVcu_A._c[4])
#define c6_BcuToVcu_A_c                      (BcuToVcu_A._c[5])
#define c7_BcuToVcu_A_c                      (BcuToVcu_A._c[6])
#define c8_BcuToVcu_A_c                      (BcuToVcu_A._c[7])

/* ID: 0x000007e8, Handle: 7, UdsTx [FC] */
#define c1_UdsTx_c                           (UdsTx._c[0])
#define c2_UdsTx_c                           (UdsTx._c[1])
#define c3_UdsTx_c                           (UdsTx._c[2])
#define c4_UdsTx_c                           (UdsTx._c[3])
#define c5_UdsTx_c                           (UdsTx._c[4])
#define c6_UdsTx_c                           (UdsTx._c[5])
#define c7_UdsTx_c                           (UdsTx._c[6])
#define c8_UdsTx_c                           (UdsTx._c[7])

/* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */
#define c1_BcuSD6_c                          (BcuSD6._c[0])
#define c2_BcuSD6_c                          (BcuSD6._c[1])
#define c3_BcuSD6_c                          (BcuSD6._c[2])
#define c4_BcuSD6_c                          (BcuSD6._c[3])
#define c5_BcuSD6_c                          (BcuSD6._c[4])
#define c6_BcuSD6_c                          (BcuSD6._c[5])
#define c7_BcuSD6_c                          (BcuSD6._c[6])
#define c8_BcuSD6_c                          (BcuSD6._c[7])

/* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */
#define c1_BcuSD5_c                          (BcuSD5._c[0])
#define c2_BcuSD5_c                          (BcuSD5._c[1])
#define c3_BcuSD5_c                          (BcuSD5._c[2])
#define c4_BcuSD5_c                          (BcuSD5._c[3])
#define c5_BcuSD5_c                          (BcuSD5._c[4])
#define c6_BcuSD5_c                          (BcuSD5._c[5])
#define c7_BcuSD5_c                          (BcuSD5._c[6])
#define c8_BcuSD5_c                          (BcuSD5._c[7])

/* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */
#define c1_BcuSD4_c                          (BcuSD4._c[0])
#define c2_BcuSD4_c                          (BcuSD4._c[1])
#define c3_BcuSD4_c                          (BcuSD4._c[2])
#define c4_BcuSD4_c                          (BcuSD4._c[3])
#define c5_BcuSD4_c                          (BcuSD4._c[4])
#define c6_BcuSD4_c                          (BcuSD4._c[5])
#define c7_BcuSD4_c                          (BcuSD4._c[6])
#define c8_BcuSD4_c                          (BcuSD4._c[7])

/* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */
#define c1_BcuSD3_c                          (BcuSD3._c[0])
#define c2_BcuSD3_c                          (BcuSD3._c[1])
#define c3_BcuSD3_c                          (BcuSD3._c[2])
#define c4_BcuSD3_c                          (BcuSD3._c[3])
#define c5_BcuSD3_c                          (BcuSD3._c[4])
#define c6_BcuSD3_c                          (BcuSD3._c[5])
#define c7_BcuSD3_c                          (BcuSD3._c[6])
#define c8_BcuSD3_c                          (BcuSD3._c[7])

/* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */
#define c1_BcuSD2_c                          (BcuSD2._c[0])
#define c2_BcuSD2_c                          (BcuSD2._c[1])
#define c3_BcuSD2_c                          (BcuSD2._c[2])
#define c4_BcuSD2_c                          (BcuSD2._c[3])
#define c5_BcuSD2_c                          (BcuSD2._c[4])
#define c6_BcuSD2_c                          (BcuSD2._c[5])
#define c7_BcuSD2_c                          (BcuSD2._c[6])
#define c8_BcuSD2_c                          (BcuSD2._c[7])

/* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */
#define c1_BcuSD1_c                          (BcuSD1._c[0])
#define c2_BcuSD1_c                          (BcuSD1._c[1])
#define c3_BcuSD1_c                          (BcuSD1._c[2])
#define c4_BcuSD1_c                          (BcuSD1._c[3])
#define c5_BcuSD1_c                          (BcuSD1._c[4])
#define c6_BcuSD1_c                          (BcuSD1._c[5])
#define c7_BcuSD1_c                          (BcuSD1._c[6])
#define c8_BcuSD1_c                          (BcuSD1._c[7])

/* ID: 0x00000200, Handle: 14, TxXCP [FC] */
#define c1_TxXCP_c                           (TxXCP._c[0])
#define c2_TxXCP_c                           (TxXCP._c[1])
#define c3_TxXCP_c                           (TxXCP._c[2])
#define c4_TxXCP_c                           (TxXCP._c[3])
#define c5_TxXCP_c                           (TxXCP._c[4])
#define c6_TxXCP_c                           (TxXCP._c[5])
#define c7_TxXCP_c                           (TxXCP._c[6])
#define c8_TxXCP_c                           (TxXCP._c[7])

/* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */
#define c1_BcuCHAInfo2_c                     (BcuCHAInfo2._c[0])
#define c2_BcuCHAInfo2_c                     (BcuCHAInfo2._c[1])
#define c3_BcuCHAInfo2_c                     (BcuCHAInfo2._c[2])
#define c4_BcuCHAInfo2_c                     (BcuCHAInfo2._c[3])
#define c5_BcuCHAInfo2_c                     (BcuCHAInfo2._c[4])
#define c6_BcuCHAInfo2_c                     (BcuCHAInfo2._c[5])
#define c7_BcuCHAInfo2_c                     (BcuCHAInfo2._c[6])
#define c8_BcuCHAInfo2_c                     (BcuCHAInfo2._c[7])

/* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */
#define c1_BcuCHAInfo1_c                     (BcuCHAInfo1._c[0])
#define c2_BcuCHAInfo1_c                     (BcuCHAInfo1._c[1])
#define c3_BcuCHAInfo1_c                     (BcuCHAInfo1._c[2])
#define c4_BcuCHAInfo1_c                     (BcuCHAInfo1._c[3])
#define c5_BcuCHAInfo1_c                     (BcuCHAInfo1._c[4])
#define c6_BcuCHAInfo1_c                     (BcuCHAInfo1._c[5])
#define c7_BcuCHAInfo1_c                     (BcuCHAInfo1._c[6])
#define c8_BcuCHAInfo1_c                     (BcuCHAInfo1._c[7])

/* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */
#define c1_UdsInterRx_c                      (UdsInterRx._c[0])
#define c2_UdsInterRx_c                      (UdsInterRx._c[1])
#define c3_UdsInterRx_c                      (UdsInterRx._c[2])
#define c4_UdsInterRx_c                      (UdsInterRx._c[3])
#define c5_UdsInterRx_c                      (UdsInterRx._c[4])
#define c6_UdsInterRx_c                      (UdsInterRx._c[5])
#define c7_UdsInterRx_c                      (UdsInterRx._c[6])
#define c8_UdsInterRx_c                      (UdsInterRx._c[7])

/* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */
#define c1_BcuBalCmdMc60A_1_c                (BcuBalCmdMc60A_1._c[0])
#define c2_BcuBalCmdMc60A_1_c                (BcuBalCmdMc60A_1._c[1])
#define c3_BcuBalCmdMc60A_1_c                (BcuBalCmdMc60A_1._c[2])
#define c4_BcuBalCmdMc60A_1_c                (BcuBalCmdMc60A_1._c[3])
#define c5_BcuBalCmdMc60A_1_c                (BcuBalCmdMc60A_1._c[4])
#define c6_BcuBalCmdMc60A_1_c                (BcuBalCmdMc60A_1._c[5])
#define c7_BcuBalCmdMc60A_1_c                (BcuBalCmdMc60A_1._c[6])
#define c8_BcuBalCmdMc60A_1_c                (BcuBalCmdMc60A_1._c[7])

/* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */
#define c1_RtcRxMulData_c                    (RtcRxMulData._c[0])
#define c2_RtcRxMulData_c                    (RtcRxMulData._c[1])
#define c3_RtcRxMulData_c                    (RtcRxMulData._c[2])
#define c4_RtcRxMulData_c                    (RtcRxMulData._c[3])
#define c5_RtcRxMulData_c                    (RtcRxMulData._c[4])
#define c6_RtcRxMulData_c                    (RtcRxMulData._c[5])
#define c7_RtcRxMulData_c                    (RtcRxMulData._c[6])
#define c8_RtcRxMulData_c                    (RtcRxMulData._c[7])

/* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */
#define c1_RtcRxMulReq_c                     (RtcRxMulReq._c[0])
#define c2_RtcRxMulReq_c                     (RtcRxMulReq._c[1])
#define c3_RtcRxMulReq_c                     (RtcRxMulReq._c[2])
#define c4_RtcRxMulReq_c                     (RtcRxMulReq._c[3])
#define c5_RtcRxMulReq_c                     (RtcRxMulReq._c[4])
#define c6_RtcRxMulReq_c                     (RtcRxMulReq._c[5])
#define c7_RtcRxMulReq_c                     (RtcRxMulReq._c[6])
#define c8_RtcRxMulReq_c                     (RtcRxMulReq._c[7])

/* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */
#define c1_RtcRxMsg_c                        (RtcRxMsg._c[0])
#define c2_RtcRxMsg_c                        (RtcRxMsg._c[1])
#define c3_RtcRxMsg_c                        (RtcRxMsg._c[2])
#define c4_RtcRxMsg_c                        (RtcRxMsg._c[3])
#define c5_RtcRxMsg_c                        (RtcRxMsg._c[4])
#define c6_RtcRxMsg_c                        (RtcRxMsg._c[5])
#define c7_RtcRxMsg_c                        (RtcRxMsg._c[6])
#define c8_RtcRxMsg_c                        (RtcRxMsg._c[7])

/* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */
#define c1_BcuBalCmdMc33B_0_c                (BcuBalCmdMc33B_0._c[0])
#define c2_BcuBalCmdMc33B_0_c                (BcuBalCmdMc33B_0._c[1])
#define c3_BcuBalCmdMc33B_0_c                (BcuBalCmdMc33B_0._c[2])
#define c4_BcuBalCmdMc33B_0_c                (BcuBalCmdMc33B_0._c[3])
#define c5_BcuBalCmdMc33B_0_c                (BcuBalCmdMc33B_0._c[4])
#define c6_BcuBalCmdMc33B_0_c                (BcuBalCmdMc33B_0._c[5])
#define c7_BcuBalCmdMc33B_0_c                (BcuBalCmdMc33B_0._c[6])
#define c8_BcuBalCmdMc33B_0_c                (BcuBalCmdMc33B_0._c[7])

/* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */
#define c1_BcuBalCmdMc60A_0_c                (BcuBalCmdMc60A_0._c[0])
#define c2_BcuBalCmdMc60A_0_c                (BcuBalCmdMc60A_0._c[1])
#define c3_BcuBalCmdMc60A_0_c                (BcuBalCmdMc60A_0._c[2])
#define c4_BcuBalCmdMc60A_0_c                (BcuBalCmdMc60A_0._c[3])
#define c5_BcuBalCmdMc60A_0_c                (BcuBalCmdMc60A_0._c[4])
#define c6_BcuBalCmdMc60A_0_c                (BcuBalCmdMc60A_0._c[5])
#define c7_BcuBalCmdMc60A_0_c                (BcuBalCmdMc60A_0._c[6])
#define c8_BcuBalCmdMc60A_0_c                (BcuBalCmdMc60A_0._c[7])

/* ID: 0x00000090, Handle: 24, BcuInit [FC] */
#define c1_BcuInit_c                         (BcuInit._c[0])
#define c2_BcuInit_c                         (BcuInit._c[1])
#define c3_BcuInit_c                         (BcuInit._c[2])
#define c4_BcuInit_c                         (BcuInit._c[3])
#define c5_BcuInit_c                         (BcuInit._c[4])
#define c6_BcuInit_c                         (BcuInit._c[5])
#define c7_BcuInit_c                         (BcuInit._c[6])
#define c8_BcuInit_c                         (BcuInit._c[7])

/* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
#define c1_BcuSyc100msMsg_c                  (BcuSyc100msMsg._c[0])
#define c2_BcuSyc100msMsg_c                  (BcuSyc100msMsg._c[1])
#define c3_BcuSyc100msMsg_c                  (BcuSyc100msMsg._c[2])
#define c4_BcuSyc100msMsg_c                  (BcuSyc100msMsg._c[3])
#define c5_BcuSyc100msMsg_c                  (BcuSyc100msMsg._c[4])
#define c6_BcuSyc100msMsg_c                  (BcuSyc100msMsg._c[5])
#define c7_BcuSyc100msMsg_c                  (BcuSyc100msMsg._c[6])
#define c8_BcuSyc100msMsg_c                  (BcuSyc100msMsg._c[7])



/* -----------------------------------------------------------------------------
    &&&~ RDS Access
 ----------------------------------------------------------------------------- */

#define b_CAN_XCP_TxData_0_b                 (RDS0.TxXCP.XCP_TxData_0)
#define b_CAN_XCP_TxData_1_b                 (RDS0.TxXCP.XCP_TxData_1)
#define b_CAN_XCP_TxData_2_b                 (RDS0.TxXCP.XCP_TxData_2)
#define b_CAN_XCP_TxData_3_b                 (RDS0.TxXCP.XCP_TxData_3)
#define b_CAN_XCP_TxData_4_b                 (RDS0.TxXCP.XCP_TxData_4)
#define b_CAN_XCP_TxData_5_b                 (RDS0.TxXCP.XCP_TxData_5)
#define b_CAN_XCP_TxData_6_b                 (RDS0.TxXCP.XCP_TxData_6)
#define b_CAN_XCP_TxData_7_b                 (RDS0.TxXCP.XCP_TxData_7)

typedef struct _c_TxXCP_RDS_msgTypeTag
{
  vbittype XCP_TxData_0 : 8;
  vbittype XCP_TxData_1 : 8;
  vbittype XCP_TxData_2 : 8;
  vbittype XCP_TxData_3 : 8;
  vbittype XCP_TxData_4 : 8;
  vbittype XCP_TxData_5 : 8;
  vbittype XCP_TxData_6 : 8;
  vbittype XCP_TxData_7 : 8;
} _c_TxXCP_RDS_msgType;

typedef struct _c_BcuSD1_RDS_msgTypeTag
{
  vbittype BcuSt : 4;
  vbittype MccSt : 4;
  vbittype BalSt : 4;
  vbittype ThmSt : 4;
  vbittype SocCalcSt : 4;
  vbittype BatSt : 4;
  vbittype ChaRSt : 5;
  vbittype BmsErrLvl : 3;
  vbittype DTCCodeOutput : 8;
  vbittype CtctrStPos : 1;
  vbittype CtctrStNeg : 1;
  vbittype CtctrStPrec : 1;
  vbittype PtcConSt : 1;
  vbittype AirconConSt : 1;
  vbittype DCDCSt : 1;
  vbittype SetChaCtl : 1;
  vbittype StChaGun : 1;
  vbittype LowFanSt : 1;
  vbittype HighFanSt : 1;
  vbittype HeatSt : 1;
  vbittype WkSigCC_1 : 1;
  vbittype WkSigCC2_1 : 1;
  vbittype unused0 : 3;
  vbittype UWkKeyOn : 4;
  vbittype UWkCarCha : 4;
} _c_BcuSD1_RDS_msgType;

typedef struct _c_BcuSD2_RDS_msgTypeTag
{
  vbittype Uact1_0 : 8;
  vbittype Uact1_1 : 8;
  vbittype UcellSum : 8;
  vbittype Uact2 : 8;
  vbittype SocPack : 8;
  vbittype Soh : 8;
  vbittype BatMaxCp : 8;
  vbittype CarChaICP : 8;
} _c_BcuSD2_RDS_msgType;

typedef struct _c_BcuSD3_RDS_msgTypeTag
{
  vbittype UcellMax_0 : 8;
  vbittype UcellMax_1 : 8;
  vbittype UcellMin_0 : 8;
  vbittype UcellMin_1 : 8;
  vbittype TempMax : 8;
  vbittype TempMin : 8;
  vbittype Ipack_0_0 : 8;
  vbittype Ipack_0_1 : 8;
} _c_BcuSD3_RDS_msgType;

typedef struct _c_BcuSD4_RDS_msgTypeTag
{
  vbittype WarnUCellMax : 1;
  vbittype ErrUCellMax : 1;
  vbittype WarnUCellMin : 1;
  vbittype ErrUCellMin : 1;
  vbittype WarnTempMax : 1;
  vbittype ErrTempMax : 1;
  vbittype WarnTempMin : 1;
  vbittype ErrTempMin : 1;
  vbittype WarnUPackMax : 1;
  vbittype ErrUPackMax : 1;
  vbittype WarnUPackMin : 1;
  vbittype ErrUPackMin : 1;
  vbittype WarnIso : 1;
  vbittype ErrIso : 1;
  vbittype WarnIActDcha : 1;
  vbittype ErrIActDcha : 1;
  vbittype WarnIActCha : 1;
  vbittype ErrIActCha : 1;
  vbittype WarnUCellDiff : 1;
  vbittype ErrUCellDiff : 1;
  vbittype WarnTempDiff : 1;
  vbittype ErrTempDiff : 1;
  vbittype ErrUCellLow : 1;
  vbittype ErrUPackInter : 1;
  vbittype WarnIActChaBack : 1;
  vbittype ErrIActChaBack : 1;
  vbittype WarnIActChaCar : 1;
  vbittype ErrIActChaCar : 1;
  vbittype WarnIActChaBGBC : 1;
  vbittype ErrIActChaBGBC : 1;
  vbittype TempSnsrErr : 1;
  vbittype unused0 : 1;
  vbittype WkSig : 1;
  vbittype WkSigCha : 1;
  vbittype WkCarCha : 1;
  vbittype WkSigCC : 1;
  vbittype WkSigCC2 : 1;
  vbittype WkKeyStart : 1;
  vbittype unused1 : 2;
  vbittype ErrPrecDurMax : 1;
  vbittype ErrCnctDurMax : 1;
  vbittype ErrSoffDurMax : 1;
  vbittype ErrDcnctDurMax : 1;
  vbittype LoaErrFlag : 1;
  vbittype unused2 : 3;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
} _c_BcuSD4_RDS_msgType;

typedef struct _c_BcuSD5_RDS_msgTypeTag
{
  vbittype UcellMaxIndex : 8;
  vbittype UcellMinIndex : 8;
  vbittype TempMaxIndex : 8;
  vbittype TempMinIndex : 8;
  vbittype TiBatOff : 8;
  vbittype IChLim : 8;
  vbittype IDchaLim : 8;
  vbittype EEPROM_SOC : 8;
} _c_BcuSD5_RDS_msgType;

typedef struct _c_BcuSD6_RDS_msgTypeTag
{
  vbittype Cc2Vol_1 : 8;
  vbittype CcVol_1 : 8;
  vbittype DchaAH_0 : 8;
  vbittype DchaAH_1 : 8;
  vbittype ChaAh_0 : 8;
  vbittype ChaAh_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
} _c_BcuSD6_RDS_msgType;

typedef struct _c_UdsTx_RDS_msgTypeTag
{
  vbittype UdsTx_Cmd : 8;
  vbittype UdsTx_D1 : 8;
  vbittype UdsTx_D2 : 8;
  vbittype UdsTx_D3 : 8;
  vbittype UdsTx_D4 : 8;
  vbittype UdsTx_D5 : 8;
  vbittype UdsTx_D6 : 8;
  vbittype UdsTx_D7 : 8;
} _c_UdsTx_RDS_msgType;

typedef struct _c_BcuTime_RDS_msgTypeTag
{
  vbittype tSecond : 8;
  vbittype tMinute : 8;
  vbittype tHour : 8;
  vbittype tDay : 8;
  vbittype tWeek : 8;
  vbittype tMonth : 8;
  vbittype tYear : 8;
  vbittype unused0 : 8;
} _c_BcuTime_RDS_msgType;

typedef struct _c_Bcu_CarCharA_RDS_msgTypeTag
{
  vbittype ReqUCarCha_1 : 8;
  vbittype ReqUCarCha_0 : 8;
  vbittype ReqICarCha_1 : 8;
  vbittype ReqICarCha_0 : 8;
  vbittype ChargerSt : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
} _c_Bcu_CarCharA_RDS_msgType;

typedef struct _c_BmsToVcu_E_RDS_msgTypeTag
{
  vbittype UcellMax1_0 : 8;
  vbittype UcellMax1_1 : 8;
  vbittype UcellMaxNo : 8;
  vbittype UcellMin1_0 : 8;
  vbittype UcellMin1_1 : 8;
  vbittype UcellMinNo : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
} _c_BmsToVcu_E_RDS_msgType;

typedef struct _c_BmsToVcu_D_RDS_msgTypeTag
{
  vbittype ChaConSt : 2;
  vbittype unused0 : 2;
  vbittype PosRlySt : 1;
  vbittype ChaRlySt : 1;
  vbittype NegRlySt : 1;
  vbittype PreRlySt : 1;
  vbittype HeatManageSt : 3;
  vbittype unused1 : 5;
  vbittype WorkSt : 3;
  vbittype unused2 : 5;
  vbittype ChaLeftTime_0 : 8;
  vbittype ChaLeftTime_1 : 8;
  vbittype BmsSoftNO : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
} _c_BmsToVcu_D_RDS_msgType;

typedef struct _c_BmsToVcu_C_RDS_msgTypeTag
{
  vbittype Upack1_0 : 8;
  vbittype Upack1_1 : 8;
  vbittype Ipack1_0 : 8;
  vbittype Ipack1_1 : 8;
  vbittype SOC1 : 8;
  vbittype TempMax1 : 8;
  vbittype TempMin1 : 8;
  vbittype AvgTemp : 8;
} _c_BmsToVcu_C_RDS_msgType;

typedef struct _c_BmsTxVcu_B_RDS_msgTypeTag
{
  vbittype IDchaLim1_0 : 8;
  vbittype IDchaLim1_1 : 8;
  vbittype IChaLim_0 : 8;
  vbittype IChaLim_1 : 8;
  vbittype GBChaTimes_0 : 8;
  vbittype GBChaTimes_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
} _c_BmsTxVcu_B_RDS_msgType;

typedef struct _c_BcuToVcu_A_RDS_msgTypeTag
{
  vbittype RptIChaMax : 1;
  vbittype RptIDchaMax : 1;
  vbittype RptUPackMax : 1;
  vbittype RptUPackMin : 1;
  vbittype RptIso : 1;
  vbittype RptSOCMin : 1;
  vbittype RptUcellMin : 1;
  vbittype RptUcellMax : 1;
  vbittype WarnTempMin1 : 1;
  vbittype RptTempMax : 1;
  vbittype ErrCellBal : 1;
  vbittype ErrRepairsSwitch : 1;
  vbittype ErrTempSensor : 1;
  vbittype ErrLEM : 1;
  vbittype ErrUSensor : 1;
  vbittype unused0 : 1;
  vbittype WarnIChaMax : 1;
  vbittype WarnIDchaMax : 1;
  vbittype WarnUPackMax1 : 1;
  vbittype WarnUPackMin1 : 1;
  vbittype WarnIso1 : 1;
  vbittype WarnSOCMin : 1;
  vbittype WarnUcellMin1 : 1;
  vbittype WarnUcellMax1 : 1;
  vbittype ErrTempMin1 : 1;
  vbittype WarnTempMax1 : 1;
  vbittype unused1 : 6;
  vbittype ErrIChaMax : 1;
  vbittype ErrIDchaMax : 1;
  vbittype ErrUPackMax1 : 1;
  vbittype ErrUPackMin1 : 1;
  vbittype unused2 : 1;
  vbittype ErrSOCMin : 1;
  vbittype ErrUcellMin : 1;
  vbittype ErrUcellMax : 1;
  vbittype ErrTempMax1 : 1;
  vbittype ErrCharge : 1;
  vbittype ErrIso1 : 1;
  vbittype ErrPosNegRly : 1;
  vbittype ErrPreRly : 1;
  vbittype ErrInterCom : 1;
  vbittype unused3 : 2;
  vbittype RptFaultTotal : 4;
  vbittype WarnFaultTotal : 4;
  vbittype ErrFaultTotal : 4;
  vbittype unused4 : 4;
} _c_BcuToVcu_A_RDS_msgType;

typedef struct _c_UdsRx_RDS_msgTypeTag
{
  vbittype UdsRx_Cmd : 8;
  vbittype UdsRx_D1 : 8;
  vbittype UdsRx_D2 : 8;
  vbittype UdsRx_D3 : 8;
  vbittype UdsRx_D4 : 8;
  vbittype UdsRx_D5 : 8;
  vbittype UdsRx_D6 : 8;
  vbittype UdsRx_D7 : 8;
} _c_UdsRx_RDS_msgType;

#define b_CAN_XCP_RxData_0_b                 (RDSBasic1_0.RxXCP.XCP_RxData_0)
#define b_CAN_XCP_RxData_1_b                 (RDSBasic1_0.RxXCP.XCP_RxData_1)
#define b_CAN_XCP_RxData_2_b                 (RDSBasic1_0.RxXCP.XCP_RxData_2)
#define b_CAN_XCP_RxData_3_b                 (RDSBasic1_0.RxXCP.XCP_RxData_3)
#define b_CAN_XCP_RxData_4_b                 (RDSBasic1_0.RxXCP.XCP_RxData_4)
#define b_CAN_XCP_RxData_5_b                 (RDSBasic1_0.RxXCP.XCP_RxData_5)
#define b_CAN_XCP_RxData_6_b                 (RDSBasic1_0.RxXCP.XCP_RxData_6)
#define b_CAN_XCP_RxData_7_b                 (RDSBasic1_0.RxXCP.XCP_RxData_7)

typedef struct _c_RxXCP_RDS_msgTypeTag
{
  vbittype XCP_RxData_0 : 8;
  vbittype XCP_RxData_1 : 8;
  vbittype XCP_RxData_2 : 8;
  vbittype XCP_RxData_3 : 8;
  vbittype XCP_RxData_4 : 8;
  vbittype XCP_RxData_5 : 8;
  vbittype XCP_RxData_6 : 8;
  vbittype XCP_RxData_7 : 8;
} _c_RxXCP_RDS_msgType;

typedef struct _c_Bcu_CarCharB_RDS_msgTypeTag
{
  vbittype ChargerU_1 : 8;
  vbittype ChargerU_0 : 8;
  vbittype ChargerI_1 : 8;
  vbittype ChargerI_0 : 8;
  vbittype ErrChaCon : 1;
  vbittype ErrChrTemp : 1;
  vbittype ErrChrU : 1;
  vbittype ChrInitSt : 1;
  vbittype ChrWorkSt : 1;
  vbittype ErrChrCommunicate : 1;
  vbittype unused0 : 2;
} _c_Bcu_CarCharB_RDS_msgType;

typedef struct _c_VcuToBms_RDS_msgTypeTag
{
  vbittype StartEn : 1;
  vbittype unused0 : 7;
} _c_VcuToBms_RDS_msgType;

typedef union _c_RDS0_bufTag
{
  vuint8 _c[8];
  _c_TxXCP_RDS_msgType TxXCP;
} _c_RDS0_buf;
typedef union _c_RDS1_bufTag
{
  vuint8 _c[8];
  _c_BcuSD1_RDS_msgType BcuSD1;
} _c_RDS1_buf;
typedef union _c_RDS2_bufTag
{
  vuint8 _c[8];
  _c_BcuSD2_RDS_msgType BcuSD2;
} _c_RDS2_buf;
typedef union _c_RDS3_bufTag
{
  vuint8 _c[8];
  _c_BcuSD3_RDS_msgType BcuSD3;
} _c_RDS3_buf;
typedef union _c_RDS4_bufTag
{
  vuint8 _c[8];
  _c_BcuSD4_RDS_msgType BcuSD4;
} _c_RDS4_buf;
typedef union _c_RDS5_bufTag
{
  vuint8 _c[8];
  _c_BcuSD5_RDS_msgType BcuSD5;
} _c_RDS5_buf;
typedef union _c_RDS6_bufTag
{
  vuint8 _c[8];
  _c_BcuSD6_RDS_msgType BcuSD6;
} _c_RDS6_buf;
typedef union _c_RDS7_bufTag
{
  vuint8 _c[8];
  _c_UdsTx_RDS_msgType UdsTx;
} _c_RDS7_buf;
typedef union _c_RDS_Tx_buf_0Tag
{
  vuint8 _c[8];
  _c_BcuTime_RDS_msgType BcuTime;
  _c_Bcu_CarCharA_RDS_msgType Bcu_CarCharA;
  _c_BmsToVcu_E_RDS_msgType BmsToVcu_E;
  _c_BmsToVcu_D_RDS_msgType BmsToVcu_D;
  _c_BmsToVcu_C_RDS_msgType BmsToVcu_C;
  _c_BmsTxVcu_B_RDS_msgType BmsTxVcu_B;
  _c_BcuToVcu_A_RDS_msgType BcuToVcu_A;
} _c_RDS_Tx_buf_0;
typedef union _c_RDS25_bufTag
{
  vuint8 _c[8];
  _c_UdsRx_RDS_msgType UdsRx;
} _c_RDS25_buf;
typedef union _c_RDSBasic1_buf_0Tag
{
  vuint8 _c[8];
  _c_RxXCP_RDS_msgType RxXCP;
} _c_RDSBasic1_buf_0;
typedef union _c_RDSBasic2_buf_0Tag
{
  vuint8 _c[8];
  _c_Bcu_CarCharB_RDS_msgType Bcu_CarCharB;
  _c_VcuToBms_RDS_msgType VcuToBms;
} _c_RDSBasic2_buf_0;


#define RDS0                                 ((* ((_c_RDS0_buf MEMORY_CAN *)(canRDSTxPtr[0]))))
#define RDS1                                 ((* ((_c_RDS1_buf MEMORY_CAN *)(canRDSTxPtr[1]))))
#define RDS2                                 ((* ((_c_RDS2_buf MEMORY_CAN *)(canRDSTxPtr[2]))))
#define RDS3                                 ((* ((_c_RDS3_buf MEMORY_CAN *)(canRDSTxPtr[3]))))
#define RDS4                                 ((* ((_c_RDS4_buf MEMORY_CAN *)(canRDSTxPtr[4]))))
#define RDS5                                 ((* ((_c_RDS5_buf MEMORY_CAN *)(canRDSTxPtr[5]))))
#define RDS6                                 ((* ((_c_RDS6_buf MEMORY_CAN *)(canRDSTxPtr[6]))))
#define RDS7                                 ((* ((_c_RDS7_buf MEMORY_CAN *)(canRDSTxPtr[7]))))
#define RDSTx_0                              ((* ((_c_RDS_Tx_buf_0 MEMORY_CAN *)(canRDSTxPtr[8]))))
#define RDS25                                ((* ((_c_RDS25_buf MEMORY_CAN *)(canRDSRxPtr[0]))))
#define RDSBasic1_0                          ((* ((_c_RDSBasic1_buf_0 MEMORY_CAN *)(canRDSRxPtr[0]))))
#define RDSBasic2_0                          ((* ((_c_RDSBasic2_buf_0 MEMORY_CAN *)(canRDSRxPtr[0]))))

typedef struct _c_BcuSyc100msMsg_RDS_msgTypeTag
{
  vbittype SycD0 : 8;
  vbittype SycD1 : 8;
  vbittype SycD2 : 8;
  vbittype SycD3 : 8;
  vbittype SycD4_0 : 8;
  vbittype SycD4_1 : 8;
  vbittype SycD4_2 : 8;
  vbittype SycD4_3 : 8;
} _c_BcuSyc100msMsg_RDS_msgType;

typedef struct _c_BcuInit_RDS_msgTypeTag
{
  vbittype BcuInit_Cmd : 8;
  vbittype BcuInit_McNo : 8;
  vbittype BcuInit_D1 : 8;
  vbittype BcuInit_D2 : 8;
  vbittype BcuInit_D3 : 8;
  vbittype BcuInit_D4 : 8;
  vbittype BcuInit_D5 : 8;
  vbittype BcuInit_D6 : 8;
} _c_BcuInit_RDS_msgType;

typedef struct _c_BcuBalCmdMc60A_0_RDS_msgTypeTag
{
  vbittype Mc60ACtrlLtc1_0 : 8;
  vbittype Mc60ACtrlLtc1_1 : 8;
  vbittype Mc60ACtrlLtc2_0 : 8;
  vbittype Mc60ACtrlLtc2_1 : 8;
  vbittype Mc60ACtrlLtc3_0 : 8;
  vbittype Mc60ACtrlLtc3_1 : 8;
  vbittype Mc60ACtrlLtc4_0 : 8;
  vbittype Mc60ACtrlLtc4_1 : 8;
} _c_BcuBalCmdMc60A_0_RDS_msgType;

typedef struct _c_BcuBalCmdMc33B_0_RDS_msgTypeTag
{
  vbittype Mc33BCtrlLtc1_0 : 8;
  vbittype Mc33BCtrlLtc1_1 : 8;
  vbittype Mc33BCtrlLtc2_0 : 8;
  vbittype Mc33BCtrlLtc2_1 : 8;
  vbittype Mc33BCtrlLtc3_0 : 8;
  vbittype Mc33BCtrlLtc3_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
} _c_BcuBalCmdMc33B_0_RDS_msgType;

typedef struct _c_RtcRxMsg_RDS_msgTypeTag
{
  vbittype RtcRxD0 : 8;
  vbittype RtcRxD1 : 8;
  vbittype RtcRxD2 : 8;
  vbittype RtcRxD3 : 8;
  vbittype RtcRxD4 : 8;
  vbittype RtcRxD5 : 8;
  vbittype RtcRxD6 : 8;
  vbittype RtcRxCmd : 8;
} _c_RtcRxMsg_RDS_msgType;

typedef struct _c_RtcRxMulReq_RDS_msgTypeTag
{
  vbittype RtcRxMulReqCmd : 8;
  vbittype RtcRxMulByteSum_0 : 8;
  vbittype RtcRxMulByteSum_1 : 8;
  vbittype RtcRxMulPackSum : 8;
  vbittype RtcTxMulReqD4Sig : 8;
  vbittype RtcRxMulReqPGN_0 : 8;
  vbittype RtcRxMulReqPGN_1 : 8;
  vbittype RtcRxMulReqPGN_2 : 8;
} _c_RtcRxMulReq_RDS_msgType;

typedef struct _c_RtcRxMulData_RDS_msgTypeTag
{
  vbittype RtcRxMulNo : 8;
  vbittype RtcRxMulD1 : 8;
  vbittype RtcRxMulD2 : 8;
  vbittype RtcRxMulD3 : 8;
  vbittype RtcRxMulD4 : 8;
  vbittype RtcRxMulD5 : 8;
  vbittype RtcRxMulD6 : 8;
  vbittype RtcRxMulD7 : 8;
} _c_RtcRxMulData_RDS_msgType;

typedef struct _c_UdsInterRx_RDS_msgTypeTag
{
  vbittype UdsRxCmd : 8;
  vbittype UdsRxD1 : 8;
  vbittype UdsRxD2 : 8;
  vbittype UdsRxD3 : 8;
  vbittype UdsRxD4 : 8;
  vbittype UdsRxD5 : 8;
  vbittype UdsRxD6 : 8;
  vbittype UdsRxD7 : 8;
} _c_UdsInterRx_RDS_msgType;

typedef struct _c_BcuCHAInfo2_RDS_msgTypeTag
{
  vbittype CellVolDiff_0 : 8;
  vbittype CellVolDiff_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
} _c_BcuCHAInfo2_RDS_msgType;

typedef struct _c_BcuCHAInfo1_RDS_msgTypeTag
{
  vbittype MaxCellV_0 : 8;
  vbittype MaxCellV_1 : 8;
  vbittype MinCellV_0 : 8;
  vbittype MinCellV_1 : 8;
  vbittype MaxCellVolNo : 8;
  vbittype MinCellVolNo : 8;
  vbittype AveCellVol_0 : 8;
  vbittype AveCellVol_1 : 8;
} _c_BcuCHAInfo1_RDS_msgType;

typedef struct _c_BcuBalCmdMc60A_1_RDS_msgTypeTag
{
  vbittype Mc60ACtrlLtc5_0 : 8;
  vbittype Mc60ACtrlLtc5_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
} _c_BcuBalCmdMc60A_1_RDS_msgType;

typedef struct _c_HcuData3_RDS_msgTypeTag
{
  vbittype HV_Uact2_2_0 : 8;
  vbittype HV_Uact2_2_1 : 8;
  vbittype HV_Uact2_3_0 : 8;
  vbittype HV_Uact2_3_1 : 8;
  vbittype HV_Uact2_4_0 : 8;
  vbittype HV_Uact2_4_1 : 8;
  vbittype HV_Uact2_5_0 : 8;
  vbittype HV_Uact2_5_1 : 8;
} _c_HcuData3_RDS_msgType;

typedef struct _c_HcuData1_RDS_msgTypeTag
{
  vbittype IsoRst_0 : 8;
  vbittype IsoRst_1 : 8;
  vbittype IsoHvFlg : 8;
} _c_HcuData1_RDS_msgType;

typedef struct _c_HcuData0_RDS_msgTypeTag
{
  vbittype HV_Uact1_0 : 8;
  vbittype HV_Uact1_1 : 8;
  vbittype HV_Uact2_0 : 8;
  vbittype HV_Uact2_1 : 8;
  vbittype Ipack_1_0 : 8;
  vbittype Ipack_1_1 : 8;
  vbittype HcuSt : 8;
} _c_HcuData0_RDS_msgType;

typedef struct _c_RtcTxMulReq_RDS_msgTypeTag
{
  vbittype RtcTxMulReqCmd : 8;
  vbittype RtcTxMulReqByteSum : 8;
  vbittype unused0 : 8;
  vbittype RtcTxMulReqPackSum : 8;
  vbittype unused1 : 8;
  vbittype RtcTxMulReqPGN_0 : 8;
  vbittype RtcTxMulReqPGN_1 : 8;
  vbittype RtcTxMulReqPGN_2 : 8;
} _c_RtcTxMulReq_RDS_msgType;

typedef struct _c_RtcTxMsg_RDS_msgTypeTag
{
  vbittype RtcTxD0 : 8;
  vbittype RtcTxD1 : 8;
  vbittype RtcTxD2 : 8;
  vbittype RtcTxD3 : 8;
  vbittype RtcTxD4 : 8;
  vbittype RtcTxD5 : 8;
  vbittype RtcTxD6 : 8;
  vbittype RtcTxCmd : 8;
} _c_RtcTxMsg_RDS_msgType;

typedef struct _c_Mc33BState_RDS_msgTypeTag
{
  vbittype Mc33BAveCellV_0 : 8;
  vbittype Mc33BAveCellV_1 : 8;
  vbittype Mc33BTxErrCnt : 8;
  vbittype Mc33BRxErrCnt : 8;
  vbittype Mc33BCanResets : 8;
  vbittype Mc33BCanErrDirect : 8;
  vbittype Mc33BErrCode : 4;
  vbittype Mc33BSt : 4;
  vbittype Mc33BErrCounter : 8;
} _c_Mc33BState_RDS_msgType;

typedef struct _c_Mc60AState_RDS_msgTypeTag
{
  vbittype Mc60AAveCellV_0 : 8;
  vbittype Mc60AAveCellV_1 : 8;
  vbittype Mc60ATxErrCnt : 8;
  vbittype Mc60ARxErrCnt : 8;
  vbittype Mc60ACanResets : 8;
  vbittype Mc60ACanErrDirect : 8;
  vbittype Mc60AErrCode : 4;
  vbittype Mc60ASt : 4;
  vbittype Mc60AErrCounter : 8;
} _c_Mc60AState_RDS_msgType;

typedef struct _c_McInit_RDS_msgTypeTag
{
  vbittype McInit_Cmd : 8;
  vbittype McInit_McNo : 8;
  vbittype McInit_Data1 : 8;
  vbittype McInit_Data2 : 8;
  vbittype McInit_Data3 : 8;
  vbittype McInit_Data4 : 8;
  vbittype McInit_Data5 : 8;
  vbittype McInit_Data6 : 8;
} _c_McInit_RDS_msgType;

typedef struct _c_Mc33BData02_RDS_msgTypeTag
{
  vbittype Ucell68_0 : 8;
  vbittype Ucell68_1 : 8;
  vbittype Ucell69_0 : 8;
  vbittype Ucell69_1 : 8;
  vbittype Ucell70_0 : 8;
  vbittype Ucell70_1 : 8;
  vbittype Ucell71_0 : 8;
  vbittype Ucell71_1 : 8;
} _c_Mc33BData02_RDS_msgType;

typedef struct _c_Mc60AData15_RDS_msgTypeTag
{
  vbittype Mc60ATemp1 : 8;
  vbittype Mc60ATemp2 : 8;
  vbittype Mc60ATemp3 : 8;
  vbittype Mc60ATemp4 : 8;
} _c_Mc60AData15_RDS_msgType;

typedef struct _c_Mc33BData01_RDS_msgTypeTag
{
  vbittype Ucell64_0 : 8;
  vbittype Ucell64_1 : 8;
  vbittype Ucell65_0 : 8;
  vbittype Ucell65_1 : 8;
  vbittype Ucell66_0 : 8;
  vbittype Ucell66_1 : 8;
  vbittype Ucell67_0 : 8;
  vbittype Ucell67_1 : 8;
} _c_Mc33BData01_RDS_msgType;

typedef struct _c_Mc33BData00_RDS_msgTypeTag
{
  vbittype Ucell60_0 : 8;
  vbittype Ucell60_1 : 8;
  vbittype Ucell61_0 : 8;
  vbittype Ucell61_1 : 8;
  vbittype Ucell62_0 : 8;
  vbittype Ucell62_1 : 8;
  vbittype Ucell63_0 : 8;
  vbittype Ucell63_1 : 8;
} _c_Mc33BData00_RDS_msgType;

typedef struct _c_Mc33BData15_RDS_msgTypeTag
{
  vbittype Mc33BTemp1 : 8;
  vbittype Mc33BTemp2 : 8;
  vbittype Mc33BTemp3 : 8;
  vbittype Mc33BTemp4 : 8;
} _c_Mc33BData15_RDS_msgType;

typedef struct _c_Mc60AData02_RDS_msgTypeTag
{
  vbittype Ucell08_0 : 8;
  vbittype Ucell08_1 : 8;
  vbittype Ucell09_0 : 8;
  vbittype Ucell09_1 : 8;
  vbittype Ucell10_0 : 8;
  vbittype Ucell10_1 : 8;
  vbittype Ucell11_0 : 8;
  vbittype Ucell11_1 : 8;
} _c_Mc60AData02_RDS_msgType;

typedef struct _c_Mc60AData01_RDS_msgTypeTag
{
  vbittype Ucell04_0 : 8;
  vbittype Ucell04_1 : 8;
  vbittype Ucell05_0 : 8;
  vbittype Ucell05_1 : 8;
  vbittype Ucell06_0 : 8;
  vbittype Ucell06_1 : 8;
  vbittype Ucell07_0 : 8;
  vbittype Ucell07_1 : 8;
} _c_Mc60AData01_RDS_msgType;

typedef struct _c_Mc60AData00_RDS_msgTypeTag
{
  vbittype Ucell00_0 : 8;
  vbittype Ucell00_1 : 8;
  vbittype Ucell01_0 : 8;
  vbittype Ucell01_1 : 8;
  vbittype Ucell02_0 : 8;
  vbittype Ucell02_1 : 8;
  vbittype Ucell03_0 : 8;
  vbittype Ucell03_1 : 8;
} _c_Mc60AData00_RDS_msgType;

typedef struct _c_Mc33BBalState_0_RDS_msgTypeTag
{
  vbittype Mc33BStatLtc1_0 : 8;
  vbittype Mc33BStatLtc1_1 : 8;
  vbittype Mc33BStatLtc2_0 : 8;
  vbittype Mc33BStatLtc2_1 : 8;
  vbittype Mc33BStatLtc3_0 : 8;
  vbittype Mc33BStatLtc3_1 : 8;
} _c_Mc33BBalState_0_RDS_msgType;

typedef struct _c_Mc60ABalState_0_RDS_msgTypeTag
{
  vbittype Mc60AStatLtc1_0 : 8;
  vbittype Mc60AStatLtc1_1 : 8;
  vbittype Mc60AStatLtc2_0 : 8;
  vbittype Mc60AStatLtc2_1 : 8;
  vbittype Mc60AStatLtc3_0 : 8;
  vbittype Mc60AStatLtc3_1 : 8;
  vbittype Mc60AStatLtc4_0 : 8;
  vbittype Mc60AStatLtc4_1 : 8;
} _c_Mc60ABalState_0_RDS_msgType;

typedef struct _c_RtcTime_RDS_msgTypeTag
{
  vbittype RtcSec : 8;
  vbittype RtcMin : 8;
  vbittype RtcHour : 8;
  vbittype RtcDay : 8;
  vbittype RtcWeek : 8;
  vbittype RtcMonth : 8;
  vbittype RtcYear : 8;
} _c_RtcTime_RDS_msgType;

typedef struct _c_RtcIo_RDS_msgTypeTag
{
  vbittype Cc2Vol : 8;
  vbittype CcPwmDt : 8;
  vbittype CcVol : 8;
  vbittype GprsVol : 8;
  vbittype PwrVol : 8;
  vbittype RtcSt : 8;
} _c_RtcIo_RDS_msgType;

typedef struct _c_UdsInterTx_RDS_msgTypeTag
{
  vbittype UdsTxCmd : 8;
  vbittype UdsTxD1 : 8;
  vbittype UdsTxD2 : 8;
  vbittype UdsTxD3 : 8;
  vbittype UdsTxD4 : 8;
  vbittype UdsTxD5 : 8;
  vbittype UdsTxD6 : 8;
  vbittype UdsTxD7 : 8;
} _c_UdsInterTx_RDS_msgType;

typedef struct _c_Mc33BData05_RDS_msgTypeTag
{
  vbittype Ucell80_0 : 8;
  vbittype Ucell80_1 : 8;
  vbittype Ucell81_0 : 8;
  vbittype Ucell81_1 : 8;
  vbittype Ucell82_0 : 8;
  vbittype Ucell82_1 : 8;
  vbittype Ucell83_0 : 8;
  vbittype Ucell83_1 : 8;
} _c_Mc33BData05_RDS_msgType;

typedef struct _c_Mc33BData04_RDS_msgTypeTag
{
  vbittype Ucell76_0 : 8;
  vbittype Ucell76_1 : 8;
  vbittype Ucell77_0 : 8;
  vbittype Ucell77_1 : 8;
  vbittype Ucell78_0 : 8;
  vbittype Ucell78_1 : 8;
  vbittype Ucell79_0 : 8;
  vbittype Ucell79_1 : 8;
} _c_Mc33BData04_RDS_msgType;

typedef struct _c_Mc33BData03_RDS_msgTypeTag
{
  vbittype Ucell72_0 : 8;
  vbittype Ucell72_1 : 8;
  vbittype Ucell73_0 : 8;
  vbittype Ucell73_1 : 8;
  vbittype Ucell74_0 : 8;
  vbittype Ucell74_1 : 8;
  vbittype Ucell75_0 : 8;
  vbittype Ucell75_1 : 8;
} _c_Mc33BData03_RDS_msgType;

typedef struct _c_Mc60AData03_RDS_msgTypeTag
{
  vbittype Ucell12_0 : 8;
  vbittype Ucell12_1 : 8;
  vbittype Ucell13_0 : 8;
  vbittype Ucell13_1 : 8;
  vbittype Ucell14_0 : 8;
  vbittype Ucell14_1 : 8;
  vbittype Ucell15_0 : 8;
  vbittype Ucell15_1 : 8;
} _c_Mc60AData03_RDS_msgType;

typedef struct _c_Mc60AData04_RDS_msgTypeTag
{
  vbittype Ucell16_0 : 8;
  vbittype Ucell16_1 : 8;
  vbittype Ucell17_0 : 8;
  vbittype Ucell17_1 : 8;
  vbittype Ucell18_0 : 8;
  vbittype Ucell18_1 : 8;
  vbittype Ucell19_0 : 8;
  vbittype Ucell19_1 : 8;
} _c_Mc60AData04_RDS_msgType;

typedef struct _c_Mc60AData05_RDS_msgTypeTag
{
  vbittype Ucell20_0 : 8;
  vbittype Ucell20_1 : 8;
  vbittype Ucell21_0 : 8;
  vbittype Ucell21_1 : 8;
  vbittype Ucell22_0 : 8;
  vbittype Ucell22_1 : 8;
  vbittype Ucell23_0 : 8;
  vbittype Ucell23_1 : 8;
} _c_Mc60AData05_RDS_msgType;

typedef struct _c_Mc60ABalState_1_RDS_msgTypeTag
{
  vbittype Mc60AStatLtc5_0 : 8;
  vbittype Mc60AStatLtc5_1 : 8;
} _c_Mc60ABalState_1_RDS_msgType;

typedef struct _c_Mc60AData06_RDS_msgTypeTag
{
  vbittype Ucell24_0 : 8;
  vbittype Ucell24_1 : 8;
  vbittype Ucell25_0 : 8;
  vbittype Ucell25_1 : 8;
  vbittype Ucell26_0 : 8;
  vbittype Ucell26_1 : 8;
  vbittype Ucell27_0 : 8;
  vbittype Ucell27_1 : 8;
} _c_Mc60AData06_RDS_msgType;

typedef struct _c_Mc60AData07_RDS_msgTypeTag
{
  vbittype Ucell28_0 : 8;
  vbittype Ucell28_1 : 8;
  vbittype Ucell29_0 : 8;
  vbittype Ucell29_1 : 8;
  vbittype Ucell30_0 : 8;
  vbittype Ucell30_1 : 8;
  vbittype Ucell31_0 : 8;
  vbittype Ucell31_1 : 8;
} _c_Mc60AData07_RDS_msgType;

typedef struct _c_Mc60AData08_RDS_msgTypeTag
{
  vbittype Ucell32_0 : 8;
  vbittype Ucell32_1 : 8;
  vbittype Ucell33_0 : 8;
  vbittype Ucell33_1 : 8;
  vbittype Ucell34_0 : 8;
  vbittype Ucell34_1 : 8;
  vbittype Ucell35_0 : 8;
  vbittype Ucell35_1 : 8;
} _c_Mc60AData08_RDS_msgType;

typedef struct _c_Mc33BData06_RDS_msgTypeTag
{
  vbittype Ucell84_0 : 8;
  vbittype Ucell84_1 : 8;
  vbittype Ucell85_0 : 8;
  vbittype Ucell85_1 : 8;
  vbittype Ucell86_0 : 8;
  vbittype Ucell86_1 : 8;
  vbittype Ucell87_0 : 8;
  vbittype Ucell87_1 : 8;
} _c_Mc33BData06_RDS_msgType;

typedef struct _c_Mc33BData07_RDS_msgTypeTag
{
  vbittype Ucell88_0 : 8;
  vbittype Ucell88_1 : 8;
  vbittype Ucell89_0 : 8;
  vbittype Ucell89_1 : 8;
  vbittype Ucell90_0 : 8;
  vbittype Ucell90_1 : 8;
  vbittype Ucell91_0 : 8;
  vbittype Ucell91_1 : 8;
} _c_Mc33BData07_RDS_msgType;

typedef struct _c_Mc33BData08_RDS_msgTypeTag
{
  vbittype Ucell92_0 : 8;
  vbittype Ucell92_1 : 8;
} _c_Mc33BData08_RDS_msgType;

typedef struct _c_Mc60AData14_RDS_msgTypeTag
{
  vbittype Ucell56_0 : 8;
  vbittype Ucell56_1 : 8;
  vbittype Ucell57_0 : 8;
  vbittype Ucell57_1 : 8;
  vbittype Ucell58_0 : 8;
  vbittype Ucell58_1 : 8;
  vbittype Ucell59_0 : 8;
  vbittype Ucell59_1 : 8;
} _c_Mc60AData14_RDS_msgType;

typedef struct _c_Mc60AData13_RDS_msgTypeTag
{
  vbittype Ucell52_0 : 8;
  vbittype Ucell52_1 : 8;
  vbittype Ucell53_0 : 8;
  vbittype Ucell53_1 : 8;
  vbittype Ucell54_0 : 8;
  vbittype Ucell54_1 : 8;
  vbittype Ucell55_0 : 8;
  vbittype Ucell55_1 : 8;
} _c_Mc60AData13_RDS_msgType;

typedef struct _c_Mc60AData12_RDS_msgTypeTag
{
  vbittype Ucell48_0 : 8;
  vbittype Ucell48_1 : 8;
  vbittype Ucell49_0 : 8;
  vbittype Ucell49_1 : 8;
  vbittype Ucell50_0 : 8;
  vbittype Ucell50_1 : 8;
  vbittype Ucell51_0 : 8;
  vbittype Ucell51_1 : 8;
} _c_Mc60AData12_RDS_msgType;

typedef struct _c_Mc60AData11_RDS_msgTypeTag
{
  vbittype Ucell44_0 : 8;
  vbittype Ucell44_1 : 8;
  vbittype Ucell45_0 : 8;
  vbittype Ucell45_1 : 8;
  vbittype Ucell46_0 : 8;
  vbittype Ucell46_1 : 8;
  vbittype Ucell47_0 : 8;
  vbittype Ucell47_1 : 8;
} _c_Mc60AData11_RDS_msgType;

typedef struct _c_Mc60AData10_RDS_msgTypeTag
{
  vbittype Ucell40_0 : 8;
  vbittype Ucell40_1 : 8;
  vbittype Ucell41_0 : 8;
  vbittype Ucell41_1 : 8;
  vbittype Ucell42_0 : 8;
  vbittype Ucell42_1 : 8;
  vbittype Ucell43_0 : 8;
  vbittype Ucell43_1 : 8;
} _c_Mc60AData10_RDS_msgType;

typedef struct _c_Mc60AData09_RDS_msgTypeTag
{
  vbittype Ucell36_0 : 8;
  vbittype Ucell36_1 : 8;
  vbittype Ucell37_0 : 8;
  vbittype Ucell37_1 : 8;
  vbittype Ucell38_0 : 8;
  vbittype Ucell38_1 : 8;
  vbittype Ucell39_0 : 8;
  vbittype Ucell39_1 : 8;
} _c_Mc60AData09_RDS_msgType;

typedef union _c_RDS30_bufTag
{
  vuint8 _c[8];
  _c_BcuSyc100msMsg_RDS_msgType BcuSyc100msMsg;
} _c_RDS30_buf;
typedef union _c_RDS31_bufTag
{
  vuint8 _c[8];
  _c_BcuInit_RDS_msgType BcuInit;
} _c_RDS31_buf;
typedef union _c_RDS32_bufTag
{
  vuint8 _c[8];
  _c_BcuBalCmdMc60A_0_RDS_msgType BcuBalCmdMc60A_0;
} _c_RDS32_buf;
typedef union _c_RDS33_bufTag
{
  vuint8 _c[8];
  _c_BcuBalCmdMc33B_0_RDS_msgType BcuBalCmdMc33B_0;
} _c_RDS33_buf;
typedef union _c_RDS34_bufTag
{
  vuint8 _c[8];
  _c_RtcRxMsg_RDS_msgType RtcRxMsg;
} _c_RDS34_buf;
typedef union _c_RDS35_bufTag
{
  vuint8 _c[8];
  _c_RtcRxMulReq_RDS_msgType RtcRxMulReq;
} _c_RDS35_buf;
typedef union _c_RDS36_bufTag
{
  vuint8 _c[8];
  _c_RtcRxMulData_RDS_msgType RtcRxMulData;
} _c_RDS36_buf;
typedef union _c_RDS_Tx_buf_1Tag
{
  vuint8 _c[8];
  _c_UdsInterRx_RDS_msgType UdsInterRx;
  _c_BcuCHAInfo2_RDS_msgType BcuCHAInfo2;
  _c_BcuCHAInfo1_RDS_msgType BcuCHAInfo1;
  _c_BcuBalCmdMc60A_1_RDS_msgType BcuBalCmdMc60A_1;
} _c_RDS_Tx_buf_1;
typedef union _c_RDS52_bufTag
{
  vuint8 _c[8];
  _c_HcuData3_RDS_msgType HcuData3;
} _c_RDS52_buf;
typedef union _c_RDS53_bufTag
{
  vuint8 _c[8];
  _c_HcuData1_RDS_msgType HcuData1;
} _c_RDS53_buf;
typedef union _c_RDS54_bufTag
{
  vuint8 _c[8];
  _c_HcuData0_RDS_msgType HcuData0;
} _c_RDS54_buf;
typedef union _c_RDS55_bufTag
{
  vuint8 _c[8];
  _c_RtcTxMulReq_RDS_msgType RtcTxMulReq;
} _c_RDS55_buf;
typedef union _c_RDS56_bufTag
{
  vuint8 _c[8];
  _c_RtcTxMsg_RDS_msgType RtcTxMsg;
} _c_RDS56_buf;
typedef union _c_RDS57_bufTag
{
  vuint8 _c[8];
  _c_Mc33BState_RDS_msgType Mc33BState;
} _c_RDS57_buf;
typedef union _c_RDS58_bufTag
{
  vuint8 _c[8];
  _c_Mc60AState_RDS_msgType Mc60AState;
} _c_RDS58_buf;
typedef union _c_RDS59_bufTag
{
  vuint8 _c[8];
  _c_McInit_RDS_msgType McInit;
} _c_RDS59_buf;
typedef union _c_RDSBasic1_buf_1Tag
{
  vuint8 _c[8];
  _c_Mc33BData02_RDS_msgType Mc33BData02;
  _c_Mc60AData15_RDS_msgType Mc60AData15;
  _c_Mc33BData01_RDS_msgType Mc33BData01;
  _c_Mc33BData00_RDS_msgType Mc33BData00;
  _c_Mc33BData15_RDS_msgType Mc33BData15;
  _c_Mc60AData02_RDS_msgType Mc60AData02;
  _c_Mc60AData01_RDS_msgType Mc60AData01;
  _c_Mc60AData00_RDS_msgType Mc60AData00;
  _c_Mc33BBalState_0_RDS_msgType Mc33BBalState_0;
  _c_Mc60ABalState_0_RDS_msgType Mc60ABalState_0;
  _c_RtcTime_RDS_msgType RtcTime;
  _c_RtcIo_RDS_msgType RtcIo;
  _c_UdsInterTx_RDS_msgType UdsInterTx;
  _c_Mc33BData05_RDS_msgType Mc33BData05;
  _c_Mc33BData04_RDS_msgType Mc33BData04;
  _c_Mc33BData03_RDS_msgType Mc33BData03;
  _c_Mc60AData03_RDS_msgType Mc60AData03;
  _c_Mc60AData04_RDS_msgType Mc60AData04;
  _c_Mc60AData05_RDS_msgType Mc60AData05;
  _c_Mc60ABalState_1_RDS_msgType Mc60ABalState_1;
  _c_Mc60AData06_RDS_msgType Mc60AData06;
  _c_Mc60AData07_RDS_msgType Mc60AData07;
  _c_Mc60AData08_RDS_msgType Mc60AData08;
  _c_Mc33BData06_RDS_msgType Mc33BData06;
  _c_Mc33BData07_RDS_msgType Mc33BData07;
  _c_Mc33BData08_RDS_msgType Mc33BData08;
  _c_Mc60AData14_RDS_msgType Mc60AData14;
  _c_Mc60AData13_RDS_msgType Mc60AData13;
  _c_Mc60AData12_RDS_msgType Mc60AData12;
  _c_Mc60AData11_RDS_msgType Mc60AData11;
  _c_Mc60AData10_RDS_msgType Mc60AData10;
  _c_Mc60AData09_RDS_msgType Mc60AData09;
} _c_RDSBasic1_buf_1;


#define RDS30                                ((* ((_c_RDS30_buf MEMORY_CAN *)(canRDSTxPtr[9]))))
#define RDS31                                ((* ((_c_RDS31_buf MEMORY_CAN *)(canRDSTxPtr[10]))))
#define RDS32                                ((* ((_c_RDS32_buf MEMORY_CAN *)(canRDSTxPtr[11]))))
#define RDS33                                ((* ((_c_RDS33_buf MEMORY_CAN *)(canRDSTxPtr[12]))))
#define RDS34                                ((* ((_c_RDS34_buf MEMORY_CAN *)(canRDSTxPtr[13]))))
#define RDS35                                ((* ((_c_RDS35_buf MEMORY_CAN *)(canRDSTxPtr[14]))))
#define RDS36                                ((* ((_c_RDS36_buf MEMORY_CAN *)(canRDSTxPtr[15]))))
#define RDSTx_1                              ((* ((_c_RDS_Tx_buf_1 MEMORY_CAN *)(canRDSTxPtr[16]))))
#define RDS52                                ((* ((_c_RDS52_buf MEMORY_CAN *)(canRDSRxPtr[1]))))
#define RDS53                                ((* ((_c_RDS53_buf MEMORY_CAN *)(canRDSRxPtr[1]))))
#define RDS54                                ((* ((_c_RDS54_buf MEMORY_CAN *)(canRDSRxPtr[1]))))
#define RDS55                                ((* ((_c_RDS55_buf MEMORY_CAN *)(canRDSRxPtr[1]))))
#define RDS56                                ((* ((_c_RDS56_buf MEMORY_CAN *)(canRDSRxPtr[1]))))
#define RDS57                                ((* ((_c_RDS57_buf MEMORY_CAN *)(canRDSRxPtr[1]))))
#define RDS58                                ((* ((_c_RDS58_buf MEMORY_CAN *)(canRDSRxPtr[1]))))
#define RDS59                                ((* ((_c_RDS59_buf MEMORY_CAN *)(canRDSRxPtr[1]))))
#define RDSBasic1_1                          ((* ((_c_RDSBasic1_buf_1 MEMORY_CAN *)(canRDSRxPtr[1]))))



/* -----------------------------------------------------------------------------
    &&&~ Message Hardware Objects
 ----------------------------------------------------------------------------- */

#define CanTxTxXCP_HW_OBJ                    0
#define CanTxTxXCP_HW_CHANNEL                0
#define CanTxBcuSD1_HW_OBJ                   1
#define CanTxBcuSD1_HW_CHANNEL               0
#define CanTxBcuSD2_HW_OBJ                   2
#define CanTxBcuSD2_HW_CHANNEL               0
#define CanTxBcuSD3_HW_OBJ                   3
#define CanTxBcuSD3_HW_CHANNEL               0
#define CanTxBcuSD4_HW_OBJ                   4
#define CanTxBcuSD4_HW_CHANNEL               0
#define CanTxBcuSD5_HW_OBJ                   5
#define CanTxBcuSD5_HW_CHANNEL               0
#define CanTxBcuSD6_HW_OBJ                   6
#define CanTxBcuSD6_HW_CHANNEL               0
#define CanTxUdsTx_HW_OBJ                    7
#define CanTxUdsTx_HW_CHANNEL                0
#define C_TX_NORMAL_0_HW_OBJ                 8
#define C_TX_NORMAL_0_HW_CHANNEL             0
#define CanRxUdsRx_HW_OBJ                    25
#define CanRxUdsRx_HW_CHANNEL                0
#define C_BASIC0_0_HW_OBJ                    26
#define C_BASIC0_0_HW_CHANNEL                0
#define C_BASIC1_0_HW_OBJ                    28
#define C_BASIC1_0_HW_CHANNEL                0

#define CanTxBcuSyc100msMsg_HW_OBJ           30
#define CanTxBcuSyc100msMsg_HW_CHANNEL       1
#define CanTxBcuInit_HW_OBJ                  31
#define CanTxBcuInit_HW_CHANNEL              1
#define CanTxBcuBalCmdMc60A_0_HW_OBJ         32
#define CanTxBcuBalCmdMc60A_0_HW_CHANNEL     1
#define CanTxBcuBalCmdMc33B_0_HW_OBJ         33
#define CanTxBcuBalCmdMc33B_0_HW_CHANNEL     1
#define CanTxRtcRxMsg_HW_OBJ                 34
#define CanTxRtcRxMsg_HW_CHANNEL             1
#define CanTxRtcRxMulReq_HW_OBJ              35
#define CanTxRtcRxMulReq_HW_CHANNEL          1
#define CanTxRtcRxMulData_HW_OBJ             36
#define CanTxRtcRxMulData_HW_CHANNEL         1
#define C_TX_NORMAL_1_HW_OBJ                 37
#define C_TX_NORMAL_1_HW_CHANNEL             1
#define CanRxHcuData3_HW_OBJ                 52
#define CanRxHcuData3_HW_CHANNEL             1
#define CanRxHcuData1_HW_OBJ                 53
#define CanRxHcuData1_HW_CHANNEL             1
#define CanRxHcuData0_HW_OBJ                 54
#define CanRxHcuData0_HW_CHANNEL             1
#define CanRxRtcTxMulReq_HW_OBJ              55
#define CanRxRtcTxMulReq_HW_CHANNEL          1
#define CanRxRtcTxMsg_HW_OBJ                 56
#define CanRxRtcTxMsg_HW_CHANNEL             1
#define CanRxMc33BState_HW_OBJ               57
#define CanRxMc33BState_HW_CHANNEL           1
#define CanRxMc60AState_HW_OBJ               58
#define CanRxMc60AState_HW_CHANNEL           1
#define CanRxMcInit_HW_OBJ                   59
#define CanRxMcInit_HW_CHANNEL               1
#define C_BASIC0_1_HW_OBJ                    60
#define C_BASIC0_1_HW_CHANNEL                1
#define C_BASIC1_1_HW_OBJ                    62
#define C_BASIC1_1_HW_CHANNEL                1





/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 210607152
      #error "The magic number of the generated file <D:\workspace\R1556\can_par.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 210607152
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __CAN_PAR_H__ */
