/* -----------------------------------------------------------------------------
  Filename:    can_par.c
  Description: Toolversion: 02.01.13.01.10.01.32.00.00.00
                
                Serial Number: CBD1100132
                Customer Info: BEIQI Foton Motor Co., Ltd.
                               Foton
                               Microcontroller: Infineon TriCore TC1767
                               Compiler: Tasking V3.3r1
                
                
                Generator Fwk   : GENy 
                Generator Module: DrvCan__base
                
                Configuration   : D:\TaskingTc&GENywork\R1556\BMS_R1556\Bsw\Can\configCAN\configGENy\R1556.gny
                
                ECU: 
                        TargetSystem: Hw_TricoreCpu
                        Compiler:     Tasking
                        Derivates:    INFINEON_TC1767
                
                Channel "Channel0":
                        Databasefile: D:\DBC WORK\R1556\R1556_Veh_02.dbc
                        Bussystem:    CAN
                        Manufacturer: Vector
                        Node:         Bcu
                Channel "Channel1":
                        Databasefile: D:\DBC WORK\R1556\R1556_Inter_02.dbc
                        Bussystem:    CAN
                        Manufacturer: Vector
                        Node:         Bcu

  Generated by , 2015-12-25  17:24:00
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2008 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#define C_DRV_INTERNAL
#include "can_inc.h"
#include "can_par.h"
#include "v_inc.h"

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanTxId0 V_MEMROM2 CanTxId0[kCanNumberOfTxObjects] = 
{
  MK_STDID0(0x7E4u) /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  MK_EXTID0(0x1D00A6A9u) /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  MK_EXTID0(0x1C00A6A9u) /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  MK_EXTID0(0x1806E5F4u) /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  MK_EXTID0(0x1000A6A9u) /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  MK_EXTID0(0x900A6A9u) /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  MK_EXTID0(0x800A6A9u) /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  MK_STDID0(0x7E8u) /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  MK_STDID0(0x7E7u) /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  MK_STDID0(0x7E6u) /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  MK_STDID0(0x7E5u) /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  MK_STDID0(0x7E3u) /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  MK_STDID0(0x7E2u) /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  MK_STDID0(0x7E1u) /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  MK_STDID0(0x200u) /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  MK_STDID0(0x7EBu) /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  MK_STDID0(0x7EAu) /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  MK_STDID0(0x7E0u) /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  MK_STDID0(0x201u) /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  MK_STDID0(0x303u) /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  MK_STDID0(0x302u) /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  MK_STDID0(0x300u) /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  MK_STDID0(0x220u) /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  MK_STDID0(0x200u) /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  MK_STDID0(0x090u) /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  MK_STDID0(0x082u) /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanTxId1 V_MEMROM2 CanTxId1[kCanNumberOfTxObjects] = 
{
  MK_STDID1(0x7E4u) /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  MK_EXTID1(0x1D00A6A9u) /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  MK_EXTID1(0x1C00A6A9u) /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  MK_EXTID1(0x1806E5F4u) /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  MK_EXTID1(0x1000A6A9u) /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  MK_EXTID1(0x900A6A9u) /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  MK_EXTID1(0x800A6A9u) /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  MK_STDID1(0x7E8u) /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  MK_STDID1(0x7E7u) /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  MK_STDID1(0x7E6u) /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  MK_STDID1(0x7E5u) /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  MK_STDID1(0x7E3u) /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  MK_STDID1(0x7E2u) /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  MK_STDID1(0x7E1u) /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  MK_STDID1(0x200u) /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  MK_STDID1(0x7EBu) /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  MK_STDID1(0x7EAu) /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  MK_STDID1(0x7E0u) /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  MK_STDID1(0x201u) /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  MK_STDID1(0x303u) /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  MK_STDID1(0x302u) /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  MK_STDID1(0x300u) /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  MK_STDID1(0x220u) /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  MK_STDID1(0x200u) /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  MK_STDID1(0x090u) /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  MK_STDID1(0x082u) /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxDLC[kCanNumberOfTxObjects] = 
{
  MK_TX_DLC(8) /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  MK_TX_DLC_EXT(8) /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  MK_TX_DLC_EXT(8) /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  MK_TX_DLC_EXT(8) /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  MK_TX_DLC_EXT(8) /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  MK_TX_DLC_EXT(8) /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  MK_TX_DLC_EXT(8) /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  MK_TX_DLC(8) /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  MK_TX_DLC(8) /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  MK_TX_DLC(8) /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  MK_TX_DLC(8) /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  MK_TX_DLC(8) /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  MK_TX_DLC(8) /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  MK_TX_DLC(8) /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  MK_TX_DLC(8) /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  MK_TX_DLC(8) /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  MK_TX_DLC(8) /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  MK_TX_DLC(8) /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 1 END */


#ifdef C_ENABLE_COPY_TX_DATA
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 TxDataPtr V_MEMROM2 CanTxDataPtr[kCanNumberOfTxObjects] = 
{
  (vuint8*) BcuTime._c /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  (vuint8*) BmsToVcu_E._c /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  (vuint8*) BmsToVcu_D._c /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  (vuint8*) Bcu_CarCharA._c /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  (vuint8*) BmsToVcu_C._c /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  (vuint8*) BmsTxVcu_B._c /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  (vuint8*) BcuToVcu_A._c /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  (vuint8*) UdsTx._c /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  (vuint8*) BcuSD6._c /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  (vuint8*) BcuSD5._c /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  (vuint8*) BcuSD4._c /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  (vuint8*) BcuSD3._c /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  (vuint8*) BcuSD2._c /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  (vuint8*) BcuSD1._c /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  (vuint8*) TxXCP._c /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  (vuint8*) BcuCHAInfo2._c /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  (vuint8*) BcuCHAInfo1._c /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  (vuint8*) UdsInterRx._c /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  (vuint8*) BcuBalCmdMc60A_1._c /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  (vuint8*) RtcRxMulData._c /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  (vuint8*) RtcRxMulReq._c /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  (vuint8*) RtcRxMsg._c /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  (vuint8*) BcuBalCmdMc33B_0._c /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  (vuint8*) BcuBalCmdMc60A_0._c /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  (vuint8*) BcuInit._c /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  (vuint8*) BcuSyc100msMsg._c /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_PRETRANSMIT_FCT
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplPreTransmitFct V_MEMROM2 CanTxApplPreTransmitPtr[kCanNumberOfTxObjects] = 
{
  V_NULL /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  V_NULL /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  V_NULL /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  V_NULL /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  V_NULL /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  V_NULL /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  V_NULL /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  V_NULL /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  V_NULL /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  V_NULL /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  V_NULL /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  V_NULL /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  V_NULL /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  V_NULL /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  V_NULL /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  V_NULL /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  V_NULL /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  V_NULL /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  V_NULL /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  V_NULL /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  V_NULL /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  V_NULL /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  V_NULL /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  V_NULL /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  V_NULL /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  V_NULL /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_CONFIRMATION_FCT
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplConfirmationFct V_MEMROM2 CanTxApplConfirmationPtr[kCanNumberOfTxObjects] = 
{
  V_NULL /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  V_NULL /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  V_NULL /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  V_NULL /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  V_NULL /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  V_NULL /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  V_NULL /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  V_NULL /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  V_NULL /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  V_NULL /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  V_NULL /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  V_NULL /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  V_NULL /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  V_NULL /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  XcpConfirmation /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  V_NULL /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  V_NULL /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  V_NULL /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  V_NULL /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  V_NULL /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  V_NULL /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  V_NULL /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  V_NULL /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  V_NULL /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  V_NULL /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  V_NULL /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_PART_OFFLINE
/* ROM CATEGORY 2 START */

V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxSendMask[kCanNumberOfTxObjects] = 
{
  C_SEND_GRP_NONE /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  C_SEND_GRP_NONE /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  C_SEND_GRP_NONE /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};

/* ROM CATEGORY 2 END */

#endif


#ifdef C_ENABLE_CONFIRMATION_FLAG
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanConfirmationOffset[kCanNumberOfTxObjects] = 
{
  0 /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  0 /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  0 /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  0 /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  0 /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  0 /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  0 /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  0 /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  1 /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  1 /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  1 /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  1 /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  1 /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  1 /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  1 /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  1 /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  2 /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  2 /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  2 /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  2 /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  2 /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  2 /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  2 /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  2 /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  3 /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  3 /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanConfirmationMask[kCanNumberOfTxObjects] = 
{
  0x01 /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  0x02 /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  0x04 /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  0x08 /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  0x10 /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  0x20 /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  0x40 /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  0x80 /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  0x01 /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  0x02 /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  0x04 /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  0x08 /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  0x10 /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  0x20 /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  0x40 /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  0x80 /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  0x01 /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  0x02 /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  0x04 /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  0x08 /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  0x10 /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  0x20 /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  0x40 /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  0x80 /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  0x01 /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  0x02 /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 1 END */


#endif




/* Id table depending on search algorithm */
/* Linear search */
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanRxId0 V_MEMROM2 CanRxId0[kCanNumberOfRxObjects] = 
{
  MK_EXTID0(0x18FF50E5u) /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */, 
  MK_STDID0(0x201u) /* ID: 0x00000201, Handle: 43, RxXCP [BC] */, 
  MK_EXTID0(0x700A9A6u) /* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */, 
  MK_STDID0(0x7E0u) /* ID: 0x000007e0, Handle: 2, UdsRx [FC] */, 
  MK_STDID0(0x7E8u) /* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */, 
  MK_STDID0(0x306u) /* ID: 0x00000306, Handle: 7, RtcTime [BC] */, 
  MK_STDID0(0x305u) /* ID: 0x00000305, Handle: 8, RtcIo [BC] */, 
  MK_STDID0(0x22Bu) /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */, 
  MK_STDID0(0x20Cu) /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */, 
  MK_STDID0(0x20Bu) /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */, 
  MK_STDID0(0x12Fu) /* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */, 
  MK_STDID0(0x128u) /* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */, 
  MK_STDID0(0x127u) /* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */, 
  MK_STDID0(0x126u) /* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */, 
  MK_STDID0(0x125u) /* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */, 
  MK_STDID0(0x124u) /* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */, 
  MK_STDID0(0x123u) /* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */, 
  MK_STDID0(0x122u) /* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */, 
  MK_STDID0(0x121u) /* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */, 
  MK_STDID0(0x120u) /* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */, 
  MK_STDID0(0x10Fu) /* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */, 
  MK_STDID0(0x10Eu) /* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */, 
  MK_STDID0(0x10Du) /* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */, 
  MK_STDID0(0x10Cu) /* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */, 
  MK_STDID0(0x10Bu) /* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */, 
  MK_STDID0(0x10Au) /* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */, 
  MK_STDID0(0x109u) /* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */, 
  MK_STDID0(0x108u) /* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */, 
  MK_STDID0(0x107u) /* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */, 
  MK_STDID0(0x106u) /* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */, 
  MK_STDID0(0x105u) /* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */, 
  MK_STDID0(0x104u) /* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */, 
  MK_STDID0(0x103u) /* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */, 
  MK_STDID0(0x102u) /* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */, 
  MK_STDID0(0x101u) /* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */, 
  MK_STDID0(0x100u) /* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */, 
  MK_STDID0(0x522u) /* ID: 0x00000522, Handle: 4, HcuData3 [FC] */, 
  MK_STDID0(0x521u) /* ID: 0x00000521, Handle: 5, HcuData1 [FC] */, 
  MK_STDID0(0x520u) /* ID: 0x00000520, Handle: 6, HcuData0 [FC] */, 
  MK_STDID0(0x304u) /* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */, 
  MK_STDID0(0x301u) /* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */, 
  MK_STDID0(0x22Du) /* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */, 
  MK_STDID0(0x20Du) /* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */, 
  MK_STDID0(0x092u) /* ID: 0x00000092, Handle: 42, McInit [FC] */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanRxId1 V_MEMROM2 CanRxId1[kCanNumberOfRxObjects] = 
{
  MK_EXTID1(0x18FF50E5u) /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */, 
  MK_STDID1(0x201u) /* ID: 0x00000201, Handle: 43, RxXCP [BC] */, 
  MK_EXTID1(0x700A9A6u) /* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */, 
  MK_STDID1(0x7E0u) /* ID: 0x000007e0, Handle: 2, UdsRx [FC] */, 
  MK_STDID1(0x7E8u) /* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */, 
  MK_STDID1(0x306u) /* ID: 0x00000306, Handle: 7, RtcTime [BC] */, 
  MK_STDID1(0x305u) /* ID: 0x00000305, Handle: 8, RtcIo [BC] */, 
  MK_STDID1(0x22Bu) /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */, 
  MK_STDID1(0x20Cu) /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */, 
  MK_STDID1(0x20Bu) /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */, 
  MK_STDID1(0x12Fu) /* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */, 
  MK_STDID1(0x128u) /* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */, 
  MK_STDID1(0x127u) /* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */, 
  MK_STDID1(0x126u) /* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */, 
  MK_STDID1(0x125u) /* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */, 
  MK_STDID1(0x124u) /* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */, 
  MK_STDID1(0x123u) /* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */, 
  MK_STDID1(0x122u) /* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */, 
  MK_STDID1(0x121u) /* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */, 
  MK_STDID1(0x120u) /* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */, 
  MK_STDID1(0x10Fu) /* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */, 
  MK_STDID1(0x10Eu) /* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */, 
  MK_STDID1(0x10Du) /* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */, 
  MK_STDID1(0x10Cu) /* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */, 
  MK_STDID1(0x10Bu) /* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */, 
  MK_STDID1(0x10Au) /* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */, 
  MK_STDID1(0x109u) /* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */, 
  MK_STDID1(0x108u) /* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */, 
  MK_STDID1(0x107u) /* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */, 
  MK_STDID1(0x106u) /* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */, 
  MK_STDID1(0x105u) /* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */, 
  MK_STDID1(0x104u) /* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */, 
  MK_STDID1(0x103u) /* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */, 
  MK_STDID1(0x102u) /* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */, 
  MK_STDID1(0x101u) /* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */, 
  MK_STDID1(0x100u) /* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */, 
  MK_STDID1(0x522u) /* ID: 0x00000522, Handle: 4, HcuData3 [FC] */, 
  MK_STDID1(0x521u) /* ID: 0x00000521, Handle: 5, HcuData1 [FC] */, 
  MK_STDID1(0x520u) /* ID: 0x00000520, Handle: 6, HcuData0 [FC] */, 
  MK_STDID1(0x304u) /* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */, 
  MK_STDID1(0x301u) /* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */, 
  MK_STDID1(0x22Du) /* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */, 
  MK_STDID1(0x20Du) /* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */, 
  MK_STDID1(0x092u) /* ID: 0x00000092, Handle: 42, McInit [FC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanReceiveHandle V_MEMROM2 CanRxMsgIndirection[kCanNumberOfRxObjects] = 
{
  0 /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB */, 
  43 /* ID: 0x00000201, Handle: 43, RxXCP */, 
  1 /* ID: 0x0700a9a6, Handle: 1, VcuToBms */, 
  2 /* ID: 0x000007e0, Handle: 2, UdsRx */, 
  3 /* ID: 0x000007e8, Handle: 3, UdsInterTx */, 
  7 /* ID: 0x00000306, Handle: 7, RtcTime */, 
  8 /* ID: 0x00000305, Handle: 8, RtcIo */, 
  12 /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 */, 
  14 /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 */, 
  15 /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 */, 
  16 /* ID: 0x0000012f, Handle: 16, Mc60AData15 */, 
  17 /* ID: 0x00000128, Handle: 17, Mc33BData08 */, 
  18 /* ID: 0x00000127, Handle: 18, Mc33BData07 */, 
  19 /* ID: 0x00000126, Handle: 19, Mc33BData06 */, 
  20 /* ID: 0x00000125, Handle: 20, Mc33BData05 */, 
  21 /* ID: 0x00000124, Handle: 21, Mc33BData04 */, 
  22 /* ID: 0x00000123, Handle: 22, Mc33BData03 */, 
  23 /* ID: 0x00000122, Handle: 23, Mc33BData02 */, 
  24 /* ID: 0x00000121, Handle: 24, Mc33BData01 */, 
  25 /* ID: 0x00000120, Handle: 25, Mc33BData00 */, 
  26 /* ID: 0x0000010f, Handle: 26, Mc33BData15 */, 
  27 /* ID: 0x0000010e, Handle: 27, Mc60AData14 */, 
  28 /* ID: 0x0000010d, Handle: 28, Mc60AData13 */, 
  29 /* ID: 0x0000010c, Handle: 29, Mc60AData12 */, 
  30 /* ID: 0x0000010b, Handle: 30, Mc60AData11 */, 
  31 /* ID: 0x0000010a, Handle: 31, Mc60AData10 */, 
  32 /* ID: 0x00000109, Handle: 32, Mc60AData09 */, 
  33 /* ID: 0x00000108, Handle: 33, Mc60AData08 */, 
  34 /* ID: 0x00000107, Handle: 34, Mc60AData07 */, 
  35 /* ID: 0x00000106, Handle: 35, Mc60AData06 */, 
  36 /* ID: 0x00000105, Handle: 36, Mc60AData05 */, 
  37 /* ID: 0x00000104, Handle: 37, Mc60AData04 */, 
  38 /* ID: 0x00000103, Handle: 38, Mc60AData03 */, 
  39 /* ID: 0x00000102, Handle: 39, Mc60AData02 */, 
  40 /* ID: 0x00000101, Handle: 40, Mc60AData01 */, 
  41 /* ID: 0x00000100, Handle: 41, Mc60AData00 */, 
  4 /* ID: 0x00000522, Handle: 4, HcuData3 */, 
  5 /* ID: 0x00000521, Handle: 5, HcuData1 */, 
  6 /* ID: 0x00000520, Handle: 6, HcuData0 */, 
  9 /* ID: 0x00000304, Handle: 9, RtcTxMulReq */, 
  10 /* ID: 0x00000301, Handle: 10, RtcTxMsg */, 
  11 /* ID: 0x0000022d, Handle: 11, Mc33BState */, 
  13 /* ID: 0x0000020d, Handle: 13, Mc60AState */, 
  42 /* ID: 0x00000092, Handle: 42, McInit */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanRxDataLen[kCanNumberOfRxObjects] = 
{
  5 /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */, 
  1 /* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */, 
  8 /* ID: 0x000007e0, Handle: 2, UdsRx [FC] */, 
  8 /* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */, 
  8 /* ID: 0x00000522, Handle: 4, HcuData3 [FC] */, 
  3 /* ID: 0x00000521, Handle: 5, HcuData1 [FC] */, 
  7 /* ID: 0x00000520, Handle: 6, HcuData0 [FC] */, 
  7 /* ID: 0x00000306, Handle: 7, RtcTime [BC] */, 
  6 /* ID: 0x00000305, Handle: 8, RtcIo [BC] */, 
  8 /* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */, 
  8 /* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */, 
  8 /* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */, 
  6 /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */, 
  8 /* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */, 
  2 /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */, 
  8 /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */, 
  4 /* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */, 
  2 /* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */, 
  8 /* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */, 
  8 /* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */, 
  8 /* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */, 
  8 /* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */, 
  8 /* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */, 
  8 /* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */, 
  8 /* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */, 
  8 /* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */, 
  4 /* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */, 
  8 /* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */, 
  8 /* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */, 
  8 /* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */, 
  8 /* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */, 
  8 /* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */, 
  8 /* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */, 
  8 /* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */, 
  8 /* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */, 
  8 /* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */, 
  8 /* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */, 
  8 /* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */, 
  8 /* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */, 
  8 /* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */, 
  8 /* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */, 
  8 /* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */, 
  8 /* ID: 0x00000092, Handle: 42, McInit [FC] */, 
  8 /* ID: 0x00000201, Handle: 43, RxXCP [BC] */
};
/* ROM CATEGORY 1 END */


#ifdef C_ENABLE_COPY_RX_DATA
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 RxDataPtr V_MEMROM2 CanRxDataPtr[kCanNumberOfRxObjects] = 
{
  (vuint8*) Bcu_CarCharB._c /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */, 
  (vuint8*) VcuToBms._c /* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */, 
  (vuint8*) UdsRx._c /* ID: 0x000007e0, Handle: 2, UdsRx [FC] */, 
  (vuint8*) UdsInterTx._c /* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */, 
  (vuint8*) HcuData3._c /* ID: 0x00000522, Handle: 4, HcuData3 [FC] */, 
  (vuint8*) HcuData1._c /* ID: 0x00000521, Handle: 5, HcuData1 [FC] */, 
  (vuint8*) HcuData0._c /* ID: 0x00000520, Handle: 6, HcuData0 [FC] */, 
  (vuint8*) RtcTime._c /* ID: 0x00000306, Handle: 7, RtcTime [BC] */, 
  (vuint8*) RtcIo._c /* ID: 0x00000305, Handle: 8, RtcIo [BC] */, 
  (vuint8*) RtcTxMulReq._c /* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */, 
  (vuint8*) RtcTxMsg._c /* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */, 
  (vuint8*) Mc33BState._c /* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */, 
  (vuint8*) Mc33BBalState_0._c /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */, 
  (vuint8*) Mc60AState._c /* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */, 
  (vuint8*) Mc60ABalState_1._c /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */, 
  (vuint8*) Mc60ABalState_0._c /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */, 
  (vuint8*) Mc60AData15._c /* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */, 
  (vuint8*) Mc33BData08._c /* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */, 
  (vuint8*) Mc33BData07._c /* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */, 
  (vuint8*) Mc33BData06._c /* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */, 
  (vuint8*) Mc33BData05._c /* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */, 
  (vuint8*) Mc33BData04._c /* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */, 
  (vuint8*) Mc33BData03._c /* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */, 
  (vuint8*) Mc33BData02._c /* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */, 
  (vuint8*) Mc33BData01._c /* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */, 
  (vuint8*) Mc33BData00._c /* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */, 
  (vuint8*) Mc33BData15._c /* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */, 
  (vuint8*) Mc60AData14._c /* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */, 
  (vuint8*) Mc60AData13._c /* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */, 
  (vuint8*) Mc60AData12._c /* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */, 
  (vuint8*) Mc60AData11._c /* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */, 
  (vuint8*) Mc60AData10._c /* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */, 
  (vuint8*) Mc60AData09._c /* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */, 
  (vuint8*) Mc60AData08._c /* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */, 
  (vuint8*) Mc60AData07._c /* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */, 
  (vuint8*) Mc60AData06._c /* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */, 
  (vuint8*) Mc60AData05._c /* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */, 
  (vuint8*) Mc60AData04._c /* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */, 
  (vuint8*) Mc60AData03._c /* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */, 
  (vuint8*) Mc60AData02._c /* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */, 
  (vuint8*) Mc60AData01._c /* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */, 
  (vuint8*) Mc60AData00._c /* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */, 
  (vuint8*) McInit._c /* ID: 0x00000092, Handle: 42, McInit [FC] */, 
  (vuint8*) RxXCP._c /* ID: 0x00000201, Handle: 43, RxXCP [BC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_PRECOPY_FCT
/* CODE CATEGORY 1 START */
/* CODE CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplPrecopyFct V_MEMROM2 CanRxApplPrecopyPtr[kCanNumberOfRxObjects] = 
{
  IlMsgBcu_CarCharBPreCopy /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */, 
  IlMsgVcuToBmsPreCopy /* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */, 
  V_NULL /* ID: 0x000007e0, Handle: 2, UdsRx [FC] */, 
  V_NULL /* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */, 
  IlMsgHcuData3PreCopy /* ID: 0x00000522, Handle: 4, HcuData3 [FC] */, 
  V_NULL /* ID: 0x00000521, Handle: 5, HcuData1 [FC] */, 
  IlMsgHcuData0PreCopy /* ID: 0x00000520, Handle: 6, HcuData0 [FC] */, 
  IlMsgRtcTimePreCopy /* ID: 0x00000306, Handle: 7, RtcTime [BC] */, 
  IlMsgRtcIoPreCopy /* ID: 0x00000305, Handle: 8, RtcIo [BC] */, 
  V_NULL /* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */, 
  V_NULL /* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */, 
  IlMsgMc33BStatePreCopy /* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */, 
  IlMsgMc33BBalState_0PreCopy /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */, 
  IlMsgMc60AStatePreCopy /* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */, 
  IlMsgMc60ABalState_1PreCopy /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */, 
  IlMsgMc60ABalState_0PreCopy /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */, 
  IlMsgMc60AData15PreCopy /* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */, 
  IlMsgMc33BData08PreCopy /* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */, 
  IlMsgMc33BData07PreCopy /* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */, 
  IlMsgMc33BData06PreCopy /* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */, 
  IlMsgMc33BData05PreCopy /* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */, 
  IlMsgMc33BData04PreCopy /* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */, 
  IlMsgMc33BData03PreCopy /* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */, 
  IlMsgMc33BData02PreCopy /* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */, 
  IlMsgMc33BData01PreCopy /* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */, 
  IlMsgMc33BData00PreCopy /* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */, 
  IlMsgMc33BData15PreCopy /* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */, 
  IlMsgMc60AData14PreCopy /* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */, 
  IlMsgMc60AData13PreCopy /* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */, 
  IlMsgMc60AData12PreCopy /* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */, 
  IlMsgMc60AData11PreCopy /* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */, 
  IlMsgMc60AData10PreCopy /* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */, 
  IlMsgMc60AData09PreCopy /* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */, 
  IlMsgMc60AData08PreCopy /* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */, 
  IlMsgMc60AData07PreCopy /* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */, 
  IlMsgMc60AData06PreCopy /* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */, 
  IlMsgMc60AData05PreCopy /* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */, 
  IlMsgMc60AData04PreCopy /* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */, 
  IlMsgMc60AData03PreCopy /* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */, 
  IlMsgMc60AData02PreCopy /* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */, 
  IlMsgMc60AData01PreCopy /* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */, 
  IlMsgMc60AData00PreCopy /* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */, 
  V_NULL /* ID: 0x00000092, Handle: 42, McInit [FC] */, 
  XcpPreCopy /* ID: 0x00000201, Handle: 43, RxXCP [BC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_INDICATION_FCT
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 ApplIndicationFct V_MEMROM2 CanRxApplIndicationPtr[kCanNumberOfRxObjects] = 
{
  BCOM_RxBcu_CarCharB /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */, 
  V_NULL /* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */, 
  BCOM_RxUdsRx /* ID: 0x000007e0, Handle: 2, UdsRx [FC] */, 
  V_NULL /* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */, 
  BCOM_HcuData3 /* ID: 0x00000522, Handle: 4, HcuData3 [FC] */, 
  BCOM_HcuData1 /* ID: 0x00000521, Handle: 5, HcuData1 [FC] */, 
  BCOM_HcuData0 /* ID: 0x00000520, Handle: 6, HcuData0 [FC] */, 
  V_NULL /* ID: 0x00000306, Handle: 7, RtcTime [BC] */, 
  V_NULL /* ID: 0x00000305, Handle: 8, RtcIo [BC] */, 
  BCOM_RtcMulReq /* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */, 
  BCOM_RtcRxMsg /* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */, 
  BCOM_Mc33BState /* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */, 
  V_NULL /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */, 
  BCOM_Mc60AState /* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */, 
  V_NULL /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */, 
  V_NULL /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */, 
  V_NULL /* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */, 
  V_NULL /* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */, 
  V_NULL /* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */, 
  V_NULL /* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */, 
  V_NULL /* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */, 
  V_NULL /* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */, 
  V_NULL /* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */, 
  V_NULL /* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */, 
  V_NULL /* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */, 
  V_NULL /* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */, 
  V_NULL /* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */, 
  V_NULL /* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */, 
  V_NULL /* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */, 
  V_NULL /* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */, 
  V_NULL /* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */, 
  V_NULL /* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */, 
  V_NULL /* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */, 
  V_NULL /* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */, 
  V_NULL /* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */, 
  V_NULL /* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */, 
  V_NULL /* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */, 
  V_NULL /* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */, 
  V_NULL /* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */, 
  V_NULL /* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */, 
  V_NULL /* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */, 
  V_NULL /* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */, 
  BCOM_BcuRxMdulCtrl /* ID: 0x00000092, Handle: 42, McInit [FC] */, 
  V_NULL /* ID: 0x00000201, Handle: 43, RxXCP [BC] */
};
/* ROM CATEGORY 1 END */

#endif


#ifdef C_ENABLE_INDICATION_FLAG
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanIndicationOffset[kCanNumberOfRxObjects] = 
{
  0 /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */, 
  0 /* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */, 
  0 /* ID: 0x000007e0, Handle: 2, UdsRx [FC] */, 
  0 /* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */, 
  0 /* ID: 0x00000522, Handle: 4, HcuData3 [FC] */, 
  0 /* ID: 0x00000521, Handle: 5, HcuData1 [FC] */, 
  0 /* ID: 0x00000520, Handle: 6, HcuData0 [FC] */, 
  0 /* ID: 0x00000306, Handle: 7, RtcTime [BC] */, 
  0 /* ID: 0x00000305, Handle: 8, RtcIo [BC] */, 
  0 /* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */, 
  0 /* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */, 
  0 /* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */, 
  0 /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */, 
  0 /* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */, 
  0 /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */, 
  0 /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */, 
  0 /* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */, 
  0 /* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */, 
  0 /* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */, 
  0 /* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */, 
  0 /* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */, 
  0 /* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */, 
  0 /* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */, 
  0 /* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */, 
  0 /* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */, 
  0 /* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */, 
  0 /* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */, 
  0 /* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */, 
  0 /* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */, 
  0 /* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */, 
  0 /* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */, 
  0 /* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */, 
  0 /* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */, 
  0 /* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */, 
  0 /* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */, 
  0 /* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */, 
  0 /* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */, 
  0 /* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */, 
  0 /* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */, 
  0 /* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */, 
  0 /* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */, 
  0 /* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */, 
  0 /* ID: 0x00000092, Handle: 42, McInit [FC] */, 
  0 /* ID: 0x00000201, Handle: 43, RxXCP [BC] */
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanIndicationMask[kCanNumberOfRxObjects] = 
{
  0 /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */, 
  0 /* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */, 
  0 /* ID: 0x000007e0, Handle: 2, UdsRx [FC] */, 
  0 /* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */, 
  0 /* ID: 0x00000522, Handle: 4, HcuData3 [FC] */, 
  0 /* ID: 0x00000521, Handle: 5, HcuData1 [FC] */, 
  0 /* ID: 0x00000520, Handle: 6, HcuData0 [FC] */, 
  0 /* ID: 0x00000306, Handle: 7, RtcTime [BC] */, 
  0 /* ID: 0x00000305, Handle: 8, RtcIo [BC] */, 
  0 /* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */, 
  0 /* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */, 
  0 /* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */, 
  0 /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */, 
  0 /* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */, 
  0 /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */, 
  0 /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */, 
  0 /* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */, 
  0 /* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */, 
  0 /* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */, 
  0 /* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */, 
  0 /* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */, 
  0 /* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */, 
  0 /* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */, 
  0 /* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */, 
  0 /* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */, 
  0 /* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */, 
  0 /* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */, 
  0 /* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */, 
  0 /* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */, 
  0 /* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */, 
  0 /* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */, 
  0 /* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */, 
  0 /* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */, 
  0 /* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */, 
  0 /* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */, 
  0 /* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */, 
  0 /* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */, 
  0 /* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */, 
  0 /* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */, 
  0 /* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */, 
  0 /* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */, 
  0 /* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */, 
  0 /* ID: 0x00000092, Handle: 42, McInit [FC] */, 
  0x01 /* ID: 0x00000201, Handle: 43, RxXCP [BC] */
};
/* ROM CATEGORY 1 END */


#endif




/* -----------------------------------------------------------------------------
    &&&~ Init structures
 ----------------------------------------------------------------------------- */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanInitObjectStartIndex[3] = 
{
  0, 
  1, 
  2
};

/* ROM CATEGORY 4 END */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitBT[kCanNumberOfInitObjects] = 
{
  0x2313u, 
  0x3E03u
};
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitMaskH[kCanNumberOfInitObjects*kCanNumberOfMaxBasicCAN] = 
{
  0x2003u, 
  0x2000u, 
  0x2003u, 
  0x2000u
};
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitMaskL[kCanNumberOfInitObjects*kCanNumberOfMaxBasicCAN] = 
{
  0xFFFFu, 
  0x0000u, 
  0xFFFFu, 
  0x0000u
};
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitCodeH[kCanNumberOfInitObjects*kCanNumberOfMaxBasicCAN] = 
{
  0x0000u, 
  0x2000u, 
  0x0000u, 
  0x2000u
};
V_MEMROM0 V_MEMROM1 vuint16 V_MEMROM2 CanInitCodeL[kCanNumberOfInitObjects*kCanNumberOfMaxBasicCAN] = 
{
  0x0000u, 
  0x0000u, 
  0x0000u, 
  0x0000u
};
/* ROM CATEGORY 4 END */



/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanTransmitHandle V_MEMROM2 CanTxDynRomStartIndex[kCanNumberOfChannels] = 
{
  15, 
  26
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */

V_MEMROM0 V_MEMROM1 CanTransmitHandle V_MEMROM2 CanTxDynRamStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  0, 
  0
};

/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tCanChannelObject V_MEMROM2 CanChannelObject[kCanNumberOfChannels] = 
{
  
  {
    ApplCanWakeUp, 
    CAN_RECEIVE_FCT_DUMMY, 
    
    {
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY
    }, 
    ApplCanBusOff, 
    IlCanCancelNotification, 
    ApplCanChannelDummy, 
    
    {
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u)
    }, 
    
    {
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u)
    }, 
    0x00u, 
    
    {
      kCanIdTypeStd, 
      kCanIdTypeStd, 
      kCanIdTypeStd, 
      kCanIdTypeStd
    }
  }, 
  
  {
    ApplCanWakeUp, 
    CAN_RECEIVE_FCT_DUMMY, 
    
    {
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY, 
      CAN_RANGE_FCT_DUMMY
    }, 
    ApplCanBusOff, 
    IlCanCancelNotification, 
    ApplCanChannelDummy, 
    
    {
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u), 
      MK_RX_RANGE_MASK_IDSTD(0x00u)
    }, 
    
    {
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u), 
      MK_RX_RANGE_CODE_IDSTD(0x00u)
    }, 
    0x00u, 
    
    {
      kCanIdTypeStd, 
      kCanIdTypeStd, 
      kCanIdTypeStd, 
      kCanIdTypeStd
    }
  }
};
/* ROM CATEGORY 1 END */

#if defined(C_ENABLE_MULTI_ECU_CONFIG)
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanPhysToLogChannel[kVNumberOfIdentities][kCanNumberOfPhysChannels] = 
{
  
  {
    0, 
    1
  }
};
/* ROM CATEGORY 1 END */

#endif

#if defined(C_ENABLE_MULTI_ECU_CONFIG)
/* ROM CATEGORY 2 START */

V_MEMROM0 V_MEMROM1 tVIdentityMsk V_MEMROM2 CanChannelIdentityAssignment[kCanNumberOfChannels] = 
{
  0x01u, 
  0x01u
};

/* ROM CATEGORY 2 END */

#endif

#if defined(C_ENABLE_MULTI_ECU_PHYS)
/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 tVIdentityMsk V_MEMROM2 CanRxIdentityAssignment[kCanNumberOfRxObjects] = 
{
  0x01u /* ID: 0x18ff50e5, Handle: 0, Bcu_CarCharB [BC] */, 
  0x01u /* ID: 0x0700a9a6, Handle: 1, VcuToBms [BC] */, 
  0x01u /* ID: 0x000007e0, Handle: 2, UdsRx [FC] */, 
  0x01u /* ID: 0x000007e8, Handle: 3, UdsInterTx [BC] */, 
  0x01u /* ID: 0x00000522, Handle: 4, HcuData3 [FC] */, 
  0x01u /* ID: 0x00000521, Handle: 5, HcuData1 [FC] */, 
  0x01u /* ID: 0x00000520, Handle: 6, HcuData0 [FC] */, 
  0x01u /* ID: 0x00000306, Handle: 7, RtcTime [BC] */, 
  0x01u /* ID: 0x00000305, Handle: 8, RtcIo [BC] */, 
  0x01u /* ID: 0x00000304, Handle: 9, RtcTxMulReq [FC] */, 
  0x01u /* ID: 0x00000301, Handle: 10, RtcTxMsg [FC] */, 
  0x01u /* ID: 0x0000022d, Handle: 11, Mc33BState [FC] */, 
  0x01u /* ID: 0x0000022b, Handle: 12, Mc33BBalState_0 [BC] */, 
  0x01u /* ID: 0x0000020d, Handle: 13, Mc60AState [FC] */, 
  0x01u /* ID: 0x0000020c, Handle: 14, Mc60ABalState_1 [BC] */, 
  0x01u /* ID: 0x0000020b, Handle: 15, Mc60ABalState_0 [BC] */, 
  0x01u /* ID: 0x0000012f, Handle: 16, Mc60AData15 [BC] */, 
  0x01u /* ID: 0x00000128, Handle: 17, Mc33BData08 [BC] */, 
  0x01u /* ID: 0x00000127, Handle: 18, Mc33BData07 [BC] */, 
  0x01u /* ID: 0x00000126, Handle: 19, Mc33BData06 [BC] */, 
  0x01u /* ID: 0x00000125, Handle: 20, Mc33BData05 [BC] */, 
  0x01u /* ID: 0x00000124, Handle: 21, Mc33BData04 [BC] */, 
  0x01u /* ID: 0x00000123, Handle: 22, Mc33BData03 [BC] */, 
  0x01u /* ID: 0x00000122, Handle: 23, Mc33BData02 [BC] */, 
  0x01u /* ID: 0x00000121, Handle: 24, Mc33BData01 [BC] */, 
  0x01u /* ID: 0x00000120, Handle: 25, Mc33BData00 [BC] */, 
  0x01u /* ID: 0x0000010f, Handle: 26, Mc33BData15 [BC] */, 
  0x01u /* ID: 0x0000010e, Handle: 27, Mc60AData14 [BC] */, 
  0x01u /* ID: 0x0000010d, Handle: 28, Mc60AData13 [BC] */, 
  0x01u /* ID: 0x0000010c, Handle: 29, Mc60AData12 [BC] */, 
  0x01u /* ID: 0x0000010b, Handle: 30, Mc60AData11 [BC] */, 
  0x01u /* ID: 0x0000010a, Handle: 31, Mc60AData10 [BC] */, 
  0x01u /* ID: 0x00000109, Handle: 32, Mc60AData09 [BC] */, 
  0x01u /* ID: 0x00000108, Handle: 33, Mc60AData08 [BC] */, 
  0x01u /* ID: 0x00000107, Handle: 34, Mc60AData07 [BC] */, 
  0x01u /* ID: 0x00000106, Handle: 35, Mc60AData06 [BC] */, 
  0x01u /* ID: 0x00000105, Handle: 36, Mc60AData05 [BC] */, 
  0x01u /* ID: 0x00000104, Handle: 37, Mc60AData04 [BC] */, 
  0x01u /* ID: 0x00000103, Handle: 38, Mc60AData03 [BC] */, 
  0x01u /* ID: 0x00000102, Handle: 39, Mc60AData02 [BC] */, 
  0x01u /* ID: 0x00000101, Handle: 40, Mc60AData01 [BC] */, 
  0x01u /* ID: 0x00000100, Handle: 41, Mc60AData00 [BC] */, 
  0x01u /* ID: 0x00000092, Handle: 42, McInit [FC] */, 
  0x01u /* ID: 0x00000201, Handle: 43, RxXCP [BC] */
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 tVIdentityMsk V_MEMROM2 CanTxIdentityAssignment[kCanNumberOfTxObjects] = 
{
  0x01u /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  0x01u /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  0x01u /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  0x01u /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  0x01u /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  0x01u /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  0x01u /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  0x01u /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  0x01u /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  0x01u /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  0x01u /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  0x01u /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  0x01u /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  0x01u /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  0x01u /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  0x01u /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  0x01u /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  0x01u /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  0x01u /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  0x01u /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  0x01u /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  0x01u /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  0x01u /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  0x01u /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  0x01u /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  0x01u /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 4 END */

#endif


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxQueuePadBits[kCanNumberOfChannels] = 
{
  0, 
  17
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanSignedTxHandle V_MEMROM2 CanTxQueueStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  1, 
  2
};
/* ROM CATEGORY 1 END */

/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanChannelHandle V_MEMROM2 CanTxMsgHandleToChannel[kCanNumberOfTxObjects] = 
{
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  0, 
  1, 
  1, 
  1, 
  1, 
  1, 
  1, 
  1, 
  1, 
  1, 
  1, 
  1
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 1 START */

V_MEMROM0 V_MEMROM1 CanTransmitHandle V_MEMROM2 CanTxStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  15, 
  26
};

/* ROM CATEGORY 1 END */


/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanReceiveHandle V_MEMROM2 CanRxStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  4, 
  44
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanReceiveHandle V_MEMROM2 CanRxBasicStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  4, 
  44
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanReceiveHandle V_MEMROM2 CanRxFullStartIndex[kCanNumberOfChannels+1] = 
{
  3, 
  36, 
  44
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanLogHwTxStartIndex[kCanNumberOfChannels+1] = 
{
  0, 
  9, 
  17
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwTxStartIndex[kCanNumberOfChannels] = 
{
  0, 
  30
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwRxFullStartIndex[kCanNumberOfChannels] = 
{
  25, 
  52
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwRxBasicStartIndex[kCanNumberOfChannels] = 
{
  26, 
  60
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 4 START */

V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwUnusedStartIndex[kCanNumberOfChannels] = 
{
  9, 
  38
};

/* ROM CATEGORY 4 END */


/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwTxStopIndex[kCanNumberOfChannels] = 
{
  9, 
  38
};
/* ROM CATEGORY 2 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwRxFullStopIndex[kCanNumberOfChannels] = 
{
  26, 
  60
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */
V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwRxBasicStopIndex[kCanNumberOfChannels] = 
{
  30, 
  64
};
/* ROM CATEGORY 1 END */


/* ROM CATEGORY 4 START */

V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwUnusedStopIndex[kCanNumberOfChannels] = 
{
  25, 
  52
};

/* ROM CATEGORY 4 END */


#ifdef C_ENABLE_TX_FULLCAN_OBJECTS
/* ROM CATEGORY 2 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanTxHwObj[kCanNumberOfTxObjects] = 
{
  0x08u /* ID: 0x000007e4, Handle: 0, BcuTime [BC] */, 
  0x08u /* ID: 0x1d00a6a9, Handle: 1, BmsToVcu_E [BC] */, 
  0x08u /* ID: 0x1c00a6a9, Handle: 2, BmsToVcu_D [BC] */, 
  0x08u /* ID: 0x1806e5f4, Handle: 3, Bcu_CarCharA [BC] */, 
  0x08u /* ID: 0x1000a6a9, Handle: 4, BmsToVcu_C [BC] */, 
  0x08u /* ID: 0x0900a6a9, Handle: 5, BmsTxVcu_B [BC] */, 
  0x08u /* ID: 0x0800a6a9, Handle: 6, BcuToVcu_A [BC] */, 
  0x07u /* ID: 0x000007e8, Handle: 7, UdsTx [FC] */, 
  0x06u /* ID: 0x000007e7, Handle: 8, BcuSD6 [FC] */, 
  0x05u /* ID: 0x000007e6, Handle: 9, BcuSD5 [FC] */, 
  0x04u /* ID: 0x000007e5, Handle: 10, BcuSD4 [FC] */, 
  0x03u /* ID: 0x000007e3, Handle: 11, BcuSD3 [FC] */, 
  0x02u /* ID: 0x000007e2, Handle: 12, BcuSD2 [FC] */, 
  0x01u /* ID: 0x000007e1, Handle: 13, BcuSD1 [FC] */, 
  0x00u /* ID: 0x00000200, Handle: 14, TxXCP [FC] */, 
  0x25u /* ID: 0x000007eb, Handle: 15, BcuCHAInfo2 [BC] */, 
  0x25u /* ID: 0x000007ea, Handle: 16, BcuCHAInfo1 [BC] */, 
  0x25u /* ID: 0x000007e0, Handle: 17, UdsInterRx [BC] */, 
  0x25u /* ID: 0x00000201, Handle: 18, BcuBalCmdMc60A_1 [BC] */, 
  0x24u /* ID: 0x00000303, Handle: 19, RtcRxMulData [FC] */, 
  0x23u /* ID: 0x00000302, Handle: 20, RtcRxMulReq [FC] */, 
  0x22u /* ID: 0x00000300, Handle: 21, RtcRxMsg [FC] */, 
  0x21u /* ID: 0x00000220, Handle: 22, BcuBalCmdMc33B_0 [FC] */, 
  0x20u /* ID: 0x00000200, Handle: 23, BcuBalCmdMc60A_0 [FC] */, 
  0x1Fu /* ID: 0x00000090, Handle: 24, BcuInit [FC] */, 
  0x1Eu /* ID: 0x00000082, Handle: 25, BcuSyc100msMsg [FC] */
};
/* ROM CATEGORY 2 END */

#endif



/* ROM CATEGORY 1 START */

V_MEMROM0 V_MEMROM1 CanObjectHandle V_MEMROM2 CanHwTxNormalIndex[kCanNumberOfChannels] = 
{
  8, 
  37
};

/* ROM CATEGORY 1 END */


/* ROM CATEGORY 1 START */

V_MEMROM0 V_MEMROM1 vsintx V_MEMROM2 CanTxOffsetHwToLog[kCanNumberOfChannels] = 
{
  0, 
  -21
};

/* ROM CATEGORY 1 END */



/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanNodeNum[kCanNumberOfChannels] = 
{
  C_NODE_0, 
  C_NODE_1
};
/* ROM CATEGORY 4 END */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 vuint32 V_MEMROM2 CanNodeAdr[kCanNumberOfChannels] = 
{
  0xF0004200u, 
  0xF0004300u
};
/* ROM CATEGORY 4 END */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanInitPortSel[kCanNumberOfChannels] = 
{
  0, 
  0
};
/* ROM CATEGORY 4 END */

/* ROM CATEGORY 3 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 canPhysPrio[2] = 
{
  35, 
  36
};
/* ROM CATEGORY 3 END */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 vuint8 V_MEMROM2 CanSrcNum[kCanNumberOfChannels] = 
{
  0, 
  1
};
/* ROM CATEGORY 4 END */

/* -----------------------------------------------------------------------------
    &&&~ CanInterruptPendingMask
 ----------------------------------------------------------------------------- */

/* ROM CATEGORY 4 START */
V_MEMROM0 V_MEMROM1 tCanIntPendMaskStruct V_MEMROM2 CanInterruptPendingMask[kCanNumberOfChannels] = 
{
  
  {
    { 0x3E0001FFu, 0x00u }, 
    { 0x01FFu, 0x00u }, 
    { 0x02000000u, 0x00u }, 
    { 0x3C000000u, 0x00u }
  }, 
  
  {
    { 0xC0000000u, 0xFFF0003Fu }, 
    { 0xC0000000u, 0x3Fu }, 
    { 0x00u, 0x0FF00000u }, 
    { 0x00u, 0xF0000000u }
  }
};
/* ROM CATEGORY 4 END */





/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 210607152
      #error "The magic number of the generated file <D:\workspace\R1556\can_par.c> is different. Please check time and date of generated files!"
  #endif
#else
  #error "The magic number is not defined in the generated file <D:\workspace\R1556\can_par.c> "

#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

