/* -----------------------------------------------------------------------------
  Filename:    drv_par.h
  Description: Toolversion: 02.01.13.01.10.01.32.00.00.00
                
                Serial Number: CBD1100132
                Customer Info: BEIQI Foton Motor Co., Ltd.
                               Foton
                               Microcontroller: Infineon TriCore TC1767
                               Compiler: Tasking V3.3r1
                
                
                Generator Fwk   : GENy 
                Generator Module: GenTool_GenyDriverBase
                
                Configuration   : D:\TaskingTc&GENywork\R1556\BMS_R1556\Bsw\Can\configCAN\configGENy\R1556.gny
                
                ECU: 
                        TargetSystem: Hw_TricoreCpu
                        Compiler:     Tasking
                        Derivates:    INFINEON_TC1767
                
                Channel "Channel0":
                        Databasefile: D:\DBC WORK\R1556\R1556_Veh_02.dbc
                        Bussystem:    CAN
                        Manufacturer: Vector
                        Node:         Bcu
                Channel "Channel1":
                        Databasefile: D:\DBC WORK\R1556\R1556_Inter_02.dbc
                        Bussystem:    CAN
                        Manufacturer: Vector
                        Node:         Bcu

  Generated by , 2015-12-25  17:24:00
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2008 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__DRV_PAR_H__)
#define __DRV_PAR_H__

/* -----------------------------------------------------------------------------
    &&&~ Signal Structures
 ----------------------------------------------------------------------------- */

typedef struct _c_TxXCP_msgTypeTag
{
  vbittype XCP_TxData_0 : 8;
  vbittype XCP_TxData_1 : 8;
  vbittype XCP_TxData_2 : 8;
  vbittype XCP_TxData_3 : 8;
  vbittype XCP_TxData_4 : 8;
  vbittype XCP_TxData_5 : 8;
  vbittype XCP_TxData_6 : 8;
  vbittype XCP_TxData_7 : 8;
} _c_TxXCP_msgType;
typedef struct _c_RxXCP_msgTypeTag
{
  vbittype XCP_RxData_0 : 8;
  vbittype XCP_RxData_1 : 8;
  vbittype XCP_RxData_2 : 8;
  vbittype XCP_RxData_3 : 8;
  vbittype XCP_RxData_4 : 8;
  vbittype XCP_RxData_5 : 8;
  vbittype XCP_RxData_6 : 8;
  vbittype XCP_RxData_7 : 8;
} _c_RxXCP_msgType;
typedef struct _c_UdsRx_msgTypeTag
{
  vbittype UdsRx_Cmd : 8;
  vbittype UdsRx_D1 : 8;
  vbittype UdsRx_D2 : 8;
  vbittype UdsRx_D3 : 8;
  vbittype UdsRx_D4 : 8;
  vbittype UdsRx_D5 : 8;
  vbittype UdsRx_D6 : 8;
  vbittype UdsRx_D7 : 8;
} _c_UdsRx_msgType;
typedef struct _c_UdsTx_msgTypeTag
{
  vbittype UdsTx_Cmd : 8;
  vbittype UdsTx_D1 : 8;
  vbittype UdsTx_D2 : 8;
  vbittype UdsTx_D3 : 8;
  vbittype UdsTx_D4 : 8;
  vbittype UdsTx_D5 : 8;
  vbittype UdsTx_D6 : 8;
  vbittype UdsTx_D7 : 8;
} _c_UdsTx_msgType;
typedef struct _c_BcuSD1_msgTypeTag
{
  vbittype BcuSt : 4;
  vbittype MccSt : 4;
  vbittype BalSt : 4;
  vbittype ThmSt : 4;
  vbittype SocCalcSt : 4;
  vbittype BatSt : 4;
  vbittype ChaRSt : 5;
  vbittype BmsErrLvl : 3;
  vbittype DTCCodeOutput : 8;
  vbittype CtctrStPos : 1;
  vbittype CtctrStNeg : 1;
  vbittype CtctrStPrec : 1;
  vbittype PtcConSt : 1;
  vbittype AirconConSt : 1;
  vbittype DCDCSt : 1;
  vbittype SetChaCtl : 1;
  vbittype StChaGun : 1;
  vbittype LowFanSt : 1;
  vbittype HighFanSt : 1;
  vbittype HeatSt : 1;
  vbittype WkSigCC_1 : 1;
  vbittype WkSigCC2_1 : 1;
  vbittype unused0 : 3;
  vbittype UWkKeyOn : 4;
  vbittype UWkCarCha : 4;
} _c_BcuSD1_msgType;
typedef struct _c_BcuSD2_msgTypeTag
{
  vbittype Uact1_0 : 8;
  vbittype Uact1_1 : 8;
  vbittype UcellSum : 8;
  vbittype Uact2 : 8;
  vbittype SocPack : 8;
  vbittype Soh : 8;
  vbittype BatMaxCp : 8;
  vbittype CarChaICP : 8;
} _c_BcuSD2_msgType;
typedef struct _c_BcuSD3_msgTypeTag
{
  vbittype UcellMax_0 : 8;
  vbittype UcellMax_1 : 8;
  vbittype UcellMin_0 : 8;
  vbittype UcellMin_1 : 8;
  vbittype TempMax : 8;
  vbittype TempMin : 8;
  vbittype Ipack_0_0 : 8;
  vbittype Ipack_0_1 : 8;
} _c_BcuSD3_msgType;
typedef struct _c_BcuSD4_msgTypeTag
{
  vbittype WarnUCellMax : 1;
  vbittype ErrUCellMax : 1;
  vbittype WarnUCellMin : 1;
  vbittype ErrUCellMin : 1;
  vbittype WarnTempMax : 1;
  vbittype ErrTempMax : 1;
  vbittype WarnTempMin : 1;
  vbittype ErrTempMin : 1;
  vbittype WarnUPackMax : 1;
  vbittype ErrUPackMax : 1;
  vbittype WarnUPackMin : 1;
  vbittype ErrUPackMin : 1;
  vbittype WarnIso : 1;
  vbittype ErrIso : 1;
  vbittype WarnIActDcha : 1;
  vbittype ErrIActDcha : 1;
  vbittype WarnIActCha : 1;
  vbittype ErrIActCha : 1;
  vbittype WarnUCellDiff : 1;
  vbittype ErrUCellDiff : 1;
  vbittype WarnTempDiff : 1;
  vbittype ErrTempDiff : 1;
  vbittype ErrUCellLow : 1;
  vbittype ErrUPackInter : 1;
  vbittype WarnIActChaBack : 1;
  vbittype ErrIActChaBack : 1;
  vbittype WarnIActChaCar : 1;
  vbittype ErrIActChaCar : 1;
  vbittype WarnIActChaBGBC : 1;
  vbittype ErrIActChaBGBC : 1;
  vbittype TempSnsrErr : 1;
  vbittype unused0 : 1;
  vbittype WkSig : 1;
  vbittype WkSigCha : 1;
  vbittype WkCarCha : 1;
  vbittype WkSigCC : 1;
  vbittype WkSigCC2 : 1;
  vbittype WkKeyStart : 1;
  vbittype unused1 : 2;
  vbittype ErrPrecDurMax : 1;
  vbittype ErrCnctDurMax : 1;
  vbittype ErrSoffDurMax : 1;
  vbittype ErrDcnctDurMax : 1;
  vbittype LoaErrFlag : 1;
  vbittype unused2 : 3;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
} _c_BcuSD4_msgType;
typedef struct _c_BcuSD6_msgTypeTag
{
  vbittype Cc2Vol_1 : 8;
  vbittype CcVol_1 : 8;
  vbittype DchaAH_0 : 8;
  vbittype DchaAH_1 : 8;
  vbittype ChaAh_0 : 8;
  vbittype ChaAh_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
} _c_BcuSD6_msgType;
typedef struct _c_BcuSD5_msgTypeTag
{
  vbittype UcellMaxIndex : 8;
  vbittype UcellMinIndex : 8;
  vbittype TempMaxIndex : 8;
  vbittype TempMinIndex : 8;
  vbittype TiBatOff : 8;
  vbittype IChLim : 8;
  vbittype IDchaLim : 8;
  vbittype EEPROM_SOC : 8;
} _c_BcuSD5_msgType;
typedef struct _c_BcuTime_msgTypeTag
{
  vbittype tSecond : 8;
  vbittype tMinute : 8;
  vbittype tHour : 8;
  vbittype tDay : 8;
  vbittype tWeek : 8;
  vbittype tMonth : 8;
  vbittype tYear : 8;
  vbittype unused0 : 8;
} _c_BcuTime_msgType;
typedef struct _c_Bcu_CarCharB_msgTypeTag
{
  vbittype ChargerU_1 : 8;
  vbittype ChargerU_0 : 8;
  vbittype ChargerI_1 : 8;
  vbittype ChargerI_0 : 8;
  vbittype ErrChaCon : 1;
  vbittype ErrChrTemp : 1;
  vbittype ErrChrU : 1;
  vbittype ChrInitSt : 1;
  vbittype ChrWorkSt : 1;
  vbittype ErrChrCommunicate : 1;
  vbittype unused0 : 2;
} _c_Bcu_CarCharB_msgType;
typedef struct _c_Bcu_CarCharA_msgTypeTag
{
  vbittype ReqUCarCha_1 : 8;
  vbittype ReqUCarCha_0 : 8;
  vbittype ReqICarCha_1 : 8;
  vbittype ReqICarCha_0 : 8;
  vbittype ChargerSt : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
} _c_Bcu_CarCharA_msgType;
typedef struct _c_VcuToBms_msgTypeTag
{
  vbittype StartEn : 1;
  vbittype unused0 : 7;
} _c_VcuToBms_msgType;
typedef struct _c_BmsToVcu_E_msgTypeTag
{
  vbittype UcellMax1_0 : 8;
  vbittype UcellMax1_1 : 8;
  vbittype UcellMaxNo : 8;
  vbittype UcellMin1_0 : 8;
  vbittype UcellMin1_1 : 8;
  vbittype UcellMinNo : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
} _c_BmsToVcu_E_msgType;
typedef struct _c_BmsToVcu_D_msgTypeTag
{
  vbittype ChaConSt : 2;
  vbittype unused0 : 2;
  vbittype PosRlySt : 1;
  vbittype ChaRlySt : 1;
  vbittype NegRlySt : 1;
  vbittype PreRlySt : 1;
  vbittype HeatManageSt : 3;
  vbittype unused1 : 5;
  vbittype WorkSt : 3;
  vbittype unused2 : 5;
  vbittype ChaLeftTime_0 : 8;
  vbittype ChaLeftTime_1 : 8;
  vbittype BmsSoftNO : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
} _c_BmsToVcu_D_msgType;
typedef struct _c_BmsToVcu_C_msgTypeTag
{
  vbittype Upack1_0 : 8;
  vbittype Upack1_1 : 8;
  vbittype Ipack1_0 : 8;
  vbittype Ipack1_1 : 8;
  vbittype SOC1 : 8;
  vbittype TempMax1 : 8;
  vbittype TempMin1 : 8;
  vbittype AvgTemp : 8;
} _c_BmsToVcu_C_msgType;
typedef struct _c_BmsTxVcu_B_msgTypeTag
{
  vbittype IDchaLim1_0 : 8;
  vbittype IDchaLim1_1 : 8;
  vbittype IChaLim_0 : 8;
  vbittype IChaLim_1 : 8;
  vbittype GBChaTimes_0 : 8;
  vbittype GBChaTimes_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
} _c_BmsTxVcu_B_msgType;
typedef struct _c_BcuToVcu_A_msgTypeTag
{
  vbittype RptIChaMax : 1;
  vbittype RptIDchaMax : 1;
  vbittype RptUPackMax : 1;
  vbittype RptUPackMin : 1;
  vbittype RptIso : 1;
  vbittype RptSOCMin : 1;
  vbittype RptUcellMin : 1;
  vbittype RptUcellMax : 1;
  vbittype WarnTempMin1 : 1;
  vbittype RptTempMax : 1;
  vbittype ErrCellBal : 1;
  vbittype ErrRepairsSwitch : 1;
  vbittype ErrTempSensor : 1;
  vbittype ErrLEM : 1;
  vbittype ErrUSensor : 1;
  vbittype unused0 : 1;
  vbittype WarnIChaMax : 1;
  vbittype WarnIDchaMax : 1;
  vbittype WarnUPackMax1 : 1;
  vbittype WarnUPackMin1 : 1;
  vbittype WarnIso1 : 1;
  vbittype WarnSOCMin : 1;
  vbittype WarnUcellMin1 : 1;
  vbittype WarnUcellMax1 : 1;
  vbittype ErrTempMin1 : 1;
  vbittype WarnTempMax1 : 1;
  vbittype unused1 : 6;
  vbittype ErrIChaMax : 1;
  vbittype ErrIDchaMax : 1;
  vbittype ErrUPackMax1 : 1;
  vbittype ErrUPackMin1 : 1;
  vbittype unused2 : 1;
  vbittype ErrSOCMin : 1;
  vbittype ErrUcellMin : 1;
  vbittype ErrUcellMax : 1;
  vbittype ErrTempMax1 : 1;
  vbittype ErrCharge : 1;
  vbittype ErrIso1 : 1;
  vbittype ErrPosNegRly : 1;
  vbittype ErrPreRly : 1;
  vbittype ErrInterCom : 1;
  vbittype unused3 : 2;
  vbittype RptFaultTotal : 4;
  vbittype WarnFaultTotal : 4;
  vbittype ErrFaultTotal : 4;
  vbittype unused4 : 4;
} _c_BcuToVcu_A_msgType;
typedef struct _c_Mc33BData02_msgTypeTag
{
  vbittype Ucell68_0 : 8;
  vbittype Ucell68_1 : 8;
  vbittype Ucell69_0 : 8;
  vbittype Ucell69_1 : 8;
  vbittype Ucell70_0 : 8;
  vbittype Ucell70_1 : 8;
  vbittype Ucell71_0 : 8;
  vbittype Ucell71_1 : 8;
} _c_Mc33BData02_msgType;
typedef struct _c_Mc60AData15_msgTypeTag
{
  vbittype Mc60ATemp1 : 8;
  vbittype Mc60ATemp2 : 8;
  vbittype Mc60ATemp3 : 8;
  vbittype Mc60ATemp4 : 8;
} _c_Mc60AData15_msgType;
typedef struct _c_Mc33BData01_msgTypeTag
{
  vbittype Ucell64_0 : 8;
  vbittype Ucell64_1 : 8;
  vbittype Ucell65_0 : 8;
  vbittype Ucell65_1 : 8;
  vbittype Ucell66_0 : 8;
  vbittype Ucell66_1 : 8;
  vbittype Ucell67_0 : 8;
  vbittype Ucell67_1 : 8;
} _c_Mc33BData01_msgType;
typedef struct _c_Mc33BData00_msgTypeTag
{
  vbittype Ucell60_0 : 8;
  vbittype Ucell60_1 : 8;
  vbittype Ucell61_0 : 8;
  vbittype Ucell61_1 : 8;
  vbittype Ucell62_0 : 8;
  vbittype Ucell62_1 : 8;
  vbittype Ucell63_0 : 8;
  vbittype Ucell63_1 : 8;
} _c_Mc33BData00_msgType;
typedef struct _c_Mc33BData15_msgTypeTag
{
  vbittype Mc33BTemp1 : 8;
  vbittype Mc33BTemp2 : 8;
  vbittype Mc33BTemp3 : 8;
  vbittype Mc33BTemp4 : 8;
} _c_Mc33BData15_msgType;
typedef struct _c_Mc60AData02_msgTypeTag
{
  vbittype Ucell08_0 : 8;
  vbittype Ucell08_1 : 8;
  vbittype Ucell09_0 : 8;
  vbittype Ucell09_1 : 8;
  vbittype Ucell10_0 : 8;
  vbittype Ucell10_1 : 8;
  vbittype Ucell11_0 : 8;
  vbittype Ucell11_1 : 8;
} _c_Mc60AData02_msgType;
typedef struct _c_Mc60AData01_msgTypeTag
{
  vbittype Ucell04_0 : 8;
  vbittype Ucell04_1 : 8;
  vbittype Ucell05_0 : 8;
  vbittype Ucell05_1 : 8;
  vbittype Ucell06_0 : 8;
  vbittype Ucell06_1 : 8;
  vbittype Ucell07_0 : 8;
  vbittype Ucell07_1 : 8;
} _c_Mc60AData01_msgType;
typedef struct _c_Mc60AData00_msgTypeTag
{
  vbittype Ucell00_0 : 8;
  vbittype Ucell00_1 : 8;
  vbittype Ucell01_0 : 8;
  vbittype Ucell01_1 : 8;
  vbittype Ucell02_0 : 8;
  vbittype Ucell02_1 : 8;
  vbittype Ucell03_0 : 8;
  vbittype Ucell03_1 : 8;
} _c_Mc60AData00_msgType;
typedef struct _c_Mc33BBalState_0_msgTypeTag
{
  vbittype Mc33BStatLtc1_0 : 8;
  vbittype Mc33BStatLtc1_1 : 8;
  vbittype Mc33BStatLtc2_0 : 8;
  vbittype Mc33BStatLtc2_1 : 8;
  vbittype Mc33BStatLtc3_0 : 8;
  vbittype Mc33BStatLtc3_1 : 8;
} _c_Mc33BBalState_0_msgType;
typedef struct _c_Mc60ABalState_0_msgTypeTag
{
  vbittype Mc60AStatLtc1_0 : 8;
  vbittype Mc60AStatLtc1_1 : 8;
  vbittype Mc60AStatLtc2_0 : 8;
  vbittype Mc60AStatLtc2_1 : 8;
  vbittype Mc60AStatLtc3_0 : 8;
  vbittype Mc60AStatLtc3_1 : 8;
  vbittype Mc60AStatLtc4_0 : 8;
  vbittype Mc60AStatLtc4_1 : 8;
} _c_Mc60ABalState_0_msgType;
typedef struct _c_HcuData0_msgTypeTag
{
  vbittype HV_Uact1_0 : 8;
  vbittype HV_Uact1_1 : 8;
  vbittype HV_Uact2_0 : 8;
  vbittype HV_Uact2_1 : 8;
  vbittype Ipack_1_0 : 8;
  vbittype Ipack_1_1 : 8;
  vbittype HcuSt : 8;
} _c_HcuData0_msgType;
typedef struct _c_McInit_msgTypeTag
{
  vbittype McInit_Cmd : 8;
  vbittype McInit_McNo : 8;
  vbittype McInit_Data1 : 8;
  vbittype McInit_Data2 : 8;
  vbittype McInit_Data3 : 8;
  vbittype McInit_Data4 : 8;
  vbittype McInit_Data5 : 8;
  vbittype McInit_Data6 : 8;
} _c_McInit_msgType;
typedef struct _c_BcuInit_msgTypeTag
{
  vbittype BcuInit_Cmd : 8;
  vbittype BcuInit_McNo : 8;
  vbittype BcuInit_D1 : 8;
  vbittype BcuInit_D2 : 8;
  vbittype BcuInit_D3 : 8;
  vbittype BcuInit_D4 : 8;
  vbittype BcuInit_D5 : 8;
  vbittype BcuInit_D6 : 8;
} _c_BcuInit_msgType;
typedef struct _c_RtcTxMulReq_msgTypeTag
{
  vbittype RtcTxMulReqCmd : 8;
  vbittype RtcTxMulReqByteSum : 8;
  vbittype unused0 : 8;
  vbittype RtcTxMulReqPackSum : 8;
  vbittype unused1 : 8;
  vbittype RtcTxMulReqPGN_0 : 8;
  vbittype RtcTxMulReqPGN_1 : 8;
  vbittype RtcTxMulReqPGN_2 : 8;
} _c_RtcTxMulReq_msgType;
typedef struct _c_RtcRxMulData_msgTypeTag
{
  vbittype RtcRxMulNo : 8;
  vbittype RtcRxMulD1 : 8;
  vbittype RtcRxMulD2 : 8;
  vbittype RtcRxMulD3 : 8;
  vbittype RtcRxMulD4 : 8;
  vbittype RtcRxMulD5 : 8;
  vbittype RtcRxMulD6 : 8;
  vbittype RtcRxMulD7 : 8;
} _c_RtcRxMulData_msgType;
typedef struct _c_RtcRxMulReq_msgTypeTag
{
  vbittype RtcRxMulReqCmd : 8;
  vbittype RtcRxMulByteSum_0 : 8;
  vbittype RtcRxMulByteSum_1 : 8;
  vbittype RtcRxMulPackSum : 8;
  vbittype RtcTxMulReqD4Sig : 8;
  vbittype RtcRxMulReqPGN_0 : 8;
  vbittype RtcRxMulReqPGN_1 : 8;
  vbittype RtcRxMulReqPGN_2 : 8;
} _c_RtcRxMulReq_msgType;
typedef struct _c_RtcTxMsg_msgTypeTag
{
  vbittype RtcTxD0 : 8;
  vbittype RtcTxD1 : 8;
  vbittype RtcTxD2 : 8;
  vbittype RtcTxD3 : 8;
  vbittype RtcTxD4 : 8;
  vbittype RtcTxD5 : 8;
  vbittype RtcTxD6 : 8;
  vbittype RtcTxCmd : 8;
} _c_RtcTxMsg_msgType;
typedef struct _c_RtcRxMsg_msgTypeTag
{
  vbittype RtcRxD0 : 8;
  vbittype RtcRxD1 : 8;
  vbittype RtcRxD2 : 8;
  vbittype RtcRxD3 : 8;
  vbittype RtcRxD4 : 8;
  vbittype RtcRxD5 : 8;
  vbittype RtcRxD6 : 8;
  vbittype RtcRxCmd : 8;
} _c_RtcRxMsg_msgType;
typedef struct _c_RtcTime_msgTypeTag
{
  vbittype RtcSec : 8;
  vbittype RtcMin : 8;
  vbittype RtcHour : 8;
  vbittype RtcDay : 8;
  vbittype RtcWeek : 8;
  vbittype RtcMonth : 8;
  vbittype RtcYear : 8;
} _c_RtcTime_msgType;
typedef struct _c_RtcIo_msgTypeTag
{
  vbittype Cc2Vol : 8;
  vbittype CcPwmDt : 8;
  vbittype CcVol : 8;
  vbittype GprsVol : 8;
  vbittype PwrVol : 8;
  vbittype RtcSt : 8;
} _c_RtcIo_msgType;
typedef struct _c_HcuData3_msgTypeTag
{
  vbittype HV_Uact2_2_0 : 8;
  vbittype HV_Uact2_2_1 : 8;
  vbittype HV_Uact2_3_0 : 8;
  vbittype HV_Uact2_3_1 : 8;
  vbittype HV_Uact2_4_0 : 8;
  vbittype HV_Uact2_4_1 : 8;
  vbittype HV_Uact2_5_0 : 8;
  vbittype HV_Uact2_5_1 : 8;
} _c_HcuData3_msgType;
typedef struct _c_BcuBalCmdMc33B_0_msgTypeTag
{
  vbittype Mc33BCtrlLtc1_0 : 8;
  vbittype Mc33BCtrlLtc1_1 : 8;
  vbittype Mc33BCtrlLtc2_0 : 8;
  vbittype Mc33BCtrlLtc2_1 : 8;
  vbittype Mc33BCtrlLtc3_0 : 8;
  vbittype Mc33BCtrlLtc3_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
} _c_BcuBalCmdMc33B_0_msgType;
typedef struct _c_BcuBalCmdMc60A_0_msgTypeTag
{
  vbittype Mc60ACtrlLtc1_0 : 8;
  vbittype Mc60ACtrlLtc1_1 : 8;
  vbittype Mc60ACtrlLtc2_0 : 8;
  vbittype Mc60ACtrlLtc2_1 : 8;
  vbittype Mc60ACtrlLtc3_0 : 8;
  vbittype Mc60ACtrlLtc3_1 : 8;
  vbittype Mc60ACtrlLtc4_0 : 8;
  vbittype Mc60ACtrlLtc4_1 : 8;
} _c_BcuBalCmdMc60A_0_msgType;
typedef struct _c_HcuData1_msgTypeTag
{
  vbittype IsoRst_0 : 8;
  vbittype IsoRst_1 : 8;
  vbittype IsoHvFlg : 8;
} _c_HcuData1_msgType;
typedef struct _c_BcuSyc100msMsg_msgTypeTag
{
  vbittype SycD0 : 8;
  vbittype SycD1 : 8;
  vbittype SycD2 : 8;
  vbittype SycD3 : 8;
  vbittype SycD4_0 : 8;
  vbittype SycD4_1 : 8;
  vbittype SycD4_2 : 8;
  vbittype SycD4_3 : 8;
} _c_BcuSyc100msMsg_msgType;
typedef struct _c_UdsInterTx_msgTypeTag
{
  vbittype UdsTxCmd : 8;
  vbittype UdsTxD1 : 8;
  vbittype UdsTxD2 : 8;
  vbittype UdsTxD3 : 8;
  vbittype UdsTxD4 : 8;
  vbittype UdsTxD5 : 8;
  vbittype UdsTxD6 : 8;
  vbittype UdsTxD7 : 8;
} _c_UdsInterTx_msgType;
typedef struct _c_UdsInterRx_msgTypeTag
{
  vbittype UdsRxCmd : 8;
  vbittype UdsRxD1 : 8;
  vbittype UdsRxD2 : 8;
  vbittype UdsRxD3 : 8;
  vbittype UdsRxD4 : 8;
  vbittype UdsRxD5 : 8;
  vbittype UdsRxD6 : 8;
  vbittype UdsRxD7 : 8;
} _c_UdsInterRx_msgType;
typedef struct _c_BcuCHAInfo2_msgTypeTag
{
  vbittype CellVolDiff_0 : 8;
  vbittype CellVolDiff_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
} _c_BcuCHAInfo2_msgType;
typedef struct _c_BcuCHAInfo1_msgTypeTag
{
  vbittype MaxCellV_0 : 8;
  vbittype MaxCellV_1 : 8;
  vbittype MinCellV_0 : 8;
  vbittype MinCellV_1 : 8;
  vbittype MaxCellVolNo : 8;
  vbittype MinCellVolNo : 8;
  vbittype AveCellVol_0 : 8;
  vbittype AveCellVol_1 : 8;
} _c_BcuCHAInfo1_msgType;
typedef struct _c_Mc33BData05_msgTypeTag
{
  vbittype Ucell80_0 : 8;
  vbittype Ucell80_1 : 8;
  vbittype Ucell81_0 : 8;
  vbittype Ucell81_1 : 8;
  vbittype Ucell82_0 : 8;
  vbittype Ucell82_1 : 8;
  vbittype Ucell83_0 : 8;
  vbittype Ucell83_1 : 8;
} _c_Mc33BData05_msgType;
typedef struct _c_Mc33BData04_msgTypeTag
{
  vbittype Ucell76_0 : 8;
  vbittype Ucell76_1 : 8;
  vbittype Ucell77_0 : 8;
  vbittype Ucell77_1 : 8;
  vbittype Ucell78_0 : 8;
  vbittype Ucell78_1 : 8;
  vbittype Ucell79_0 : 8;
  vbittype Ucell79_1 : 8;
} _c_Mc33BData04_msgType;
typedef struct _c_Mc33BData03_msgTypeTag
{
  vbittype Ucell72_0 : 8;
  vbittype Ucell72_1 : 8;
  vbittype Ucell73_0 : 8;
  vbittype Ucell73_1 : 8;
  vbittype Ucell74_0 : 8;
  vbittype Ucell74_1 : 8;
  vbittype Ucell75_0 : 8;
  vbittype Ucell75_1 : 8;
} _c_Mc33BData03_msgType;
typedef struct _c_Mc60AData03_msgTypeTag
{
  vbittype Ucell12_0 : 8;
  vbittype Ucell12_1 : 8;
  vbittype Ucell13_0 : 8;
  vbittype Ucell13_1 : 8;
  vbittype Ucell14_0 : 8;
  vbittype Ucell14_1 : 8;
  vbittype Ucell15_0 : 8;
  vbittype Ucell15_1 : 8;
} _c_Mc60AData03_msgType;
typedef struct _c_Mc60AData04_msgTypeTag
{
  vbittype Ucell16_0 : 8;
  vbittype Ucell16_1 : 8;
  vbittype Ucell17_0 : 8;
  vbittype Ucell17_1 : 8;
  vbittype Ucell18_0 : 8;
  vbittype Ucell18_1 : 8;
  vbittype Ucell19_0 : 8;
  vbittype Ucell19_1 : 8;
} _c_Mc60AData04_msgType;
typedef struct _c_Mc60AData05_msgTypeTag
{
  vbittype Ucell20_0 : 8;
  vbittype Ucell20_1 : 8;
  vbittype Ucell21_0 : 8;
  vbittype Ucell21_1 : 8;
  vbittype Ucell22_0 : 8;
  vbittype Ucell22_1 : 8;
  vbittype Ucell23_0 : 8;
  vbittype Ucell23_1 : 8;
} _c_Mc60AData05_msgType;
typedef struct _c_Mc60ABalState_1_msgTypeTag
{
  vbittype Mc60AStatLtc5_0 : 8;
  vbittype Mc60AStatLtc5_1 : 8;
} _c_Mc60ABalState_1_msgType;
typedef struct _c_Mc60AData06_msgTypeTag
{
  vbittype Ucell24_0 : 8;
  vbittype Ucell24_1 : 8;
  vbittype Ucell25_0 : 8;
  vbittype Ucell25_1 : 8;
  vbittype Ucell26_0 : 8;
  vbittype Ucell26_1 : 8;
  vbittype Ucell27_0 : 8;
  vbittype Ucell27_1 : 8;
} _c_Mc60AData06_msgType;
typedef struct _c_Mc60AData07_msgTypeTag
{
  vbittype Ucell28_0 : 8;
  vbittype Ucell28_1 : 8;
  vbittype Ucell29_0 : 8;
  vbittype Ucell29_1 : 8;
  vbittype Ucell30_0 : 8;
  vbittype Ucell30_1 : 8;
  vbittype Ucell31_0 : 8;
  vbittype Ucell31_1 : 8;
} _c_Mc60AData07_msgType;
typedef struct _c_Mc60AData08_msgTypeTag
{
  vbittype Ucell32_0 : 8;
  vbittype Ucell32_1 : 8;
  vbittype Ucell33_0 : 8;
  vbittype Ucell33_1 : 8;
  vbittype Ucell34_0 : 8;
  vbittype Ucell34_1 : 8;
  vbittype Ucell35_0 : 8;
  vbittype Ucell35_1 : 8;
} _c_Mc60AData08_msgType;
typedef struct _c_Mc33BData06_msgTypeTag
{
  vbittype Ucell84_0 : 8;
  vbittype Ucell84_1 : 8;
  vbittype Ucell85_0 : 8;
  vbittype Ucell85_1 : 8;
  vbittype Ucell86_0 : 8;
  vbittype Ucell86_1 : 8;
  vbittype Ucell87_0 : 8;
  vbittype Ucell87_1 : 8;
} _c_Mc33BData06_msgType;
typedef struct _c_Mc33BData07_msgTypeTag
{
  vbittype Ucell88_0 : 8;
  vbittype Ucell88_1 : 8;
  vbittype Ucell89_0 : 8;
  vbittype Ucell89_1 : 8;
  vbittype Ucell90_0 : 8;
  vbittype Ucell90_1 : 8;
  vbittype Ucell91_0 : 8;
  vbittype Ucell91_1 : 8;
} _c_Mc33BData07_msgType;
typedef struct _c_Mc33BData08_msgTypeTag
{
  vbittype Ucell92_0 : 8;
  vbittype Ucell92_1 : 8;
} _c_Mc33BData08_msgType;
typedef struct _c_Mc60AState_msgTypeTag
{
  vbittype Mc60AAveCellV_0 : 8;
  vbittype Mc60AAveCellV_1 : 8;
  vbittype Mc60ATxErrCnt : 8;
  vbittype Mc60ARxErrCnt : 8;
  vbittype Mc60ACanResets : 8;
  vbittype Mc60ACanErrDirect : 8;
  vbittype Mc60AErrCode : 4;
  vbittype Mc60ASt : 4;
  vbittype Mc60AErrCounter : 8;
} _c_Mc60AState_msgType;
typedef struct _c_Mc33BState_msgTypeTag
{
  vbittype Mc33BAveCellV_0 : 8;
  vbittype Mc33BAveCellV_1 : 8;
  vbittype Mc33BTxErrCnt : 8;
  vbittype Mc33BRxErrCnt : 8;
  vbittype Mc33BCanResets : 8;
  vbittype Mc33BCanErrDirect : 8;
  vbittype Mc33BErrCode : 4;
  vbittype Mc33BSt : 4;
  vbittype Mc33BErrCounter : 8;
} _c_Mc33BState_msgType;
typedef struct _c_BcuBalCmdMc60A_1_msgTypeTag
{
  vbittype Mc60ACtrlLtc5_0 : 8;
  vbittype Mc60ACtrlLtc5_1 : 8;
  vbittype unused0 : 8;
  vbittype unused1 : 8;
  vbittype unused2 : 8;
  vbittype unused3 : 8;
  vbittype unused4 : 8;
  vbittype unused5 : 8;
} _c_BcuBalCmdMc60A_1_msgType;
typedef struct _c_Mc60AData14_msgTypeTag
{
  vbittype Ucell56_0 : 8;
  vbittype Ucell56_1 : 8;
  vbittype Ucell57_0 : 8;
  vbittype Ucell57_1 : 8;
  vbittype Ucell58_0 : 8;
  vbittype Ucell58_1 : 8;
  vbittype Ucell59_0 : 8;
  vbittype Ucell59_1 : 8;
} _c_Mc60AData14_msgType;
typedef struct _c_Mc60AData13_msgTypeTag
{
  vbittype Ucell52_0 : 8;
  vbittype Ucell52_1 : 8;
  vbittype Ucell53_0 : 8;
  vbittype Ucell53_1 : 8;
  vbittype Ucell54_0 : 8;
  vbittype Ucell54_1 : 8;
  vbittype Ucell55_0 : 8;
  vbittype Ucell55_1 : 8;
} _c_Mc60AData13_msgType;
typedef struct _c_Mc60AData12_msgTypeTag
{
  vbittype Ucell48_0 : 8;
  vbittype Ucell48_1 : 8;
  vbittype Ucell49_0 : 8;
  vbittype Ucell49_1 : 8;
  vbittype Ucell50_0 : 8;
  vbittype Ucell50_1 : 8;
  vbittype Ucell51_0 : 8;
  vbittype Ucell51_1 : 8;
} _c_Mc60AData12_msgType;
typedef struct _c_Mc60AData11_msgTypeTag
{
  vbittype Ucell44_0 : 8;
  vbittype Ucell44_1 : 8;
  vbittype Ucell45_0 : 8;
  vbittype Ucell45_1 : 8;
  vbittype Ucell46_0 : 8;
  vbittype Ucell46_1 : 8;
  vbittype Ucell47_0 : 8;
  vbittype Ucell47_1 : 8;
} _c_Mc60AData11_msgType;
typedef struct _c_Mc60AData10_msgTypeTag
{
  vbittype Ucell40_0 : 8;
  vbittype Ucell40_1 : 8;
  vbittype Ucell41_0 : 8;
  vbittype Ucell41_1 : 8;
  vbittype Ucell42_0 : 8;
  vbittype Ucell42_1 : 8;
  vbittype Ucell43_0 : 8;
  vbittype Ucell43_1 : 8;
} _c_Mc60AData10_msgType;
typedef struct _c_Mc60AData09_msgTypeTag
{
  vbittype Ucell36_0 : 8;
  vbittype Ucell36_1 : 8;
  vbittype Ucell37_0 : 8;
  vbittype Ucell37_1 : 8;
  vbittype Ucell38_0 : 8;
  vbittype Ucell38_1 : 8;
  vbittype Ucell39_0 : 8;
  vbittype Ucell39_1 : 8;
} _c_Mc60AData09_msgType;


/* -----------------------------------------------------------------------------
    &&&~ Signal value names
 ----------------------------------------------------------------------------- */



/* -----------------------------------------------------------------------------
    &&&~ Message Unions
 ----------------------------------------------------------------------------- */

typedef union _c_TxXCP_bufTag
{
  vuint8 _c[8];
  _c_TxXCP_msgType TxXCP;
} _c_TxXCP_buf;
typedef union _c_RxXCP_bufTag
{
  vuint8 _c[8];
  _c_RxXCP_msgType RxXCP;
} _c_RxXCP_buf;
typedef union _c_UdsRx_bufTag
{
  vuint8 _c[8];
  _c_UdsRx_msgType UdsRx;
} _c_UdsRx_buf;
typedef union _c_UdsTx_bufTag
{
  vuint8 _c[8];
  _c_UdsTx_msgType UdsTx;
} _c_UdsTx_buf;
typedef union _c_BcuSD1_bufTag
{
  vuint8 _c[8];
  _c_BcuSD1_msgType BcuSD1;
} _c_BcuSD1_buf;
typedef union _c_BcuSD2_bufTag
{
  vuint8 _c[8];
  _c_BcuSD2_msgType BcuSD2;
} _c_BcuSD2_buf;
typedef union _c_BcuSD3_bufTag
{
  vuint8 _c[8];
  _c_BcuSD3_msgType BcuSD3;
} _c_BcuSD3_buf;
typedef union _c_BcuSD4_bufTag
{
  vuint8 _c[8];
  _c_BcuSD4_msgType BcuSD4;
} _c_BcuSD4_buf;
typedef union _c_BcuSD6_bufTag
{
  vuint8 _c[8];
  _c_BcuSD6_msgType BcuSD6;
} _c_BcuSD6_buf;
typedef union _c_BcuSD5_bufTag
{
  vuint8 _c[8];
  _c_BcuSD5_msgType BcuSD5;
} _c_BcuSD5_buf;
typedef union _c_BcuTime_bufTag
{
  vuint8 _c[8];
  _c_BcuTime_msgType BcuTime;
} _c_BcuTime_buf;
typedef union _c_Bcu_CarCharB_bufTag
{
  vuint8 _c[5];
  _c_Bcu_CarCharB_msgType Bcu_CarCharB;
} _c_Bcu_CarCharB_buf;
typedef union _c_Bcu_CarCharA_bufTag
{
  vuint8 _c[8];
  _c_Bcu_CarCharA_msgType Bcu_CarCharA;
} _c_Bcu_CarCharA_buf;
typedef union _c_VcuToBms_bufTag
{
  vuint8 _c[1];
  _c_VcuToBms_msgType VcuToBms;
} _c_VcuToBms_buf;
typedef union _c_BmsToVcu_E_bufTag
{
  vuint8 _c[8];
  _c_BmsToVcu_E_msgType BmsToVcu_E;
} _c_BmsToVcu_E_buf;
typedef union _c_BmsToVcu_D_bufTag
{
  vuint8 _c[8];
  _c_BmsToVcu_D_msgType BmsToVcu_D;
} _c_BmsToVcu_D_buf;
typedef union _c_BmsToVcu_C_bufTag
{
  vuint8 _c[8];
  _c_BmsToVcu_C_msgType BmsToVcu_C;
} _c_BmsToVcu_C_buf;
typedef union _c_BmsTxVcu_B_bufTag
{
  vuint8 _c[8];
  _c_BmsTxVcu_B_msgType BmsTxVcu_B;
} _c_BmsTxVcu_B_buf;
typedef union _c_BcuToVcu_A_bufTag
{
  vuint8 _c[8];
  _c_BcuToVcu_A_msgType BcuToVcu_A;
} _c_BcuToVcu_A_buf;
typedef union _c_Mc33BData02_bufTag
{
  vuint8 _c[8];
  _c_Mc33BData02_msgType Mc33BData02;
} _c_Mc33BData02_buf;
typedef union _c_Mc60AData15_bufTag
{
  vuint8 _c[4];
  _c_Mc60AData15_msgType Mc60AData15;
} _c_Mc60AData15_buf;
typedef union _c_Mc33BData01_bufTag
{
  vuint8 _c[8];
  _c_Mc33BData01_msgType Mc33BData01;
} _c_Mc33BData01_buf;
typedef union _c_Mc33BData00_bufTag
{
  vuint8 _c[8];
  _c_Mc33BData00_msgType Mc33BData00;
} _c_Mc33BData00_buf;
typedef union _c_Mc33BData15_bufTag
{
  vuint8 _c[4];
  _c_Mc33BData15_msgType Mc33BData15;
} _c_Mc33BData15_buf;
typedef union _c_Mc60AData02_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData02_msgType Mc60AData02;
} _c_Mc60AData02_buf;
typedef union _c_Mc60AData01_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData01_msgType Mc60AData01;
} _c_Mc60AData01_buf;
typedef union _c_Mc60AData00_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData00_msgType Mc60AData00;
} _c_Mc60AData00_buf;
typedef union _c_Mc33BBalState_0_bufTag
{
  vuint8 _c[6];
  _c_Mc33BBalState_0_msgType Mc33BBalState_0;
} _c_Mc33BBalState_0_buf;
typedef union _c_Mc60ABalState_0_bufTag
{
  vuint8 _c[8];
  _c_Mc60ABalState_0_msgType Mc60ABalState_0;
} _c_Mc60ABalState_0_buf;
typedef union _c_HcuData0_bufTag
{
  vuint8 _c[7];
  _c_HcuData0_msgType HcuData0;
} _c_HcuData0_buf;
typedef union _c_McInit_bufTag
{
  vuint8 _c[8];
  _c_McInit_msgType McInit;
} _c_McInit_buf;
typedef union _c_BcuInit_bufTag
{
  vuint8 _c[8];
  _c_BcuInit_msgType BcuInit;
} _c_BcuInit_buf;
typedef union _c_RtcTxMulReq_bufTag
{
  vuint8 _c[8];
  _c_RtcTxMulReq_msgType RtcTxMulReq;
} _c_RtcTxMulReq_buf;
typedef union _c_RtcRxMulData_bufTag
{
  vuint8 _c[8];
  _c_RtcRxMulData_msgType RtcRxMulData;
} _c_RtcRxMulData_buf;
typedef union _c_RtcRxMulReq_bufTag
{
  vuint8 _c[8];
  _c_RtcRxMulReq_msgType RtcRxMulReq;
} _c_RtcRxMulReq_buf;
typedef union _c_RtcTxMsg_bufTag
{
  vuint8 _c[8];
  _c_RtcTxMsg_msgType RtcTxMsg;
} _c_RtcTxMsg_buf;
typedef union _c_RtcRxMsg_bufTag
{
  vuint8 _c[8];
  _c_RtcRxMsg_msgType RtcRxMsg;
} _c_RtcRxMsg_buf;
typedef union _c_RtcTime_bufTag
{
  vuint8 _c[7];
  _c_RtcTime_msgType RtcTime;
} _c_RtcTime_buf;
typedef union _c_RtcIo_bufTag
{
  vuint8 _c[6];
  _c_RtcIo_msgType RtcIo;
} _c_RtcIo_buf;
typedef union _c_HcuData3_bufTag
{
  vuint8 _c[8];
  _c_HcuData3_msgType HcuData3;
} _c_HcuData3_buf;
typedef union _c_BcuBalCmdMc33B_0_bufTag
{
  vuint8 _c[8];
  _c_BcuBalCmdMc33B_0_msgType BcuBalCmdMc33B_0;
} _c_BcuBalCmdMc33B_0_buf;
typedef union _c_BcuBalCmdMc60A_0_bufTag
{
  vuint8 _c[8];
  _c_BcuBalCmdMc60A_0_msgType BcuBalCmdMc60A_0;
} _c_BcuBalCmdMc60A_0_buf;
typedef union _c_HcuData1_bufTag
{
  vuint8 _c[3];
  _c_HcuData1_msgType HcuData1;
} _c_HcuData1_buf;
typedef union _c_BcuSyc100msMsg_bufTag
{
  vuint8 _c[8];
  _c_BcuSyc100msMsg_msgType BcuSyc100msMsg;
} _c_BcuSyc100msMsg_buf;
typedef union _c_UdsInterTx_bufTag
{
  vuint8 _c[8];
  _c_UdsInterTx_msgType UdsInterTx;
} _c_UdsInterTx_buf;
typedef union _c_UdsInterRx_bufTag
{
  vuint8 _c[8];
  _c_UdsInterRx_msgType UdsInterRx;
} _c_UdsInterRx_buf;
typedef union _c_BcuCHAInfo2_bufTag
{
  vuint8 _c[8];
  _c_BcuCHAInfo2_msgType BcuCHAInfo2;
} _c_BcuCHAInfo2_buf;
typedef union _c_BcuCHAInfo1_bufTag
{
  vuint8 _c[8];
  _c_BcuCHAInfo1_msgType BcuCHAInfo1;
} _c_BcuCHAInfo1_buf;
typedef union _c_Mc33BData05_bufTag
{
  vuint8 _c[8];
  _c_Mc33BData05_msgType Mc33BData05;
} _c_Mc33BData05_buf;
typedef union _c_Mc33BData04_bufTag
{
  vuint8 _c[8];
  _c_Mc33BData04_msgType Mc33BData04;
} _c_Mc33BData04_buf;
typedef union _c_Mc33BData03_bufTag
{
  vuint8 _c[8];
  _c_Mc33BData03_msgType Mc33BData03;
} _c_Mc33BData03_buf;
typedef union _c_Mc60AData03_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData03_msgType Mc60AData03;
} _c_Mc60AData03_buf;
typedef union _c_Mc60AData04_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData04_msgType Mc60AData04;
} _c_Mc60AData04_buf;
typedef union _c_Mc60AData05_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData05_msgType Mc60AData05;
} _c_Mc60AData05_buf;
typedef union _c_Mc60ABalState_1_bufTag
{
  vuint8 _c[2];
  _c_Mc60ABalState_1_msgType Mc60ABalState_1;
} _c_Mc60ABalState_1_buf;
typedef union _c_Mc60AData06_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData06_msgType Mc60AData06;
} _c_Mc60AData06_buf;
typedef union _c_Mc60AData07_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData07_msgType Mc60AData07;
} _c_Mc60AData07_buf;
typedef union _c_Mc60AData08_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData08_msgType Mc60AData08;
} _c_Mc60AData08_buf;
typedef union _c_Mc33BData06_bufTag
{
  vuint8 _c[8];
  _c_Mc33BData06_msgType Mc33BData06;
} _c_Mc33BData06_buf;
typedef union _c_Mc33BData07_bufTag
{
  vuint8 _c[8];
  _c_Mc33BData07_msgType Mc33BData07;
} _c_Mc33BData07_buf;
typedef union _c_Mc33BData08_bufTag
{
  vuint8 _c[2];
  _c_Mc33BData08_msgType Mc33BData08;
} _c_Mc33BData08_buf;
typedef union _c_Mc60AState_bufTag
{
  vuint8 _c[8];
  _c_Mc60AState_msgType Mc60AState;
} _c_Mc60AState_buf;
typedef union _c_Mc33BState_bufTag
{
  vuint8 _c[8];
  _c_Mc33BState_msgType Mc33BState;
} _c_Mc33BState_buf;
typedef union _c_BcuBalCmdMc60A_1_bufTag
{
  vuint8 _c[8];
  _c_BcuBalCmdMc60A_1_msgType BcuBalCmdMc60A_1;
} _c_BcuBalCmdMc60A_1_buf;
typedef union _c_Mc60AData14_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData14_msgType Mc60AData14;
} _c_Mc60AData14_buf;
typedef union _c_Mc60AData13_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData13_msgType Mc60AData13;
} _c_Mc60AData13_buf;
typedef union _c_Mc60AData12_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData12_msgType Mc60AData12;
} _c_Mc60AData12_buf;
typedef union _c_Mc60AData11_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData11_msgType Mc60AData11;
} _c_Mc60AData11_buf;
typedef union _c_Mc60AData10_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData10_msgType Mc60AData10;
} _c_Mc60AData10_buf;
typedef union _c_Mc60AData09_bufTag
{
  vuint8 _c[8];
  _c_Mc60AData09_msgType Mc60AData09;
} _c_Mc60AData09_buf;


/* -----------------------------------------------------------------------------
    &&&~ Message Buffers
 ----------------------------------------------------------------------------- */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_TxXCP_buf V_MEMRAM2 TxXCP;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_RxXCP_buf V_MEMRAM2 RxXCP;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_UdsRx_buf V_MEMRAM2 UdsRx;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_UdsTx_buf V_MEMRAM2 UdsTx;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuSD1_buf V_MEMRAM2 BcuSD1;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuSD2_buf V_MEMRAM2 BcuSD2;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuSD3_buf V_MEMRAM2 BcuSD3;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuSD4_buf V_MEMRAM2 BcuSD4;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuSD6_buf V_MEMRAM2 BcuSD6;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuSD5_buf V_MEMRAM2 BcuSD5;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuTime_buf V_MEMRAM2 BcuTime;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Bcu_CarCharB_buf V_MEMRAM2 Bcu_CarCharB;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Bcu_CarCharA_buf V_MEMRAM2 Bcu_CarCharA;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_VcuToBms_buf V_MEMRAM2 VcuToBms;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BmsToVcu_E_buf V_MEMRAM2 BmsToVcu_E;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BmsToVcu_D_buf V_MEMRAM2 BmsToVcu_D;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BmsToVcu_C_buf V_MEMRAM2 BmsToVcu_C;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BmsTxVcu_B_buf V_MEMRAM2 BmsTxVcu_B;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuToVcu_A_buf V_MEMRAM2 BcuToVcu_A;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData02_buf V_MEMRAM2 Mc33BData02;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData15_buf V_MEMRAM2 Mc60AData15;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData01_buf V_MEMRAM2 Mc33BData01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData00_buf V_MEMRAM2 Mc33BData00;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData15_buf V_MEMRAM2 Mc33BData15;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData02_buf V_MEMRAM2 Mc60AData02;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData01_buf V_MEMRAM2 Mc60AData01;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData00_buf V_MEMRAM2 Mc60AData00;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BBalState_0_buf V_MEMRAM2 Mc33BBalState_0;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60ABalState_0_buf V_MEMRAM2 Mc60ABalState_0;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_HcuData0_buf V_MEMRAM2 HcuData0;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_McInit_buf V_MEMRAM2 McInit;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuInit_buf V_MEMRAM2 BcuInit;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_RtcTxMulReq_buf V_MEMRAM2 RtcTxMulReq;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_RtcRxMulData_buf V_MEMRAM2 RtcRxMulData;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_RtcRxMulReq_buf V_MEMRAM2 RtcRxMulReq;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_RtcTxMsg_buf V_MEMRAM2 RtcTxMsg;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_RtcRxMsg_buf V_MEMRAM2 RtcRxMsg;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_RtcTime_buf V_MEMRAM2 RtcTime;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_RtcIo_buf V_MEMRAM2 RtcIo;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_HcuData3_buf V_MEMRAM2 HcuData3;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuBalCmdMc33B_0_buf V_MEMRAM2 BcuBalCmdMc33B_0;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuBalCmdMc60A_0_buf V_MEMRAM2 BcuBalCmdMc60A_0;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_HcuData1_buf V_MEMRAM2 HcuData1;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuSyc100msMsg_buf V_MEMRAM2 BcuSyc100msMsg;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_UdsInterTx_buf V_MEMRAM2 UdsInterTx;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_UdsInterRx_buf V_MEMRAM2 UdsInterRx;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuCHAInfo2_buf V_MEMRAM2 BcuCHAInfo2;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuCHAInfo1_buf V_MEMRAM2 BcuCHAInfo1;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData05_buf V_MEMRAM2 Mc33BData05;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData04_buf V_MEMRAM2 Mc33BData04;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData03_buf V_MEMRAM2 Mc33BData03;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData03_buf V_MEMRAM2 Mc60AData03;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData04_buf V_MEMRAM2 Mc60AData04;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData05_buf V_MEMRAM2 Mc60AData05;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60ABalState_1_buf V_MEMRAM2 Mc60ABalState_1;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData06_buf V_MEMRAM2 Mc60AData06;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData07_buf V_MEMRAM2 Mc60AData07;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData08_buf V_MEMRAM2 Mc60AData08;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData06_buf V_MEMRAM2 Mc33BData06;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData07_buf V_MEMRAM2 Mc33BData07;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BData08_buf V_MEMRAM2 Mc33BData08;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AState_buf V_MEMRAM2 Mc60AState;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc33BState_buf V_MEMRAM2 Mc33BState;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_BcuBalCmdMc60A_1_buf V_MEMRAM2 BcuBalCmdMc60A_1;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData14_buf V_MEMRAM2 Mc60AData14;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData13_buf V_MEMRAM2 Mc60AData13;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData12_buf V_MEMRAM2 Mc60AData12;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData11_buf V_MEMRAM2 Mc60AData11;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData10_buf V_MEMRAM2 Mc60AData10;
/* RAM CATEGORY 2 END */

/* RAM CATEGORY 2 START */
V_MEMRAM0 extern  V_MEMRAM1 _c_Mc60AData09_buf V_MEMRAM2 Mc60AData09;
/* RAM CATEGORY 2 END */






/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 210607152
      #error "The magic number of the generated file <D:\workspace\R1556\drv_par.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 210607152
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __DRV_PAR_H__ */
