/* file: intvect.c, automatically generated by gentricAS.exe, Version: 5.05 */
/* configuration read from: C:\OS\OS2.0\OS_CONF.OIL */
/* generation at  : Thu Apr 21 09:39:04 2011 */
/* License CBD1000119 for BEIQI FOTON MOTOR CO.,LTD., beta license (valid from 2010-08-18 until 2011-08-31) */
/* Implementation: TriCore_1767 */
/* Version of general code: 5.15a */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 5
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#include <os.h>
#include <osekext.h>



#if (osdVectorTableInRAM == 1)
#pragma section vector_init
#endif

static void osISRUnhandledException(void);


/*interrupt priority 1 is the level of TaskSwitchInterrupt, no initialization here*/

#if (osdSystemCounterNeeded)
/* ISR Category 2: osTimerInt */
#if (osdStackModel == osdSingleStackOsek)
   static void ososTimerInt_cat23a(void);
#endif /*(osdStackModel != osdSingleStackOsek)*/
#if (osdKillTaskIsrPossible || (osdSC== SC3 ) || (osdSC== SC4))
/* If this ISR might be killed, assure that the lower context is saved! */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(2) __bisr_(osdInterruptVectorTableSize) ososTimerInt_cat23(void) /* PRQA S 1503 */
#else /* (osdKillTaskIsrPossible || (osdSC== SC3 ) || (osdSC== SC4)) */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(2)  ososTimerInt_cat23(void) /* PRQA S 1503 */
#endif /* (osdKillTaskIsrPossible || (osdSC== SC3 ) || (osdSC== SC4)) */
{
#if (osdStackModel == osdSingleStackOsek)
    osuint32 pcxiraw;
    osuint32 pcxiadr;
    osuint32 * ppcxi;

#if ((STATUS_LEVEL == EXTENDED_STATUS) && (osdEnableAssertions))
    osuint32 tmp;
    __asm( "mov.d   %0, a10" : "=d"(tmp));
    /* assure that the stack pointer is unchanged, i.e. this function needs no stack */
    osSysErrAssert((tmp == 
       (osuint32)&(osCat1IsrStack[ osdCat1IsrStackSize/sizeof(osStackDataType) ])) , 
       osdErrIWWrongStackPointer);/*lint !e530 "Symbol 'tmp' not initialized", done in inline asm */
#endif /*((STATUS_LEVEL == EXTENDED_STATUS) && (osdEnableAssertions))*/

    /*switch to Cat1IsrStack on entry of nested interrupt */
    osd_mtcr(os_PSW_OFFSET, 0x00000880UL );

    /* Are we currently running on the system stack? */
    if (osIsOnSystemStack == 0)
    {
       /* No: Set the stack pointer to the current position on the system stack */
       __asm( "   mov.a  a10, %0 " :: "d"(osCurrentBasicSP): "a10" );
       /* osIsOnSystemStack is incremented/decremented in osEnter/LeaveISR() */
    }
    else
    {
       /* Yes: The processor has switched to the Cat1IsrStack, switch back to the system stack */
       /* Get the current stack pointer from the stored context */
       pcxiraw=osd_mfcr(os_PCXI_OFFSET);   /* Get PCXI value */
       pcxiadr=((pcxiraw & 0x000f0000UL) << 12) | (((pcxiraw & 0x0000ffffUL) << 6)); 
       ppcxi=(osuint32*)pcxiadr;
#if (osdKillTaskIsrPossible || (osdSC== SC3 ) || (osdSC== SC4))
       /* Is this a lower context? (In case ISR-killing is possible, 
        * we know it is a lower context because of the bisr-instruction above) */
       if((pcxiraw & 0x00400000) == 0)
#endif /* (osdKillTaskIsrPossible || (osdSC== SC3 ) || (osdSC== SC4)) */
       {
          /* Yes: take the next one, this has to be an upper context */
          os_dsync(); /* wait until the context has been written completely before reading PCXI value from there */
          pcxiraw = *ppcxi;                   /* Get the PCXI register out of the lower context */
          pcxiadr=((pcxiraw & 0x000f0000UL) << 12) | (((pcxiraw & 0x0000ffffUL) << 6)); 
          ppcxi=(osuint32*)pcxiadr;
       } 
       /* else: we are in an upper context, get SP from here */
       __asm( "   mov.a  a10, %0 " :: "d"(*(ppcxi+2)): "a10" ); /* Get SP out of the upper context */
    }
    os_dsync();
    ososTimerInt_cat23a();
}

static void ososTimerInt_cat23a(void)
{
#endif /*(osdStackModel != osdSingleStackOsek)*/
#if osdTimingProtectionUsed
   if (osTPArrivalAllowed(osdNumberOfAllTasks + osTimerInt)==osdTRUE)
   {
      osIsrStoredInfo[osIntNestingDepth].ProcTP = osTPExeSwitchTo(osdNumberOfAllTasks + osTimerInt);
      osTPSuspendTimerBlock();
#endif

      osEnterISR(osTimerInt, 2);
#if (osdKillTaskIsrPossible || (osdSC== SC3 ) || (osdSC== SC4))
      /* switch from maximum level to the level of the this ISR */
      osSetLevel(2);
#else /* (osdKillTaskIsrPossible || (osdSC== SC3 ) || (osdSC== SC4)) */
      osEnableGlobal();
#endif /* (osdKillTaskIsrPossible || (osdSC== SC3 ) || (osdSC== SC4)) */
#if ((osdSC== SC3) || (osdSC== SC4))
      if (oskIcbIsTrusted[osTimerInt] == 0)
      {
         osd_mtcr(os_PSW_OFFSET,((osd_mfcr(os_PSW_OFFSET) & 0xffffc3ff) | 0x1000));  /* enable protection */ 
      }
#endif

      osTimerIntfunc();
#if ((osdSC== SC3) || (osdSC== SC4))
      osRETI2();
#endif

      osDisableGlobal();
      osLeaveISR();

#if osdTimingProtectionUsed
      osTPExeSwitchBack(osIsrStoredInfo[osIntNestingDepth].ProcTP);
      osTPResumeTimerBlock(osIsrStoredInfo[osIntNestingDepth].ProcTP);
   } /* if (osTPArrivalAllowed()) */
#endif
}
#else

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(2) osIsrLevel2(void) /* PRQA S 1503 */
{
   osISRUnhandledException(); 
}

#endif

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(3) osIsrLevel3(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(4) osIsrLevel4(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(5) osIsrLevel5(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(6) osIsrLevel6(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(7) osIsrLevel7(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(8) osIsrLevel8(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(9) osIsrLevel9(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* ISR Category 1: Spi_Irq0func */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(10) osSpi_Irq0func_cat1(void) /* PRQA S 1503 */
{
   Spi_Irq0func();
}

/* ISR Category 1: Spi_Irq1func */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(11) osSpi_Irq1func_cat1(void) /* PRQA S 1503 */
{
   Spi_Irq1func();
}

/* ISR Category 1: Adc_Irq0func */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(12) osAdc_Irq0func_cat1(void) /* PRQA S 1503 */
{
   Adc_Irq0func();
}

/* ISR Category 1: Adc_Irq2func */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(13) osAdc_Irq2func_cat1(void) /* PRQA S 1503 */
{
   Adc_Irq2func();
}

/* ISR Category 1: Adc_Irq1func */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(14) osAdc_Irq1func_cat1(void) /* PRQA S 1503 */
{
   Adc_Irq1func();
}

/* ISR Category 1: Adc_Irq3func */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(15) osAdc_Irq3func_cat1(void) /* PRQA S 1503 */
{
   Adc_Irq3func();
}

/* ISR Category 1: Gpt_Irq1func */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(16) osGpt_Irq1func_cat1(void) /* PRQA S 1503 */
{
   Gpt_Irq1func();
}

/* ISR Category 1: Gpt_Irq2func */
/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt(17) osGpt_Irq2func_cat1(void) /* PRQA S 1503 */
{
   Gpt_Irq2func();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(18) osIsrLevel18(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(19) osIsrLevel19(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(20) osIsrLevel20(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(21) osIsrLevel21(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(22) osIsrLevel22(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(23) osIsrLevel23(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(24) osIsrLevel24(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(25) osIsrLevel25(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(26) osIsrLevel26(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(27) osIsrLevel27(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(28) osIsrLevel28(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(29) osIsrLevel29(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(30) osIsrLevel30(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(31) osIsrLevel31(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(32) osIsrLevel32(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(33) osIsrLevel33(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(34) osIsrLevel34(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(37) osIsrLevel37(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(38) osIsrLevel38(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(39) osIsrLevel39(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(40) osIsrLevel40(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(41) osIsrLevel41(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(42) osIsrLevel42(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(43) osIsrLevel43(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(44) osIsrLevel44(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(45) osIsrLevel45(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(46) osIsrLevel46(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(47) osIsrLevel47(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(48) osIsrLevel48(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(49) osIsrLevel49(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(50) osIsrLevel50(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(51) osIsrLevel51(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(52) osIsrLevel52(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(53) osIsrLevel53(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(54) osIsrLevel54(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(55) osIsrLevel55(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(56) osIsrLevel56(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(57) osIsrLevel57(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(58) osIsrLevel58(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(59) osIsrLevel59(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(60) osIsrLevel60(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(61) osIsrLevel61(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(62) osIsrLevel62(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(63) osIsrLevel63(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(64) osIsrLevel64(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(65) osIsrLevel65(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(66) osIsrLevel66(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(67) osIsrLevel67(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(68) osIsrLevel68(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(69) osIsrLevel69(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(70) osIsrLevel70(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(71) osIsrLevel71(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(72) osIsrLevel72(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(73) osIsrLevel73(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(74) osIsrLevel74(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(75) osIsrLevel75(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(76) osIsrLevel76(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(77) osIsrLevel77(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(78) osIsrLevel78(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(79) osIsrLevel79(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(80) osIsrLevel80(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(81) osIsrLevel81(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(82) osIsrLevel82(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(83) osIsrLevel83(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(84) osIsrLevel84(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(85) osIsrLevel85(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(86) osIsrLevel86(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(87) osIsrLevel87(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(88) osIsrLevel88(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(89) osIsrLevel89(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(90) osIsrLevel90(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(91) osIsrLevel91(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(92) osIsrLevel92(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(93) osIsrLevel93(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(94) osIsrLevel94(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(95) osIsrLevel95(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(96) osIsrLevel96(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(97) osIsrLevel97(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(98) osIsrLevel98(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(99) osIsrLevel99(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(100) osIsrLevel100(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(101) osIsrLevel101(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(102) osIsrLevel102(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(103) osIsrLevel103(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(104) osIsrLevel104(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(105) osIsrLevel105(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(106) osIsrLevel106(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(107) osIsrLevel107(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(108) osIsrLevel108(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(109) osIsrLevel109(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(110) osIsrLevel110(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(111) osIsrLevel111(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(112) osIsrLevel112(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(113) osIsrLevel113(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(114) osIsrLevel114(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(115) osIsrLevel115(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(116) osIsrLevel116(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(117) osIsrLevel117(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(118) osIsrLevel118(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(119) osIsrLevel119(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(120) osIsrLevel120(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(121) osIsrLevel121(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(122) osIsrLevel122(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(123) osIsrLevel123(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(124) osIsrLevel124(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(125) osIsrLevel125(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(126) osIsrLevel126(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(127) osIsrLevel127(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(128) osIsrLevel128(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(129) osIsrLevel129(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(130) osIsrLevel130(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(131) osIsrLevel131(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(132) osIsrLevel132(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(133) osIsrLevel133(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(134) osIsrLevel134(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(135) osIsrLevel135(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(136) osIsrLevel136(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(137) osIsrLevel137(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(138) osIsrLevel138(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(139) osIsrLevel139(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(140) osIsrLevel140(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(141) osIsrLevel141(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(142) osIsrLevel142(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(143) osIsrLevel143(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(144) osIsrLevel144(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(145) osIsrLevel145(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(146) osIsrLevel146(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(147) osIsrLevel147(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(148) osIsrLevel148(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(149) osIsrLevel149(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(150) osIsrLevel150(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(151) osIsrLevel151(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(152) osIsrLevel152(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(153) osIsrLevel153(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(154) osIsrLevel154(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(155) osIsrLevel155(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(156) osIsrLevel156(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(157) osIsrLevel157(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(158) osIsrLevel158(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(159) osIsrLevel159(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(160) osIsrLevel160(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(161) osIsrLevel161(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(162) osIsrLevel162(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(163) osIsrLevel163(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(164) osIsrLevel164(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(165) osIsrLevel165(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(166) osIsrLevel166(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(167) osIsrLevel167(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(168) osIsrLevel168(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(169) osIsrLevel169(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(170) osIsrLevel170(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(171) osIsrLevel171(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(172) osIsrLevel172(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(173) osIsrLevel173(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(174) osIsrLevel174(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(175) osIsrLevel175(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(176) osIsrLevel176(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(177) osIsrLevel177(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(178) osIsrLevel178(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(179) osIsrLevel179(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(180) osIsrLevel180(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(181) osIsrLevel181(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(182) osIsrLevel182(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(183) osIsrLevel183(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(184) osIsrLevel184(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(185) osIsrLevel185(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(186) osIsrLevel186(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(187) osIsrLevel187(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(188) osIsrLevel188(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(189) osIsrLevel189(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(190) osIsrLevel190(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(191) osIsrLevel191(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(192) osIsrLevel192(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(193) osIsrLevel193(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(194) osIsrLevel194(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(195) osIsrLevel195(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(196) osIsrLevel196(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(197) osIsrLevel197(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(198) osIsrLevel198(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(199) osIsrLevel199(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(200) osIsrLevel200(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(201) osIsrLevel201(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(202) osIsrLevel202(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(203) osIsrLevel203(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(204) osIsrLevel204(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(205) osIsrLevel205(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(206) osIsrLevel206(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(207) osIsrLevel207(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(208) osIsrLevel208(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(209) osIsrLevel209(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(210) osIsrLevel210(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(211) osIsrLevel211(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(212) osIsrLevel212(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(213) osIsrLevel213(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(214) osIsrLevel214(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(215) osIsrLevel215(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(216) osIsrLevel216(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(217) osIsrLevel217(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(218) osIsrLevel218(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(219) osIsrLevel219(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(220) osIsrLevel220(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(221) osIsrLevel221(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(222) osIsrLevel222(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(223) osIsrLevel223(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(224) osIsrLevel224(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(225) osIsrLevel225(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(226) osIsrLevel226(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(227) osIsrLevel227(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(228) osIsrLevel228(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(229) osIsrLevel229(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(230) osIsrLevel230(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(231) osIsrLevel231(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(232) osIsrLevel232(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(233) osIsrLevel233(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(234) osIsrLevel234(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(235) osIsrLevel235(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(236) osIsrLevel236(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(237) osIsrLevel237(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(238) osIsrLevel238(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(239) osIsrLevel239(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(240) osIsrLevel240(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(241) osIsrLevel241(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(242) osIsrLevel242(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(243) osIsrLevel243(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(244) osIsrLevel244(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(245) osIsrLevel245(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(246) osIsrLevel246(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(247) osIsrLevel247(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(248) osIsrLevel248(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(249) osIsrLevel249(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(250) osIsrLevel250(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(251) osIsrLevel251(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(252) osIsrLevel252(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(253) osIsrLevel253(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(254) osIsrLevel254(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}

/* MISRA RULE 14.1 not violated: Function is called from interrupt table (not recognized by MISRA tool) */
void __interrupt_fast(255) osIsrLevel255(void) /* PRQA S 1503 */
{
   osISRUnhandledException();
}


/*-+--------------------------------------------------------------------------
 / osISRUnhandledException                                                    
 / =======================                                                    
 /                                                                            
 / Syntax:                                                                    
 /   void osISRUnhandledException(void)                                       
 / Parameter (In):                                                            
 /   none                                                                     
 / Parameter (Out):                                                           
 /   none                                                                     
 / Description:                                                               
 /   Performs an indirect call of osUnhandledException as an interrupt vector 
 /   is to small to contain an indirect call. This function shall be linked   
 /   close to the interrupt vector table (+-16MB), while the operating        
 /   system might be linked to any location, independently from the location  
 /   of the interrupt vector table.                                           
 / Return value:                                                              
 /   none                                                                     
 /--------------------------------------------------------------------------*/

#pragma section code "UnhandledWrapper"

#if (osdVectorTableInRAM == 1)
#pragma section code_init
#endif

static void osISRUnhandledException(void)
{
   osUnhandledException();
}
#pragma section code restore



/* Addresses of SRC registers for all ISRs (containing interrupt enable bits) (defined in the configuration) */
#if (osdNumberOfCat2ISRs > 0)
   const osuint32 osSRCtab[osdNumberOfCat2ISRs] =
   {
      0xf00002fcUL,   /* osTimerInt */
   };

#else /*osdNumberOfCat2ISRs...*/
   const osuint32 osSRCtab[1] = {0};
#endif /*osdNumberOfCat2ISRs...*/
/*** $$$Begin Protected Area   -   do not change this line      ***/
/*** $$$End Protected Area    -    do not change this line      ***/

/* END OF C:\OS\OS2.0\tcb\intvect.c */

