/* double include preventer */
#ifndef _MSG_H
#define _MSG_H

/* file: msg.h, automatically generated by gentricAS.exe, Version: 5.05 */
/* configuration read from: C:\OS\OS2.0\OS_CONF.OIL */
/* generation at  : Thu Apr 21 09:39:04 2011 */
/* License CBD1000119 for BEIQI FOTON MOTOR CO.,LTD., beta license (valid from 2010-08-18 until 2011-08-31) */
/* Implementation: TriCore_1767 */
/* Version of general code: 5.15a */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 5
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif


#if (osdUseCOM != 0)
#if ((osdNumberOfMessagesToInitialize > 0) || osdLib)
   extern osqFunc1 void osqFunc2 osInitMessagesCOMStart(void);
#endif

#if osdNumberOfMessageQueues
   extern osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osMsgQueueReceivedMessages[osdNumberOfMessageQueues];
   extern osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osMsgStatus[osdNumberOfMessageQueues];
   extern osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osMsgQueueReadIndex[osdNumberOfMessageQueues];
   extern osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osMsgQueueWriteIndex[osdNumberOfMessageQueues];
#endif
#if osdNumberOfMsgFlagNotifics
extern osqTcbRAM1 osqTcbRAM2 FlagType osqTcbRAM3 osMsgFlags[osdNumberOfMsgFlagNotifics];
#endif

#if osdNumberOfRxMessages
   extern osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskMsgNumberOfReceiveMsgs[osdNumberOfRxMessages];
   extern osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskMsgLength[osdNumberOfRxMessages];
   extern osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskMsgQueueSize[osdNumberOfRxMessages];
   extern osqROM0 osqROM1 const osqROM2 ApplicationDataRef osqROM3 oskMsgDataBuffer[osdNumberOfRxMessages];
   extern osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskMsgIndexToQueueIndex[osdNumberOfRxMessages];

   extern osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskMsgNotifications[osdNumberOfRxMessages];
   extern osqROM0 osqROM1 const osqROM2 TaskType osqROM3 oskMsgNotifyTask[osdNumberOfRxMessages];
   extern osqROM0 osqROM1 const osqROM2 EventMaskType osqROM3 oskMsgNotifyEvent[osdNumberOfRxMessages];
#endif

#if osdNumberOfMsgCallbackNotifics
extern osqROM0 osqROM1 const osqROM2 osComCbFct osqROM3 oskMsgNotifyCallBack[osdNumberOfRxMessages];
#endif

#if osdNumberOfMsgFlagNotifics
extern osqROM0 osqROM1 const osqROM2 FlagType osqROM3 oskMsgNotifyFlagIndex[osdNumberOfRxMessages];
#endif

#if osdLib
   extern osqROM0 osqROM1 const osqROM2 MessageIdentifier osqROM3 oskNumberOfMessageQueues;
   extern osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskNumberOfMsgFlagNotifics;
   extern osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskNumberOfCOMModes;
   extern osqROM0 osqROM1 const osqROM2 MessageIdentifier osqROM3 oskNumberOfRxMessages;
#endif

#if osdNumberOfMsgCallbackNotifics
#endif /* osdNumberOfMsgCallbackNotifics */

#endif /* (osdUseCOM != 0)*/

#endif   /* double include preventer */

/* END OF C:\OS\OS2.0\tcb\msg.h */

