/* file: msg.c, automatically generated by gentricAS.exe, Version: 5.05 */
/* configuration read from: C:\OS\OS2.0\OS_CONF.OIL */
/* generation at  : Thu Apr 21 09:39:04 2011 */
/* License CBD1000119 for BEIQI FOTON MOTOR CO.,LTD., beta license (valid from 2010-08-18 until 2011-08-31) */
/* Implementation: TriCore_1767 */
/* Version of general code: 5.15a */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 5
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif

#if (osdUseCOM != 0)
/* data buffers */
/* data structures */
#if (osdNumberOfMessageQueues > 0)
osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osMsgQueueReceivedMessages[osdNumberOfMessageQueues];
osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osMsgStatus[osdNumberOfMessageQueues];
osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osMsgQueueReadIndex[osdNumberOfMessageQueues];
osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osMsgQueueWriteIndex[osdNumberOfMessageQueues];
#endif
#if osdNumberOfMsgFlagNotifics
osqTcbRAM1 osqTcbRAM2 FlagType osqTcbRAM3 osMsgFlags[osdNumberOfMsgFlagNotifics];
#endif

#if osdLib
   osqROM0 osqROM1 const osqROM2 MessageIdentifier osqROM3 oskNumberOfMessageQueues = osdNumberOfMessageQueues;
   osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskNumberOfMsgFlagNotifics =           osdNumberOfMsgFlagNotifics;
   osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskNumberOfCOMModes =                  osdNumberOfCOMModes;
   osqROM0 osqROM1 const osqROM2 MessageIdentifier osqROM3 oskNumberOfRxMessages =    osdNumberOfRxMessages;
#endif

#if osdNumberOfRxMessages
/* read by SendMessage */
osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskMsgNumberOfReceiveMsgs[osdNumberOfRxMessages] =
{
};
/* length of messages */
osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskMsgLength[osdNumberOfRxMessages] =
{
};
osqROM0 osqROM1 const osqROM2 ApplicationDataRef osqROM3 oskMsgDataBuffer[osdNumberOfRxMessages] =
{
};

osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskMsgNotifications[osdNumberOfRxMessages] =
{
};

osqROM0 osqROM1 const osqROM2 TaskType osqROM3 oskMsgNotifyTask[osdNumberOfRxMessages] =
{
};

osqROM0 osqROM1 const osqROM2 EventMaskType osqROM3 oskMsgNotifyEvent[osdNumberOfRxMessages] =
{
};

#endif

#if osdNumberOfMsgCallbackNotifics
osqROM0 osqROM1 const osqROM2 osComCbFct osqROM3 oskMsgNotifyCallBack[osdNumberOfRxMessages] =
{
};
#endif
#if osdNumberOfMsgFlagNotifics
/* index to flags */
osqROM0 osqROM1 const osqROM2 FlagType osqROM3 oskMsgNotifyFlagIndex[osdNumberOfRxMessages] =
{
};
#endif

#endif /* (osdUseCOM != 0)*/

/* END OF C:\OS\OS2.0\tcb\msg.c */

