/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with
 * message 0883 below. Anyhow, there is a double include prevention and therefore,
 * the message is considered to be wrong. */
/* double include preventer */
#ifndef _TRUSTCFT_H      /* PRQA S 0883 EOF */ /* see MISRA comment above */
#define _TRUSTCFT_H
/* file: trustfct.h, automatically generated by gentricAS.exe, Version: 5.05 */
/* configuration read from: C:\OS\OS2.0\OS_CONF.OIL */
/* generation at  : Thu Apr 21 09:39:04 2011 */
/* License CBD1000119 for BEIQI FOTON MOTOR CO.,LTD., beta license (valid from 2010-08-18 until 2011-08-31) */
/* Implementation: TriCore_1767 */
/* Version of general code: 5.15a */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 5
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif



		/* Trusted functions not used in SC1*/

/* END OF C:\OS\OS2.0\tcb\trustfct.h */

#endif /* _TRUSTCFT_H double include preventer */
